import { randomUUID } from 'node:crypto'
import { expect, test, type APIRequestContext, type Page } from '@playwright/test'

const tenantCode=required('PHASE10_P007_TENANT'),managerLogin=required('PHASE10_P007_LOGIN'),password=required('PHASE10_P007_PASSWORD')
const employeeLogin='phase10.p007.employee',reviewerLogin='phase10.p007.reviewer',techLogin='phase10.p007.tech',outLogin='phase10.p007.out'
const employeeId='30000000-0000-0000-0000-000000003028',api='http://127.0.0.1:18087',employeeBase='http://127.0.0.1:5313/employee.html',centerBase='http://127.0.0.1:5314/center.html',techBase='http://127.0.0.1:5315/admin.html'
interface Shift{id:string;businessNo:string;currentNodeCode:string;status:string;versionNo:number;reason:string|null;changeReason:string|null;startAt:string;endAt:string}
function required(n:string){const v=process.env[n];if(!v)throw new Error(`required E2E environment missing: ${n}`);return v}
function headers(token:string){return{Authorization:`Bearer ${token}`}}
async function apiLogin(request:APIRequestContext,loginName:string){const r=await request.post(`${api}/api/v1/auth/login`,{data:{tenantCode,loginName,password}});expect(r.status()).toBe(200);return((await r.json())as{accessToken:string}).accessToken}
async function login(page:Page,base:string,name:string,title:string){await page.goto(base);await page.evaluate(()=>sessionStorage.clear());await page.reload();await page.goto(`${base}#/login`);await page.getByLabel('租户编码').fill(tenantCode);await page.getByLabel('登录账号').fill(name);await page.getByLabel('密码').fill(password);await page.getByRole('button',{name:'登录'}).click();await expect(page.getByRole('heading',{name:title,level:1})).toBeVisible()}
async function getShift(request:APIRequestContext,token:string,id:string){const r=await request.get(`${api}/api/v1/processes/P007/shift-changes/${id}`,{headers:headers(token)});expect(r.status()).toBe(200);return await r.json()as Shift}
async function act(request:APIRequestContext,token:string,id:string,code:string,version:number,body:Record<string,unknown>={}){const r=await request.post(`${api}/api/v1/processes/P007/shift-changes/${id}/actions/${code}`,{headers:{...headers(token),'Idempotency-Key':`p007-${code.toLowerCase()}-${randomUUID()}`},data:{expectedVersion:version,reason:null,resultSummary:null,actualAttendanceSummary:null,proposedStartAt:null,proposedEndAt:null,substituteEmployeeId:null,handoverItems:[],evidence:null,...body}});return{status:r.status(),body:r.ok()?await r.json()as Shift:undefined}}
function local(offsetHours:number){return new Date(Date.now()+offsetHours*3_600_000).toISOString().slice(0,16)}
function evidence(note:string){return{note,recordedAt:new Date().toISOString()}}

test('P007 real schedule lifecycle spans center, employee, reviewer and tech portals',async({page,request})=>{
  const manager=await apiLogin(request,managerLogin),employee=await apiLogin(request,employeeLogin),tech=await apiLogin(request,techLogin),out=await apiLogin(request,outLogin)
  await login(page,centerBase,managerLogin,'中心管理工作入口');await page.goto(`${centerBase}#/center/04/01/01`);await expect(page.getByRole('heading',{name:'排班计划与班次调整',level:1})).toBeVisible()
  await page.getByLabel('排班主题').fill('P007 浏览器真实排班闭环');await page.getByLabel('目标员工 UUID').fill(employeeId);await page.getByLabel('资格/内容版本').fill('SAFE-V1');await page.getByLabel('排班周期').fill('P007-BROWSER-WEEK');await page.getByLabel('开始时间').fill(local(48));await page.getByLabel('结束时间').fill(local(56));await page.getByLabel('排班原因（至少 10 字）').fill('验证排班资格连续工时冲突交接及三门户权限闭环');await page.getByLabel('变更/制定原因').fill('依据业务量与活动安排制定八小时安全班次');await page.getByRole('button',{name:'保存排班需求'}).click();await expect(page.getByRole('status')).toContainText('已创建')
  const record=page.locator('article.record').filter({hasText:'P007 浏览器真实排班闭环'}).first();const id=await record.getAttribute('data-shift-id');expect(id).toBeTruthy();if(!id)throw new Error('P007 shift id not rendered')
  expect(await(await request.get(`${api}/api/v1/processes/P007/shift-changes`,{headers:headers(out)})).json()).toEqual([]);expect((await request.get(`${api}/api/v1/processes/P007/shift-changes/${id}`,{headers:headers(out)})).status()).toBe(403)
  const masked=await getShift(request,tech,id);expect(masked.reason).toBeNull();expect(masked.changeReason).toBeNull()
  let current=await getShift(request,manager,id);for(const code of['SUBMIT_DEMAND','MATCH_TEMPLATE','VALIDATE','PUBLISH']){const moved=await act(request,manager,id,code,current.versionNo);expect(moved.status).toBe(200);current=moved.body!}expect(current.currentNodeCode).toBe('S05')
  expect((await act(request,manager,id,'CONFIRM',current.versionNo,{evidence:evidence('manager must not confirm')})).status).toBe(403)
  await login(page,employeeBase,employeeLogin,'员工工作入口');await page.goto(`${employeeBase}#/employee/04/01/01`);const employeeRecord=page.locator(`article[data-shift-id="${id}"]`);await expect(employeeRecord).toContainText('S05');await page.getByLabel('联动/确认/日结证据').fill('员工已核对正式班次');await employeeRecord.getByRole('button',{name:'员工确认'}).click();await expect(employeeRecord).toContainText('S06')
  await page.getByLabel('处理或变更原因').fill('员工申请调整班次并完成当日任务交接');await page.getByLabel('拟调整开始').fill(local(49));await page.getByLabel('拟调整结束').fill(local(57));await page.getByLabel('交接项（每行一项）').fill('交接值守钥匙\n交接当日待办');await employeeRecord.getByRole('button',{name:'申请换班/替班'}).click();await expect(employeeRecord).toContainText('S07')
  current=await getShift(request,employee,id);expect((await act(request,employee,id,'APPROVE',current.versionNo)).status).toBe(403)
  await login(page,centerBase,reviewerLogin,'中心管理工作入口');await page.goto(`${centerBase}#/center/04/07/04`);const reviewRecord=page.locator(`article[data-shift-id="${id}"]`);await expect(reviewRecord).toContainText('S07');await page.getByLabel('处理或变更原因').fill('独立审批人复核资格与班次冲突通过');await reviewRecord.getByRole('button',{name:'批准变更'}).click();await expect(reviewRecord).toContainText('S08')
  current=await getShift(request,manager,id);let moved=await act(request,manager,id,'LINK',current.versionNo,{evidence:evidence('考勤餐饮班车三方回执')});expect(moved.status).toBe(200);current=moved.body!;moved=await act(request,manager,id,'CLOSE_DAY',current.versionNo,{resultSummary:'日结关闭',actualAttendanceSummary:'实际出勤八小时，联动结果一致',evidence:evidence('日结核对完成')});expect(moved.status).toBe(200);expect(moved.body?.currentNodeCode).toBe('END')
  await login(page,techBase,techLogin,'技术运行工作入口');await page.goto(`${techBase}#/tech/05/03/01`);await expect(page.getByRole('heading',{name:'P007 排班流程监控',level:1})).toBeVisible();const techRecord=page.locator(`article[data-shift-id="${id}"]`);await expect(techRecord).toContainText('END');await expect(techRecord).toContainText('原因、交接、前后快照和考勤事实已隐藏');await expect(techRecord.locator('.actions button')).toHaveCount(0);await expect(techRecord).not.toContainText('员工申请调整班次')
})
