<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import type { AuthzCapabilityType, AuthzModuleView, AuthzOrgModuleView, AuthzPermissionView, AuthzPositionRoleView, AuthzPreviewResult, AuthzReferenceData } from '../../../contracts'
import { usePortalSessionStore } from '../../../session'
import { createAuthzApi } from '../../../services/authz/authz-api'

type Mode='modules'|'module-permissions'|'org-modules'|'position-roles'|'preview'
const props=defineProps<{mode:Mode}>();const route=useRoute();const session=usePortalSessionStore();const api=createAuthzApi(session)
const loading=ref(false),saving=ref(false),error=ref(''),notice=ref(''),assertion=ref('')
const modules=ref<AuthzModuleView[]>([]),reference=ref<AuthzReferenceData>({organizations:[],positions:[],roles:[],permissions:[]})
const permissions=ref<AuthzPermissionView[]>([]),orgModules=ref<AuthzOrgModuleView[]>([]),positionRoles=ref<AuthzPositionRoleView[]>([]),preview=ref<AuthzPreviewResult|null>(null)
const moduleId=computed(()=>String(route.params.id??'')),orgId=ref(String(route.params.orgId??'')),positionId=ref(String(route.params.positionId??'')),directRoles=ref<string[]>([])
const selectedModule=computed(()=>modules.value.find(m=>m.id===moduleId.value));const title=computed(()=>({modules:'模块目录','module-permissions':'模块权限编排','org-modules':'组织模块配置','position-roles':'岗位角色配置',preview:'多角色权限模拟'} as const)[props.mode])
function msg(e:unknown){return e instanceof Error?e.message:'请求失败'}
async function run<T>(fn:()=>Promise<T>,ok?:string){error.value='';notice.value='';try{const r=await fn();if(ok)notice.value=ok;return r}catch(e){error.value=msg(e);return undefined}}
async function ticket(){if(!assertion.value.trim())throw new Error('高风险写操作需要先输入二次认证断言');const x=await api.issueStepUp(assertion.value.trim());return x.ticket}
async function load(){loading.value=true;try{const base=await run(()=>Promise.all([api.modules(),api.referenceData()]));if(!base)return;modules.value=base[0];reference.value=base[1];if(props.mode==='module-permissions'&&moduleId.value)permissions.value=(await run(()=>api.modulePermissions(moduleId.value)))??[];if(props.mode==='org-modules'){orgId.value ||= reference.value.organizations[0]?.id??'';if(orgId.value)orgModules.value=(await run(()=>api.orgModules(orgId.value)))??[]}if(props.mode==='position-roles'){positionId.value ||= reference.value.positions[0]?.id??'';if(positionId.value)positionRoles.value=(await run(()=>api.positionRoles(positionId.value)))??[]}if(props.mode==='preview'){orgId.value ||= reference.value.organizations[0]?.id??'';positionId.value ||= reference.value.positions.find(p=>p.orgId===orgId.value)?.id??reference.value.positions[0]?.id??''}}finally{loading.value=false}}
async function saveModulePermissions(){saving.value=true;try{const t=await ticket();const body=permissions.value.filter(p=>p.capabilityType).map(p=>({permissionId:p.id,capabilityType:p.capabilityType as AuthzCapabilityType}));permissions.value=(await run(()=>api.replaceModulePermissions(moduleId.value,body,t),'模块权限已保存'))??permissions.value}finally{saving.value=false}}
async function saveOrgModules(){saving.value=true;try{const t=await ticket();orgModules.value=(await run(()=>api.replaceOrgModules(orgId.value,orgModules.value.map(m=>({moduleId:m.moduleId,enabled:m.enabled,inheritToChildren:m.inheritToChildren,effectiveStartAt:m.effectiveStartAt,effectiveEndAt:m.effectiveEndAt,remark:m.remark})),t),'组织模块配置已保存'))??orgModules.value}finally{saving.value=false}}
async function savePositionRoles(){saving.value=true;try{const t=await ticket();positionRoles.value=(await run(()=>api.replacePositionRoles(positionId.value,positionRoles.value.filter(r=>r.selected).map(r=>({roleId:r.roleId,effectiveStartAt:r.effectiveStartAt,effectiveEndAt:r.effectiveEndAt,grantSource:r.grantSource??'POSITION_CONFIG'})),t),'岗位角色已保存'))??positionRoles.value}finally{saving.value=false}}
async function simulate(){preview.value=await run(()=>api.preview({orgId:orgId.value,positionId:positionId.value,directRoleIds:directRoles.value,effectiveAt:null}))??null}
watch(()=>props.mode,load);watch(orgId,async()=>{if(props.mode==='org-modules'&&orgId.value)orgModules.value=(await run(()=>api.orgModules(orgId.value)))??[]});watch(positionId,async()=>{if(props.mode==='position-roles'&&positionId.value)positionRoles.value=(await run(()=>api.positionRoles(positionId.value)))??[]});onMounted(load)
</script>
<template>
<section class="authz"><header><div><p>TECH · AUTHORIZATION</p><h2>{{ title }}</h2><span>模块层只收窄既有 RBAC 权限；配置预览不会写入正式授权表。</span></div><div class="kpis"><b>{{ modules.length }}</b><small>模块</small><b>{{ reference.roles.length }}</b><small>角色</small></div></header>
<p v-if="error" class="alert error">{{ error }}</p><p v-if="notice" class="alert ok">{{ notice }}</p><p v-if="loading" class="empty">正在加载真实权限配置…</p>
<template v-else>
<div v-if="mode==='modules'" class="grid"><article v-for="m in modules" :key="m.id"><div class="row"><strong>{{ m.moduleName }}</strong><i :class="{on:m.enabled}">{{ m.enabled?'启用':'停用' }}</i></div><code>{{ m.moduleCode }}</code><p>{{ m.moduleGroup||'未分组' }} · {{ m.permissionCount }} 个权限点</p><RouterLink :to="`/tech/authz/modules/${m.id}`">配置权限 →</RouterLink></article></div>
<div v-if="mode==='module-permissions'" class="panel"><h3>{{ selectedModule?.moduleName||'模块' }} · 权限档位</h3><div class="list"><label v-for="p in reference.permissions" :key="p.id"><span><b>{{ p.permissionName }}</b><code>{{ p.permissionCode }}</code></span><select v-model="p.capabilityType"><option :value="null">不归属</option><option>VIEW</option><option>OPERATE</option><option>APPROVE</option><option>ADMIN</option></select><em>{{ p.riskLevel }}</em></label></div><div class="write"><input v-model="assertion" placeholder="二次认证断言 / TOTP"><button :disabled="saving" @click="saveModulePermissions">保存模块权限</button></div></div>
<div v-if="mode==='org-modules'" class="panel"><div class="toolbar"><select v-model="orgId"><option v-for="o in reference.organizations" :key="o.id" :value="o.id">{{ o.orgName }}</option></select></div><div class="grid"><article v-for="m in orgModules" :key="m.moduleId"><label class="switch"><input v-model="m.enabled" type="checkbox"><strong>{{ m.moduleName }}</strong></label><label class="switch"><input v-model="m.inheritToChildren" type="checkbox">继承到下级组织</label><code>{{ m.moduleCode }}</code></article></div><div class="write"><input v-model="assertion" placeholder="二次认证断言 / TOTP"><button :disabled="saving" @click="saveOrgModules">保存组织配置</button></div></div>
<div v-if="mode==='position-roles'" class="panel"><div class="toolbar"><select v-model="positionId"><option v-for="p in reference.positions" :key="p.id" :value="p.id">{{ p.positionName }}</option></select></div><div class="grid"><label v-for="r in positionRoles" :key="r.roleId" class="role"><input v-model="r.selected" type="checkbox"><span><b>{{ r.roleName }}</b><code>{{ r.roleCode }}</code><small>数据范围 {{ r.dataScopeCode||'未设置' }}</small></span></label></div><div class="write"><input v-model="assertion" placeholder="二次认证断言 / TOTP"><button :disabled="saving" @click="savePositionRoles">保存岗位角色</button></div></div>
<div v-if="mode==='preview'" class="panel"><div class="form"><label>组织<select v-model="orgId"><option v-for="o in reference.organizations" :key="o.id" :value="o.id">{{ o.orgName }}</option></select></label><label>岗位<select v-model="positionId"><option v-for="p in reference.positions.filter(x=>!orgId||x.orgId===orgId)" :key="p.id" :value="p.id">{{ p.positionName }}</option></select></label></div><h3>额外模拟直接角色</h3><div class="chips"><label v-for="r in reference.roles" :key="r.id"><input v-model="directRoles" type="checkbox" :value="r.id">{{ r.roleName }}</label></div><button class="primary" @click="simulate">运行多角色模拟</button><div v-if="preview" class="result"><h3>有效权限 {{ preview.effectivePermissionCodes.length }} · 被模块过滤 {{ preview.filteredPermissionCodes.length }}</h3><div class="perm"><article v-for="p in preview.permissions" :key="p.permissionCode" :class="{blocked:!p.effective}"><b>{{ p.permissionName }}</b><code>{{ p.permissionCode }}</code><small>{{ p.reason }}</small></article></div></div></div>
</template></section>
</template>
<style scoped>
.authz{display:grid;gap:14px;color:#0f172a}.authz header,.panel,article{background:#fff;border:1px solid rgba(15,23,42,.08);border-radius:16px}.authz header{display:flex;justify-content:space-between;gap:20px;padding:20px}.authz header p{margin:0;color:#ea580c;font-size:11px;font-weight:800;letter-spacing:.12em}.authz h2{margin:5px 0;font-size:24px}.authz header span,.authz small{color:#64748b}.kpis{display:grid;grid-template-columns:auto auto;align-content:center;gap:3px 8px}.kpis b{font-size:22px;color:#ea580c}.kpis small{font-size:11px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:12px}.grid article{padding:15px}.row,.toolbar,.write,.form{display:flex;align-items:center;gap:10px}.row{justify-content:space-between}.row i{font-style:normal;font-size:11px;padding:3px 8px;border-radius:999px;background:#f1f5f9;color:#64748b}.row i.on{background:#ecfdf5;color:#047857}.authz code{display:block;margin-top:5px;color:#9a3412;font-size:11px}.authz article p{color:#64748b;font-size:12px}.authz a{color:#ea580c;font-weight:700;text-decoration:none}.panel{padding:18px}.panel h3{margin:0 0 12px}.list{display:grid;max-height:520px;overflow:auto;border:1px solid #e2e8f0;border-radius:12px}.list>label{display:grid;grid-template-columns:1fr 150px 70px;gap:12px;align-items:center;padding:10px 12px;border-bottom:1px solid #eef2f7}.list b,.list code{display:block}.list code{margin:2px 0 0}.list em{font-style:normal;font-size:11px;color:#64748b}.authz select,.authz input{min-height:40px;padding:8px 10px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;font:inherit}.write{justify-content:flex-end;margin-top:14px}.write input{min-width:280px}.authz button{min-height:40px;padding:0 16px;border:0;border-radius:10px;background:#ea580c;color:#fff;font-weight:700;cursor:pointer}.switch,.role,.chips label{display:flex;gap:8px;align-items:center}.switch{margin:8px 0}.role{padding:12px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.role input,.switch input,.chips input{min-height:auto}.role span{display:grid;gap:2px}.form{flex-wrap:wrap}.form label{display:grid;gap:5px;min-width:260px}.chips{display:flex;flex-wrap:wrap;gap:8px}.chips label{padding:7px 10px;border:1px solid #e2e8f0;border-radius:999px;font-size:12px}.primary{margin-top:14px}.result{margin-top:18px}.perm{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:8px}.perm article{padding:12px;border-left:3px solid #059669}.perm article.blocked{border-left-color:#e11d48;background:#fff7f8}.perm small{display:block;margin-top:5px}.alert{padding:10px 13px;border-radius:10px}.alert.error{background:#fff1f2;color:#be123c}.alert.ok{background:#ecfdf5;color:#047857}.empty{text-align:center;padding:40px;color:#64748b}@media(max-width:720px){.authz header{flex-direction:column}.list>label{grid-template-columns:1fr}.write{align-items:stretch;flex-direction:column}.write input{min-width:0}}
</style>
