package cn.shangjingu.platform.api;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import org.flywaydb.core.Flyway;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

/** Real PHASE-10 / P007 Spring Boot + PostgreSQL16 + Redis browser fixture. */
public final class Phase10P007BrowserBackendFixture {
    private static final UUID TENANT=uuid("00000000-0000-0000-0000-000000002027"),CENTER_A=uuid("10000000-0000-0000-0000-000000003027"),CENTER_B=uuid("10000000-0000-0000-0000-000000003028"),POS_A=uuid("20000000-0000-0000-0000-000000003027"),POS_B=uuid("20000000-0000-0000-0000-000000003028");
    private static final UUID MANAGER=uuid("30000000-0000-0000-0000-000000003027"),EMPLOYEE=uuid("30000000-0000-0000-0000-000000003028"),REVIEWER=uuid("30000000-0000-0000-0000-000000003029"),TECH=uuid("30000000-0000-0000-0000-000000003030"),OUT=uuid("30000000-0000-0000-0000-000000003031");
    private static final String API_PASSWORD="p007_browser_api_"+shortId(),AUDIT_PASSWORD="p007_browser_audit_"+shortId();
    private Phase10P007BrowserBackendFixture(){}
    public static void main(String[] args)throws Exception{
        String tenant=required("PHASE10_P007_TENANT"),managerLogin=required("PHASE10_P007_LOGIN"),password=required("PHASE10_P007_PASSWORD");
        PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:16.14-alpine3.24").withDatabaseName("postgres").withUsername("postgres").withPassword("bootstrap-"+shortId());GenericContainer<?> redis=new GenericContainer<>(DockerImageName.parse("redis:7.4-alpine")).withExposedPorts(6379);
        postgres.start();redis.start();prepare(postgres,tenant,managerLogin,password);ConfigurableApplicationContext context=startApi(postgres,redis);writeFacts(postgres,redis);Runtime.getRuntime().addShutdownHook(new Thread(()->{context.close();redis.stop();postgres.stop();}));System.out.println("PHASE10_P007_BROWSER_FIXTURE_READY");new CountDownLatch(1).await();
    }
    private static ConfigurableApplicationContext startApi(PostgreSQLContainer<?> p,GenericContainer<?> r){return new SpringApplication(ApiApplication.class).run("--server.port=18087","--spring.flyway.enabled=false","--spring.datasource.url="+url(p,"sjg_oms"),"--spring.datasource.username=sjg_api_runtime","--spring.datasource.password="+API_PASSWORD,"--spring.data.redis.host="+r.getHost(),"--spring.data.redis.port="+r.getMappedPort(6379),"--sjg.audit.datasource.url="+url(p,"sjg_audit"),"--sjg.audit.datasource.username=sjg_audit_writer","--sjg.audit.datasource.password="+AUDIT_PASSWORD,"--sjg.security.session.access-ttl=PT30M","--sjg.security.session.refresh-ttl=PT1H");}
    private static void prepare(PostgreSQLContainer<?> p,String tenant,String managerLogin,String password)throws Exception{
        Path root=root();Flyway.configure().dataSource(p.getJdbcUrl(),p.getUsername(),p.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/cluster")).cleanDisabled(true).load().migrate();try(Connection c=DriverManager.getConnection(p.getJdbcUrl(),p.getUsername(),p.getPassword());Statement s=c.createStatement()){s.execute("alter role sjg_api_runtime password '"+API_PASSWORD+"'");s.execute("alter role sjg_audit_writer password '"+AUDIT_PASSWORD+"'");s.execute("create database sjg_oms");s.execute("create database sjg_audit");}
        Flyway.configure().dataSource(url(p,"sjg_oms"),p.getUsername(),p.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/oms"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/oms")).placeholders(Map.of("sjg_tenant_id",TENANT.toString(),"sjg_tenant_code",tenant,"sjg_tenant_name","P007 Browser Tenant")).cleanDisabled(true).load().migrate();Flyway.configure().dataSource(url(p,"sjg_audit"),p.getUsername(),p.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/audit"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/audit")).cleanDisabled(true).load().migrate();seed(p,managerLogin,password);
    }
    private static void seed(PostgreSQLContainer<?> p,String managerLogin,String password)throws Exception{
        String hash=new BCryptPasswordEncoder(12).encode(password);try(Connection c=DriverManager.getConnection(url(p,"sjg_oms"),p.getUsername(),p.getPassword());Statement s=c.createStatement()){
            s.execute("insert into org.organization(id,tenant_id,org_code,org_name,org_type,path,status) values ('"+CENTER_A+"','"+TENANT+"','P007_A','P007 Center A','CENTER','p007_a'::ltree,'ACTIVE'),('"+CENTER_B+"','"+TENANT+"','P007_B','P007 Center B','CENTER','p007_b'::ltree,'ACTIVE')");s.execute("insert into org.position(id,tenant_id,position_code,position_name,org_id,status) values ('"+POS_A+"','"+TENANT+"','P007_PA','P007 Position A','"+CENTER_A+"','ACTIVE'),('"+POS_B+"','"+TENANT+"','P007_PB','P007 Position B','"+CENTER_B+"','ACTIVE')");
            UUID[] es={MANAGER,EMPLOYEE,REVIEWER,TECH,OUT};for(int i=0;i<es.length;i++){UUID center=i==4?CENTER_B:CENTER_A,pos=i==4?POS_B:POS_A;s.execute("insert into org.employee(id,tenant_id,employee_no,person_name,employment_status,hire_date,primary_org_id,primary_position_id) values ('"+es[i]+"','"+TENANT+"','P007-B00"+(i+1)+"','P007 Browser Actor "+i+"','ACTIVE',current_date-30,'"+center+"','"+pos+"')");}
            s.execute("insert into learning.learning_assignment(id,tenant_id,business_no,status,version_no,created_by,updated_by,owner_center_id,owner_employee_id,content_version,course_team_name,course_version_id,period_or_course_no,practical_result,qualification_effective_date,qualification_expire_date) values (gen_random_uuid(),'"+TENANT+"','P007-BROWSER-QUAL','QUALIFIED',1,'"+MANAGER+"','"+MANAGER+"','"+CENTER_A+"','"+EMPLOYEE+"','SAFE-V1','安全值班课程','SAFE-V1','SAFE-COURSE','PASS',current_date-30,current_date+365)");
            s.execute("insert into iam.data_scope_rule(tenant_id,scope_code,scope_name,rule_expr,enabled) values ('"+TENANT+"','P007_SELF','P007 Self','{\"scope\":\"SELF\"}'::jsonb,true),('"+TENANT+"','P007_CENTER','P007 Center','{\"scope\":\"CENTER\"}'::jsonb,true)");s.execute("insert into iam.permission(id,tenant_id,permission_code,permission_name,resource_type,action_code,risk_level) values (gen_random_uuid(),'"+TENANT+"','platform.session.read','Session read','SESSION','READ','NORMAL'),(gen_random_uuid(),'"+TENANT+"','platform.session.logout','Session logout','SESSION','LOGOUT','NORMAL')");
            String[][] actors={{managerLogin,"CENTER","p007.schedule.read,p007.schedule.manage"},{"phase10.p007.employee","SELF","p007.schedule.read,p007.schedule.change"},{"phase10.p007.reviewer","CENTER","p007.schedule.read,p007.schedule.review"},{"phase10.p007.tech","CENTER","p007.schedule.monitor"},{"phase10.p007.out","CENTER","p007.schedule.read"}};for(int i=0;i<actors.length;i++)seedActor(s,i,es[i],actors[i][0],actors[i][1],actors[i][2],hash,i==4?CENTER_B:CENTER_A,i==4?POS_B:POS_A);
        }
    }
    private static void seedActor(Statement s,int i,UUID employee,String login,String scope,String permissions,String hash,UUID center,UUID pos)throws Exception{UUID user=derived(4,i),identity=derived(5,i),role=derived(6,i),appointment=derived(7,i);String code="P007_BROWSER_"+i;s.execute("insert into org.employee_position(id,tenant_id,employee_id,position_id,org_id,is_primary,effective_start_date,status) values ('"+appointment+"','"+TENANT+"','"+employee+"','"+pos+"','"+center+"',true,current_date-30,'ACTIVE')");s.execute("insert into iam.user_account(id,tenant_id,login_name,password_hash,status,mfa_level) values ('"+user+"','"+TENANT+"','"+login+"','"+hash+"','ACTIVE',0)");s.execute("insert into iam.user_identity(id,tenant_id,user_id,employee_id,identity_type,identity_name,org_id,position_id,is_primary,effective_start_at) values ('"+identity+"','"+TENANT+"','"+user+"','"+employee+"','EMPLOYEE','P007 "+login+"','"+center+"','"+pos+"',true,now()-interval '1 day')");s.execute("insert into iam.role(id,tenant_id,role_code,role_name,role_type,data_scope_code,enabled) values ('"+role+"','"+TENANT+"','"+code+"','"+code+"','PLATFORM','P007_"+scope+"',true)");s.execute("insert into iam.role_permission(tenant_id,role_id,permission_id) select '"+TENANT+"','"+role+"',id from iam.permission where tenant_id='"+TENANT+"' and permission_code in ('platform.session.read','platform.session.logout','"+permissions.replace(",","','")+"') and not is_deleted");s.execute("insert into iam.user_role(tenant_id,user_id,identity_id,role_id,effective_start_at,grant_source) values ('"+TENANT+"','"+user+"','"+identity+"','"+role+"',now()-interval '1 day','TEST_ONLY')");}
    private static void writeFacts(PostgreSQLContainer<?> p,GenericContainer<?> r)throws Exception{Path out=root().resolve("technical-platform/backend/apps/api/target/phase10-p007-fixture-runtime.json");Files.createDirectories(out.getParent());Files.writeString(out,"{\n  \"postgresContainerId\": \""+p.getContainerId()+"\",\n  \"redisContainerId\": \""+r.getContainerId()+"\",\n  \"tenantId\": \""+TENANT+"\",\n  \"employeeId\": \""+EMPLOYEE+"\"\n}\n");}
    private static String url(PostgreSQLContainer<?> p,String db){return "jdbc:postgresql://"+p.getHost()+":"+p.getMappedPort(5432)+"/"+db;}private static String required(String n){String v=System.getenv(n);if(v==null||v.isBlank())throw new IllegalStateException("required environment missing: "+n);return v;}private static UUID derived(int g,int i){return uuid("%d0000000-0000-0000-0000-%012d".formatted(g,3027+i));}private static UUID uuid(String v){return UUID.fromString(v);}private static String shortId(){return UUID.randomUUID().toString().replace("-","").substring(0,16);}private static Path root(){Path p=Path.of("").toAbsolutePath();while(p!=null){if(Files.exists(p.resolve("AGENT.md")))return p;p=p.getParent();}throw new IllegalStateException("repository root not found");}
}
