package cn.shangjingu.platform.api;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Map;
import java.util.UUID;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

@SpringBootTest(classes=ApiApplication.class)
@AutoConfigureMockMvc
class Phase11P014IntegrationTest {
    private static final UUID TENANT=id("00000000-0000-0000-0000-000000002014"),CENTER_A=id("10000000-0000-0000-0000-000000003514"),CENTER_B=id("10000000-0000-0000-0000-000000003515"),POSITION_A=id("20000000-0000-0000-0000-000000003514"),POSITION_B=id("20000000-0000-0000-0000-000000003515"),AFFECTED=id("30000000-0000-0000-0000-000000003514"),MANAGER=id("30000000-0000-0000-0000-000000003515"),INVESTIGATOR=id("30000000-0000-0000-0000-000000003516"),REVIEWER=id("30000000-0000-0000-0000-000000003517"),DECIDER=id("30000000-0000-0000-0000-000000003518"),APPEAL_REVIEWER=id("30000000-0000-0000-0000-000000003519"),TECH=id("30000000-0000-0000-0000-000000003520"),OUTSIDER=id("30000000-0000-0000-0000-000000003521");private static final String PASSWORD="P014-Live-Test-9q!",API_PASSWORD="p014_api_"+shortId(),AUDIT_PASSWORD="p014_audit_"+shortId();private static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:16.14-alpine3.24").withDatabaseName("postgres").withUsername("postgres").withPassword("bootstrap-"+shortId());private static final GenericContainer<?> REDIS=new GenericContainer<>(DockerImageName.parse("redis:7.4-alpine")).withExposedPorts(6379);
    static{POSTGRES.start();REDIS.start();try{prepare();}catch(Exception e){POSTGRES.stop();REDIS.stop();throw new ExceptionInInitializerError(e);}}
    @Autowired MockMvc mvc;@Autowired ObjectMapper mapper;
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->url("sjg_oms"));r.add("spring.datasource.username",()->"sjg_api_runtime");r.add("spring.datasource.password",()->API_PASSWORD);r.add("spring.data.redis.host",REDIS::getHost);r.add("spring.data.redis.port",()->REDIS.getMappedPort(6379));r.add("sjg.audit.datasource.url",()->url("sjg_audit"));r.add("sjg.audit.datasource.username",()->"sjg_audit_writer");r.add("sjg.audit.datasource.password",()->AUDIT_PASSWORD);}
    @AfterAll static void stop(){REDIS.stop();POSTGRES.stop();}
    @Test void realHttpLifecycleSeparatesInvestigationDecisionAppealAndDownstreamExecution()throws Exception{
        String affected=login("affected"),manager=login("manager"),investigator=login("investigator"),reviewer=login("reviewer"),decider=login("decider"),appealReviewer=login("appeal"),tech=login("tech"),outsider=login("outsider");ObjectNode create=create("DISCIPLINE-SOURCE-P014-001");
        mvc.perform(post("/api/v1/processes/P014/discipline-cases").contentType(MediaType.APPLICATION_JSON).content(create.toString()).header("Idempotency-Key","unauth")).andExpect(status().isUnauthorized());
        JsonNode current=json(mvc.perform(post("/api/v1/processes/P014/discipline-cases").header("Authorization",bearer(manager)).header("Idempotency-Key","create-discipline").contentType(MediaType.APPLICATION_JSON).content(create.toString())).andExpect(status().isOk()).andReturn());String id=current.path("id").asText();assertEquals("S01",current.path("currentNodeCode").asText());assertEquals(id,json(mvc.perform(post("/api/v1/processes/P014/discipline-cases").header("Authorization",bearer(manager)).header("Idempotency-Key","create-discipline").contentType(MediaType.APPLICATION_JSON).content(create.toString())).andExpect(status().isOk()).andReturn()).path("id").asText());mvc.perform(post("/api/v1/processes/P014/discipline-cases").header("Authorization",bearer(manager)).header("Idempotency-Key","duplicate-source").contentType(MediaType.APPLICATION_JSON).content(create.toString())).andExpect(status().isConflict());
        assertEquals(0,json(mvc.perform(get("/api/v1/processes/P014/discipline-cases").header("Authorization",bearer(outsider))).andExpect(status().isOk()).andReturn()).size());mvc.perform(get("/api/v1/processes/P014/discipline-cases/"+id).header("Authorization",bearer(outsider))).andExpect(status().isForbidden());JsonNode masked=json(mvc.perform(get("/api/v1/processes/P014/discipline-cases/"+id).header("Authorization",bearer(tech))).andExpect(status().isOk()).andReturn());assertTrue(masked.path("reason").isNull());assertTrue(masked.path("affectedEmployeeId").isNull());assertTrue(masked.path("sourceFactKey").isNull());assertTrue(masked.path("factSummary").isNull());assertTrue(masked.path("events").isArray()&&masked.path("events").isEmpty());assertTrue(masked.path("decisions").isArray()&&masked.path("decisions").isEmpty());
        mvc.perform(post(actionUrl(id,"REGISTER_CLUE")).header("Authorization",bearer(manager)).header("Idempotency-Key","stale").contentType(MediaType.APPLICATION_JSON).content(action(0).toString())).andExpect(status().isConflict());current=act(manager,id,"REGISTER_CLUE",1,action(1),"clue");current=act(manager,id,"RECORD_SAFEGUARD",2,action(2),"safeguard");mvc.perform(post(actionUrl(id,"COMPLETE_INVESTIGATION")).header("Authorization",bearer(affected)).header("Idempotency-Key","self-investigate").contentType(MediaType.APPLICATION_JSON).content(action(3).toString())).andExpect(status().isConflict());current=act(investigator,id,"COMPLETE_INVESTIGATION",3,action(3),"investigation");current=act(affected,id,"SUBMIT_STATEMENT",4,action(4),"statement");mvc.perform(post(actionUrl(id,"COMPLETE_RESPONSIBILITY_REVIEW")).header("Authorization",bearer(investigator)).header("Idempotency-Key","self-review").contentType(MediaType.APPLICATION_JSON).content(action(5).toString())).andExpect(status().isConflict());current=act(reviewer,id,"COMPLETE_RESPONSIBILITY_REVIEW",5,action(5),"responsibility-review");mvc.perform(post(actionUrl(id,"RECORD_DECISION")).header("Authorization",bearer(affected)).header("Idempotency-Key","self-decision").contentType(MediaType.APPLICATION_JSON).content(action(6).put("authorityReference","AUTH-SELF-BLOCKED").put("decidedAt",Instant.now().toString()).toString())).andExpect(status().isConflict());current=act(decider,id,"RECORD_DECISION",6,action(6).put("authorityReference","EXTERNAL-HR-AUTH-P014-001").put("decidedAt",Instant.now().toString()),"decision");current=act(affected,id,"CONFIRM_SERVICE",7,action(7),"service");
        JdbcTemplate oms=jdbc("sjg_oms",POSTGRES.getUsername(),POSTGRES.getPassword());assertEquals(0,oms.queryForObject("select count(*) from reward.point_transaction where tenant_id=?",Integer.class,TENANT));assertEquals(8,oms.queryForObject("select count(*) from org.employee_position where tenant_id=?",Integer.class,TENANT));current=act(manager,id,"RECORD_IMPACT",8,action(8).put("impactType","POINT_ADJUSTMENT").put("authorityReference","EXTERNAL-IMPACT-AUTH-P014-001"),"impact");UUID instruction=impactId(current,"POINT_ADJUSTMENT");mvc.perform(post(actionUrl(id,"COMPLETE_IMPACTS")).header("Authorization",bearer(manager)).header("Idempotency-Key","missing-receipt").contentType(MediaType.APPLICATION_JSON).content(action(9).toString())).andExpect(status().isConflict());mvc.perform(post(actionUrl(id,"RECORD_RECEIPT")).header("Authorization",bearer(manager)).header("Idempotency-Key","wrong-receipt").contentType(MediaType.APPLICATION_JSON).content(action(9).put("instructionId",instruction.toString()).put("receiptType","HR_CASE_RECEIPT").put("externalReference","WRONG-RECEIPT").put("externalOccurredAt",Instant.now().toString()).toString())).andExpect(status().isConflict());current=act(manager,id,"RECORD_RECEIPT",9,action(9).put("instructionId",instruction.toString()).put("receiptType","P015_POINT_LEDGER").put("externalReference","P015-LEDGER-P014-001").put("externalOccurredAt",Instant.now().toString()),"receipt");current=act(manager,id,"COMPLETE_IMPACTS",10,action(10),"impacts-complete");
        current=act(affected,id,"SUBMIT_APPEAL",11,action(11).put("appealRequested",true),"appeal-submit");assertEquals("S09",current.path("currentNodeCode").asText());mvc.perform(post(actionUrl(id,"REVIEW_APPEAL")).header("Authorization",bearer(decider)).header("Idempotency-Key","decider-appeal").contentType(MediaType.APPLICATION_JSON).content(action(12).put("decisionOutcome","UPHELD").put("authorityReference","APPEAL-SELF-BLOCKED").put("decidedAt",Instant.now().toString()).toString())).andExpect(status().isConflict());current=act(appealReviewer,id,"REVIEW_APPEAL",12,action(12).put("decisionOutcome","AMENDED").put("authorityReference","EXTERNAL-APPEAL-P014-001").put("decidedAt",Instant.now().toString()),"appeal-review");current=act(manager,id,"CLOSE_CORE",13,action(13),"core-close");current=act(manager,id,"VERIFY_REMEDIATION",14,action(14).put("authorityReference","REMEDIATION-VERIFY-P014-001"),"remediation");current=act(manager,id,"SUPPLEMENT_ARCHIVE",15,action(15),"archive");assertEquals("END",current.path("currentNodeCode").asText());assertEquals(2,oms.queryForObject("select count(*) from reward.discipline_decision_fact where tenant_id=? and discipline_case_id=?",Integer.class,TENANT,UUID.fromString(id)));assertEquals(0,oms.queryForObject("select count(*) from reward.point_transaction where tenant_id=?",Integer.class,TENANT));assertTrue(jdbc("sjg_audit",POSTGRES.getUsername(),POSTGRES.getPassword()).queryForObject("select count(*) from audit.operation_log where tenant_id=? and resource_id=? and action like 'P014_%'",Integer.class,TENANT,UUID.fromString(id))>=18);
    }
    private UUID impactId(JsonNode value,String type){for(JsonNode impact:value.path("impacts"))if(type.equals(impact.path("impactType").asText()))return UUID.fromString(impact.path("id").asText());throw new IllegalStateException("missing impact "+type);}private JsonNode act(String token,String id,String code,int version,ObjectNode body,String key)throws Exception{assertEquals(version,body.path("expectedVersion").asInt());return json(mvc.perform(post(actionUrl(id,code)).header("Authorization",bearer(token)).header("Idempotency-Key",key).contentType(MediaType.APPLICATION_JSON).content(body.toString())).andExpect(status().isOk()).andReturn());}private ObjectNode action(int version){return mapper.createObjectNode().put("expectedVersion",version).putNull("decisionOutcome").putNull("authorityReference").putNull("decidedAt").putNull("impactType").putNull("instructionId").putNull("receiptType").putNull("externalReference").putNull("externalOccurredAt").putNull("appealRequested").put("resultSummary","P014 source fact accepted").set("evidence",evidence("immutable "+version));}private ObjectNode create(String source){return mapper.createObjectNode().put("businessDate",LocalDate.now().toString()).put("subject","2026 private discipline clue review").put("reason","Source-backed clue requires independent human review").put("affectedEmployeeId",AFFECTED.toString()).put("sourceFactKey",source).put("businessObjectType","INTERNAL_CASE").put("businessObjectNo","CASE-OBJ-P014-001").put("businessObjectName","Internal duty event").put("employeeEventType","DISCIPLINE_CLUE").put("factOccurredAt",Instant.now().minusSeconds(3600).toString()).put("factSummary","Verified private clue package retained for formal investigation").put("impactLevel","L2").set("evidence",evidence("private clue package"));}private ObjectNode evidence(String note){return mapper.createObjectNode().put("note",note).put("recordedAt",Instant.now().toString());}private String login(String name)throws Exception{return json(mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content(mapper.createObjectNode().put("tenantCode","PHASE11_P014").put("loginName","p014."+name).put("password",PASSWORD).toString())).andExpect(status().isOk()).andReturn()).path("accessToken").asText();}private JsonNode json(MvcResult result)throws Exception{return mapper.readTree(result.getResponse().getContentAsByteArray());}private static String bearer(String token){return"Bearer "+token;}private static String actionUrl(String id,String action){return"/api/v1/processes/P014/discipline-cases/"+id+"/actions/"+action;}
    private static void prepare()throws Exception{Path root=root();Flyway.configure().dataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/cluster")).cleanDisabled(true).load().migrate();try(Connection c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword());Statement s=c.createStatement()){s.execute("alter role sjg_api_runtime password '"+API_PASSWORD+"'");s.execute("alter role sjg_audit_writer password '"+AUDIT_PASSWORD+"'");s.execute("create database sjg_oms");s.execute("create database sjg_audit");}Flyway.configure().dataSource(url("sjg_oms"),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/oms"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/oms")).placeholders(Map.of("sjg_tenant_id",TENANT.toString(),"sjg_tenant_code","PHASE11_P014","sjg_tenant_name","P014 Integration Tenant")).cleanDisabled(true).load().migrate();Flyway.configure().dataSource(url("sjg_audit"),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/audit"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/audit")).cleanDisabled(true).load().migrate();seed();}
    private static void seed()throws Exception{String hash=new BCryptPasswordEncoder(12).encode(PASSWORD);try(Connection c=DriverManager.getConnection(url("sjg_oms"),POSTGRES.getUsername(),POSTGRES.getPassword());Statement s=c.createStatement()){s.execute("insert into org.organization(id,tenant_id,org_code,org_name,org_type,path,status) values ('"+CENTER_A+"','"+TENANT+"','P014_A','P014 Center A','CENTER','p014_a'::ltree,'ACTIVE'),('"+CENTER_B+"','"+TENANT+"','P014_B','P014 Center B','CENTER','p014_b'::ltree,'ACTIVE')");s.execute("insert into org.position(id,tenant_id,position_code,position_name,org_id,status) values ('"+POSITION_A+"','"+TENANT+"','P014_A','P014 Position A','"+CENTER_A+"','ACTIVE'),('"+POSITION_B+"','"+TENANT+"','P014_B','P014 Position B','"+CENTER_B+"','ACTIVE')");UUID[] actors={AFFECTED,MANAGER,INVESTIGATOR,REVIEWER,DECIDER,APPEAL_REVIEWER,TECH,OUTSIDER};for(int i=0;i<actors.length;i++){UUID center=i==7?CENTER_B:CENTER_A,position=i==7?POSITION_B:POSITION_A;s.execute("insert into org.employee(id,tenant_id,employee_no,person_name,employment_status,hire_date,primary_org_id,primary_position_id) values ('"+actors[i]+"','"+TENANT+"','P014-E00"+(i+1)+"','P014 Actor "+i+"','ACTIVE',current_date-90,'"+center+"','"+position+"')");}s.execute("insert into iam.data_scope_rule(tenant_id,scope_code,scope_name,rule_expr,enabled) values ('"+TENANT+"','P014_SELF','P014 Self','{\"scope\":\"SELF\"}'::jsonb,true),('"+TENANT+"','P014_CENTER','P014 Center','{\"scope\":\"CENTER\"}'::jsonb,true)");s.execute("insert into iam.permission(id,tenant_id,permission_code,permission_name,resource_type,action_code,risk_level) values (gen_random_uuid(),'"+TENANT+"','platform.session.read','Session read','SESSION','READ','NORMAL'),(gen_random_uuid(),'"+TENANT+"','platform.session.logout','Session logout','SESSION','LOGOUT','NORMAL')");String[][] roles={{"affected","SELF","p014.discipline.read,p014.discipline.appeal,p014.discipline.manage,p014.discipline.investigate,p014.discipline.decide"},{"manager","CENTER","p014.discipline.read,p014.discipline.manage"},{"investigator","CENTER","p014.discipline.read,p014.discipline.investigate"},{"reviewer","CENTER","p014.discipline.read,p014.discipline.investigate"},{"decider","CENTER","p014.discipline.read,p014.discipline.decide,p014.discipline.appeal"},{"appeal","CENTER","p014.discipline.read,p014.discipline.appeal"},{"tech","CENTER","p014.discipline.monitor"},{"outsider","CENTER","p014.discipline.read"}};for(int i=0;i<roles.length;i++)seedActor(s,i,actors[i],roles[i][0],roles[i][1],roles[i][2],hash,i==7?CENTER_B:CENTER_A,i==7?POSITION_B:POSITION_A);}}
    private static void seedActor(Statement s,int index,UUID employee,String login,String scope,String permissions,String hash,UUID center,UUID position)throws Exception{UUID user=derived(4,index),identity=derived(5,index),role=derived(6,index),appointment=derived(7,index);s.execute("insert into org.employee_position(id,tenant_id,employee_id,position_id,org_id,is_primary,effective_start_date,status) values ('"+appointment+"','"+TENANT+"','"+employee+"','"+position+"','"+center+"',true,current_date-90,'ACTIVE')");s.execute("insert into iam.user_account(id,tenant_id,login_name,password_hash,status,mfa_level) values ('"+user+"','"+TENANT+"','p014."+login+"','"+hash+"','ACTIVE',0)");s.execute("insert into iam.user_identity(id,tenant_id,user_id,employee_id,identity_type,identity_name,org_id,position_id,is_primary,effective_start_at) values ('"+identity+"','"+TENANT+"','"+user+"','"+employee+"','EMPLOYEE','P014 "+login+"','"+center+"','"+position+"',true,now()-interval '1 day')");s.execute("insert into iam.role(id,tenant_id,role_code,role_name,role_type,data_scope_code,enabled) values ('"+role+"','"+TENANT+"','P014_"+login.toUpperCase()+"','P014 "+login+"','PLATFORM','P014_"+scope+"',true)");s.execute("insert into iam.role_permission(tenant_id,role_id,permission_id) select '"+TENANT+"','"+role+"',id from iam.permission where tenant_id='"+TENANT+"' and permission_code in ('platform.session.read','platform.session.logout','"+permissions.replace(",","','")+"') and not is_deleted");s.execute("insert into iam.user_role(tenant_id,user_id,identity_id,role_id,effective_start_at,grant_source) values ('"+TENANT+"','"+user+"','"+identity+"','"+role+"',now()-interval '1 day','TEST_ONLY')");}
    private static JdbcTemplate jdbc(String database,String username,String password){DriverManagerDataSource ds=new DriverManagerDataSource();ds.setDriverClassName("org.postgresql.Driver");ds.setUrl(url(database));ds.setUsername(username);ds.setPassword(password);return new JdbcTemplate(ds);}private static UUID derived(int group,int index){return id("%d0000000-0000-0000-0000-%012d".formatted(group,3514+index));}private static UUID id(String value){return UUID.fromString(value);}private static String shortId(){return UUID.randomUUID().toString().replace("-","").substring(0,16);}private static String url(String database){String original=POSTGRES.getJdbcUrl();int query=original.indexOf('?');String suffix=query<0?"":original.substring(query),base=query<0?original:original.substring(0,query);return base.substring(0,base.lastIndexOf('/')+1)+database+suffix;}private static Path root(){Path p=Path.of("").toAbsolutePath();while(p!=null){if(Files.exists(p.resolve("AGENT.md")))return p;p=p.getParent();}throw new IllegalStateException("repository root not found");}
}
