package cn.shangjingu.platform.api;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Map;
import java.util.UUID;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

@SpringBootTest(classes=ApiApplication.class)
@AutoConfigureMockMvc
class Phase11P012IntegrationTest {
    private static final UUID TENANT=id("00000000-0000-0000-0000-000000002012"),CENTER_A=id("10000000-0000-0000-0000-000000003412"),CENTER_B=id("10000000-0000-0000-0000-000000003413"),OLD_POSITION=id("20000000-0000-0000-0000-000000003412"),NEW_POSITION=id("20000000-0000-0000-0000-000000003413"),OUT_POSITION=id("20000000-0000-0000-0000-000000003414"),OWNER=id("30000000-0000-0000-0000-000000003412"),MANAGER=id("30000000-0000-0000-0000-000000003413"),ASSESSOR=id("30000000-0000-0000-0000-000000003414"),REVIEWER=id("30000000-0000-0000-0000-000000003415"),APPROVER=id("30000000-0000-0000-0000-000000003416"),APPOINTER=id("30000000-0000-0000-0000-000000003417"),TECH=id("30000000-0000-0000-0000-000000003418"),OUTSIDER=id("30000000-0000-0000-0000-000000003419"),OLD_APPOINTMENT=derived(7,0);private static final String PASSWORD="P012-Live-Test-9q!",API_PASSWORD="p012_api_"+shortId(),AUDIT_PASSWORD="p012_audit_"+shortId();private static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:16.14-alpine3.24").withDatabaseName("postgres").withUsername("postgres").withPassword("bootstrap-"+shortId());private static final GenericContainer<?> REDIS=new GenericContainer<>(DockerImageName.parse("redis:7.4-alpine")).withExposedPorts(6379);
    static{POSTGRES.start();REDIS.start();try{prepare();}catch(Exception e){POSTGRES.stop();REDIS.stop();throw new ExceptionInInitializerError(e);}}
    @Autowired MockMvc mvc;@Autowired ObjectMapper mapper;
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->url("sjg_oms"));r.add("spring.datasource.username",()->"sjg_api_runtime");r.add("spring.datasource.password",()->API_PASSWORD);r.add("spring.data.redis.host",REDIS::getHost);r.add("spring.data.redis.port",()->REDIS.getMappedPort(6379));r.add("sjg.audit.datasource.url",()->url("sjg_audit"));r.add("sjg.audit.datasource.username",()->"sjg_audit_writer");r.add("sjg.audit.datasource.password",()->AUDIT_PASSWORD);}
    @AfterAll static void stop(){REDIS.stop();POSTGRES.stop();}
    @Test void realHttpLifecycleKeepsApprovalNonEffectiveThenAtomicallyChangesPrimaryAppointment()throws Exception{
        String owner=login("owner"),manager=login("manager"),assessor=login("assessor"),reviewer=login("reviewer"),approver=login("approver"),appointer=login("appointer"),tech=login("tech"),outsider=login("outsider");
        ObjectNode create=mapper.createObjectNode().put("businessDate",LocalDate.now().toString()).put("subject","2026 promotion appointment request").put("reason","Published vacancy and development evidence").put("ownerEmployeeId",OWNER.toString()).put("employmentType","FULL_TIME").put("headcountNo","HC-2026-012").put("periodOrCourseNo","PROMOTION-2026-H2").put("targetPositionCode","P012_NEW").put("plannedEffectiveDate",LocalDate.now().plusDays(30).toString()).set("evidence",evidence("source application package"));
        mvc.perform(post("/api/v1/processes/P012/promotion-requests").contentType(MediaType.APPLICATION_JSON).content(create.toString()).header("Idempotency-Key","unauth")).andExpect(status().isUnauthorized());
        JsonNode current=json(mvc.perform(post("/api/v1/processes/P012/promotion-requests").header("Authorization",bearer(manager)).header("Idempotency-Key","create-nomination").contentType(MediaType.APPLICATION_JSON).content(create.toString())).andExpect(status().isOk()).andReturn());String requestId=current.path("id").asText();assertEquals("S01",current.path("currentNodeCode").asText());assertEquals(requestId,json(mvc.perform(post("/api/v1/processes/P012/promotion-requests").header("Authorization",bearer(manager)).header("Idempotency-Key","create-nomination").contentType(MediaType.APPLICATION_JSON).content(create.toString())).andExpect(status().isOk()).andReturn()).path("id").asText());
        assertEquals(0,json(mvc.perform(get("/api/v1/processes/P012/promotion-requests").header("Authorization",bearer(outsider))).andExpect(status().isOk()).andReturn()).size());mvc.perform(get("/api/v1/processes/P012/promotion-requests/"+requestId).header("Authorization",bearer(outsider))).andExpect(status().isForbidden());JsonNode masked=json(mvc.perform(get("/api/v1/processes/P012/promotion-requests/"+requestId).header("Authorization",bearer(tech))).andExpect(status().isOk()).andReturn());assertTrue(masked.path("reason").isNull());assertTrue(masked.path("personName").isNull());assertTrue(masked.path("personNo").isNull());assertTrue(masked.path("score1000").isNull());assertTrue(masked.path("events").isArray()&&masked.path("events").isEmpty());assertTrue(masked.path("executions").isArray()&&masked.path("executions").isEmpty());
        mvc.perform(post(actionUrl(requestId,"SUBMIT")).header("Authorization",bearer(manager)).header("Idempotency-Key","stale").contentType(MediaType.APPLICATION_JSON).content(action(0).toString())).andExpect(status().isConflict());current=act(manager,requestId,"SUBMIT",1,action(1),"submit-nomination");mvc.perform(post(actionUrl(requestId,"CHECK_ELIGIBILITY")).header("Authorization",bearer(manager)).header("Idempotency-Key","frozen").contentType(MediaType.APPLICATION_JSON).content(action(2).put("eligibilityConfirmed",true).put("freezeClear",false).toString())).andExpect(status().isConflict());current=act(manager,requestId,"CHECK_ELIGIBILITY",2,action(2).put("eligibilityConfirmed",true).put("freezeClear",true),"eligibility");mvc.perform(post(actionUrl(requestId,"RECORD_ASSESSMENT")).header("Authorization",bearer(assessor)).header("Idempotency-Key","score-overflow").contentType(MediaType.APPLICATION_JSON).content(action(3).put("score1000",1001).toString())).andExpect(status().isConflict());current=act(assessor,requestId,"RECORD_ASSESSMENT",3,action(3).put("score1000",912),"assessment");current=act(manager,requestId,"VERIFY_VACANCY_BUDGET",4,action(4).put("vacancyConfirmed",true).put("budgetVerificationReference","BUDGET-AUTH-2026-012"),"vacancy-budget");mvc.perform(post(actionUrl(requestId,"COMPLETE_REVIEW")).header("Authorization",bearer(assessor)).header("Idempotency-Key","self-review").contentType(MediaType.APPLICATION_JSON).content(action(5).put("reviewPassed",true).toString())).andExpect(status().isConflict());current=act(reviewer,requestId,"COMPLETE_REVIEW",5,action(5).put("reviewPassed",true),"review");mvc.perform(post(actionUrl(requestId,"APPROVE")).header("Authorization",bearer(reviewer)).header("Idempotency-Key","reviewer-approve").contentType(MediaType.APPLICATION_JSON).content(action(6).put("approved",true).toString())).andExpect(status().isForbidden());current=act(approver,requestId,"APPROVE",6,action(6).put("approved",true),"approve");
        JdbcTemplate oms=jdbc("sjg_oms",POSTGRES.getUsername(),POSTGRES.getPassword());assertEquals(OLD_APPOINTMENT,oms.queryForObject("select id from org.employee_position where tenant_id=? and employee_id=? and is_primary and status='ACTIVE'",UUID.class,TENANT,OWNER));assertEquals(OLD_POSITION,oms.queryForObject("select primary_position_id from org.employee where tenant_id=? and id=?",UUID.class,TENANT,OWNER));assertEquals(0,oms.queryForObject("select count(*) from hr.promotion_appointment_execution where tenant_id=? and request_id=?",Integer.class,TENANT,UUID.fromString(requestId)));
        current=act(manager,requestId,"COMPLETE_NOTICE",7,action(7),"notice");mvc.perform(post(actionUrl(requestId,"RECORD_APPOINTMENT")).header("Authorization",bearer(appointer)).header("Idempotency-Key","missing-salary-authority").contentType(MediaType.APPLICATION_JSON).content(action(8).put("actualEffectiveDate",LocalDate.now().plusDays(30).toString()).put("externalReference","APPOINTMENT-2026-012").toString())).andExpect(status().isConflict());current=act(appointer,requestId,"RECORD_APPOINTMENT",8,action(8).put("actualEffectiveDate",LocalDate.now().plusDays(30).toString()).put("salaryConfirmationReference","SALARY-AUTHORITY-2026-012").put("externalReference","APPOINTMENT-2026-012"),"appointment-receipt");mvc.perform(post(actionUrl(requestId,"CONFIRM_APPOINTMENT")).header("Authorization",bearer(appointer)).header("Idempotency-Key","not-owner-confirm").contentType(MediaType.APPLICATION_JSON).content(action(9).toString())).andExpect(status().isConflict());current=act(owner,requestId,"CONFIRM_APPOINTMENT",9,action(9),"owner-confirm");current=act(reviewer,requestId,"COMPLETE_PROBATION",10,action(10).put("probationResult","PASS"),"probation-pass");LocalDate effective=LocalDate.now().plusDays(30);current=act(appointer,requestId,"MAKE_EFFECTIVE",11,action(11).put("actualEffectiveDate",effective.toString()).put("externalReference","EFFECTIVE-2026-012"),"effective");assertEquals("END",current.path("currentNodeCode").asText());UUID newAppointment=oms.queryForObject("select id from org.employee_position where tenant_id=? and employee_id=? and is_primary and status='ACTIVE'",UUID.class,TENANT,OWNER);assertTrue(!OLD_APPOINTMENT.equals(newAppointment));assertEquals(NEW_POSITION,oms.queryForObject("select position_id from org.employee_position where id=?",UUID.class,newAppointment));assertEquals(NEW_POSITION,oms.queryForObject("select primary_position_id from org.employee where tenant_id=? and id=?",UUID.class,TENANT,OWNER));assertEquals(effective.minusDays(1),oms.queryForObject("select effective_end_date from org.employee_position where id=?",LocalDate.class,OLD_APPOINTMENT));assertEquals(1,oms.queryForObject("select count(*) from hr.promotion_appointment_execution where tenant_id=? and request_id=? and execution_type='EFFECTIVE'",Integer.class,TENANT,UUID.fromString(requestId)));assertTrue(jdbc("sjg_audit",POSTGRES.getUsername(),POSTGRES.getPassword()).queryForObject("select count(*) from audit.operation_log where tenant_id=? and resource_id=? and action like 'P012_%'",Integer.class,TENANT,UUID.fromString(requestId))>=15);
    }
    private JsonNode act(String token,String id,String code,int version,ObjectNode body,String key)throws Exception{assertEquals(version,body.path("expectedVersion").asInt());return json(mvc.perform(post(actionUrl(id,code)).header("Authorization",bearer(token)).header("Idempotency-Key",key).contentType(MediaType.APPLICATION_JSON).content(body.toString())).andExpect(status().isOk()).andReturn());}private ObjectNode action(int version){return mapper.createObjectNode().put("expectedVersion",version).putNull("score1000").putNull("eligibilityConfirmed").putNull("freezeClear").putNull("vacancyConfirmed").putNull("budgetVerificationReference").putNull("reviewPassed").putNull("approved").putNull("salaryConfirmationReference").putNull("externalReference").putNull("probationResult").putNull("actualEffectiveDate").put("resultSummary","P012 source fact accepted").set("evidence",evidence("immutable "+version));}private ObjectNode evidence(String note){return mapper.createObjectNode().put("note",note).put("recordedAt",Instant.now().toString());}private String login(String name)throws Exception{return json(mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content(mapper.createObjectNode().put("tenantCode","PHASE11_P012").put("loginName","p012."+name).put("password",PASSWORD).toString())).andExpect(status().isOk()).andReturn()).path("accessToken").asText();}private JsonNode json(MvcResult result)throws Exception{return mapper.readTree(result.getResponse().getContentAsByteArray());}private static String bearer(String token){return"Bearer "+token;}private static String actionUrl(String id,String action){return"/api/v1/processes/P012/promotion-requests/"+id+"/actions/"+action;}
    private static void prepare()throws Exception{Path root=root();Flyway.configure().dataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/cluster")).cleanDisabled(true).load().migrate();try(Connection c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword());Statement s=c.createStatement()){s.execute("alter role sjg_api_runtime password '"+API_PASSWORD+"'");s.execute("alter role sjg_audit_writer password '"+AUDIT_PASSWORD+"'");s.execute("create database sjg_oms");s.execute("create database sjg_audit");}Flyway.configure().dataSource(url("sjg_oms"),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/oms"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/oms")).placeholders(Map.of("sjg_tenant_id",TENANT.toString(),"sjg_tenant_code","PHASE11_P012","sjg_tenant_name","P012 Integration Tenant")).cleanDisabled(true).load().migrate();Flyway.configure().dataSource(url("sjg_audit"),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/audit"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/audit")).cleanDisabled(true).load().migrate();seed();}
    private static void seed()throws Exception{String hash=new BCryptPasswordEncoder(12).encode(PASSWORD);try(Connection c=DriverManager.getConnection(url("sjg_oms"),POSTGRES.getUsername(),POSTGRES.getPassword());Statement s=c.createStatement()){s.execute("insert into org.organization(id,tenant_id,org_code,org_name,org_type,path,status) values ('"+CENTER_A+"','"+TENANT+"','P012_A','P012 Center A','CENTER','p012_a'::ltree,'ACTIVE'),('"+CENTER_B+"','"+TENANT+"','P012_B','P012 Center B','CENTER','p012_b'::ltree,'ACTIVE')");s.execute("insert into org.position(id,tenant_id,position_code,position_name,org_id,status) values ('"+OLD_POSITION+"','"+TENANT+"','P012_OLD','P012 Old Position','"+CENTER_A+"','ACTIVE'),('"+NEW_POSITION+"','"+TENANT+"','P012_NEW','P012 New Position','"+CENTER_A+"','ACTIVE'),('"+OUT_POSITION+"','"+TENANT+"','P012_OUT','P012 Outside Position','"+CENTER_B+"','ACTIVE')");UUID[] actors={OWNER,MANAGER,ASSESSOR,REVIEWER,APPROVER,APPOINTER,TECH,OUTSIDER};for(int i=0;i<actors.length;i++){UUID center=i==7?CENTER_B:CENTER_A,position=i==7?OUT_POSITION:OLD_POSITION;s.execute("insert into org.employee(id,tenant_id,employee_no,person_name,employment_status,hire_date,primary_org_id,primary_position_id) values ('"+actors[i]+"','"+TENANT+"','P012-E00"+(i+1)+"','P012 Actor "+i+"','ACTIVE',current_date-90,'"+center+"','"+position+"')");}s.execute("insert into iam.data_scope_rule(tenant_id,scope_code,scope_name,rule_expr,enabled) values ('"+TENANT+"','P012_SELF','P012 Self','{\"scope\":\"SELF\"}'::jsonb,true),('"+TENANT+"','P012_CENTER','P012 Center','{\"scope\":\"CENTER\"}'::jsonb,true)");s.execute("insert into iam.permission(id,tenant_id,permission_code,permission_name,resource_type,action_code,risk_level) values (gen_random_uuid(),'"+TENANT+"','platform.session.read','Session read','SESSION','READ','NORMAL'),(gen_random_uuid(),'"+TENANT+"','platform.session.logout','Session logout','SESSION','LOGOUT','NORMAL')");String[][] roles={{"owner","SELF","p012.promotion.read"},{"manager","CENTER","p012.promotion.read,p012.promotion.manage"},{"assessor","CENTER","p012.promotion.read,p012.promotion.review"},{"reviewer","CENTER","p012.promotion.read,p012.promotion.review"},{"approver","CENTER","p012.promotion.read,p012.promotion.approve"},{"appointer","CENTER","p012.promotion.read,p012.promotion.appoint"},{"tech","CENTER","p012.promotion.monitor"},{"outsider","CENTER","p012.promotion.read"}};for(int i=0;i<roles.length;i++)seedActor(s,i,actors[i],roles[i][0],roles[i][1],roles[i][2],hash,i==7?CENTER_B:CENTER_A,i==7?OUT_POSITION:OLD_POSITION);}}
    private static void seedActor(Statement s,int index,UUID employee,String login,String scope,String permissions,String hash,UUID center,UUID position)throws Exception{UUID user=derived(4,index),identity=derived(5,index),role=derived(6,index),appointment=derived(7,index);s.execute("insert into org.employee_position(id,tenant_id,employee_id,position_id,org_id,is_primary,effective_start_date,status) values ('"+appointment+"','"+TENANT+"','"+employee+"','"+position+"','"+center+"',true,current_date-90,'ACTIVE')");s.execute("insert into iam.user_account(id,tenant_id,login_name,password_hash,status,mfa_level) values ('"+user+"','"+TENANT+"','p012."+login+"','"+hash+"','ACTIVE',0)");s.execute("insert into iam.user_identity(id,tenant_id,user_id,employee_id,identity_type,identity_name,org_id,position_id,is_primary,effective_start_at) values ('"+identity+"','"+TENANT+"','"+user+"','"+employee+"','EMPLOYEE','P012 "+login+"','"+center+"','"+position+"',true,now()-interval '1 day')");s.execute("insert into iam.role(id,tenant_id,role_code,role_name,role_type,data_scope_code,enabled) values ('"+role+"','"+TENANT+"','P012_"+login.toUpperCase()+"','P012 "+login+"','PLATFORM','P012_"+scope+"',true)");s.execute("insert into iam.role_permission(tenant_id,role_id,permission_id) select '"+TENANT+"','"+role+"',id from iam.permission where tenant_id='"+TENANT+"' and permission_code in ('platform.session.read','platform.session.logout','"+permissions.replace(",","','")+"') and not is_deleted");s.execute("insert into iam.user_role(tenant_id,user_id,identity_id,role_id,effective_start_at,grant_source) values ('"+TENANT+"','"+user+"','"+identity+"','"+role+"',now()-interval '1 day','TEST_ONLY')");}
    private static JdbcTemplate jdbc(String database,String username,String password){DriverManagerDataSource ds=new DriverManagerDataSource();ds.setDriverClassName("org.postgresql.Driver");ds.setUrl(url(database));ds.setUsername(username);ds.setPassword(password);return new JdbcTemplate(ds);}private static UUID derived(int group,int index){return id("%d0000000-0000-0000-0000-%012d".formatted(group,3412+index));}private static UUID id(String value){return UUID.fromString(value);}private static String shortId(){return UUID.randomUUID().toString().replace("-","").substring(0,16);}private static String url(String database){String original=POSTGRES.getJdbcUrl();int query=original.indexOf('?');String suffix=query<0?"":original.substring(query),base=query<0?original:original.substring(0,query);return base.substring(0,base.lastIndexOf('/')+1)+database+suffix;}private static Path root(){Path p=Path.of("").toAbsolutePath();while(p!=null){if(Files.exists(p.resolve("AGENT.md")))return p;p=p.getParent();}throw new IllegalStateException("repository root not found");}
}
