<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { usePortalSessionStore } from '../../session'
import type { PortalDefinition } from '../portal-config'
type Mode='employee'|'center'
interface RecordView{id:string;tenantId:string;businessNo:string;workflowInstanceId:string|null;workflowInstanceNo:string|null;currentNodeCode:string|null;status:string;versionNo:number;subject:string|null;reason:string|null;ownerCenterId:string;ownerEmployeeId:string|null;targetEmployeeId:string|null;replacementEmployeeId:string|null;changeAction:string|null;changeReason:string|null;templateCode:string|null;periodOrCourseNo:string|null;startAt:string;endAt:string;durationHours:number;qualificationCheckedAt:string|null;continuousWorkHours:number|null;conflictCheckedAt:string|null;publishedAt:string|null;employeeConfirmedAt:string|null;approvedAt:string|null;attendanceLinkedAt:string|null;cateringLinkedAt:string|null;shuttleLinkedAt:string|null;dayClosedAt:string|null;updatedAt:string}
interface Aggregate{record:RecordView}
const props=defineProps<{portal:PortalDefinition;mode:Mode}>(),session=usePortalSessionStore(),rows=ref<Aggregate[]>([]),busy=ref(false),feedback=ref('')
const subject=ref(''),changeReason=ref(''),templateCode=ref(''),period=ref(''),targetEmployee=ref(''),startAt=ref(''),endAt=ref(''),replacement=ref(''),reason=ref('')
const center=computed(()=>props.mode==='center'),orgId=computed(()=>session.session?.orgId??''),employeeId=computed(()=>session.session?.employeeId??'')
const canManage=computed(()=>session.can('p007.schedule.manage')),canChange=computed(()=>session.can('p007.schedule.change')),canReview=computed(()=>session.can('p007.schedule.review'))
function idem(p:string){return `${p}-${crypto.randomUUID()}`}function iso(v:string){const d=new Date(v);if(Number.isNaN(d.getTime()))throw new Error('日期时间无效');return d.toISOString()}
async function run(fn:()=>Promise<void>){busy.value=true;feedback.value='';try{await fn()}catch(e){feedback.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
async function load(){rows.value=await session.request<Aggregate[]>('/api/v1/processes/P007/schedules')}
function create(){return run(async()=>{const target=center.value?targetEmployee.value.trim():employeeId.value;if(!orgId.value||!target)throw new Error('缺少员工/中心身份');const body={subject:subject.value.trim(),reason:null,ownerCenterId:orgId.value,targetEmployeeId:target,changeAction:center.value?'SCHEDULE':'SHIFT_CHANGE',changeReason:changeReason.value.trim(),templateCode:templateCode.value.trim()||null,periodOrCourseNo:period.value.trim(),startAt:iso(startAt.value),endAt:iso(endAt.value)};await session.request('/api/v1/processes/P007/shift-changes',{method:'POST',idempotencyKey:idem('p007-create'),body});feedback.value='排班/换班需求已进入班次模板匹配';await load()})}
function act(a:Aggregate,action:string){return run(async()=>{const body={expectedVersion:a.record.versionNo,replacementEmployeeId:action==='SUBMIT_SHIFT_CHANGE'?(replacement.value.trim()||null):null,reason:reason.value.trim()||null};await session.request(`/api/v1/processes/P007/shift-changes/${a.record.id}/actions/${action}`,{method:'POST',idempotencyKey:idem(`p007-${action.toLowerCase()}`),body});feedback.value=`${a.record.businessNo} 已执行 ${action}`;await load()})}
const managerActions:Record<string,{code:string;label:string}[]>={S02:[{code:'MATCH_TEMPLATE',label:'确认班次模板'}],S03:[{code:'VALIDATE_SHIFT',label:'执行资格/连续工时/冲突校验'}],S04:[{code:'PUBLISH_SCHEDULE',label:'发布排班'}],S07:[{code:'APPROVE_CHANGE',label:'批准变更'},{code:'RETURN_CHANGE',label:'退回变更'}],S08:[{code:'LINK_DEPENDENCIES',label:'写入考勤/餐饮/班车联动'}],S09:[{code:'CLOSE_DAY',label:'日结归档'}]}
function stamp(v:string|null){return v?new Date(v).toLocaleString():'-'}
onMounted(()=>void run(load))
</script>
<template><main class="phase09-page" data-testid="p007-page"><header><p class="phase09-kicker">PHASE-10 · P007</p><h1>{{center?'排班与班次调整管理':'我的排班与换班'}}</h1><p>排班、资格校验、换班审批和联动均由服务端状态机与 PostgreSQL 事实驱动。</p></header>
<section class="phase09-card"><h2>{{center?'录入排班需求':'发起换班需求'}}</h2><div class="phase09-grid"><label>主题<input v-model="subject"></label><label v-if="center">目标员工 UUID<input v-model="targetEmployee"></label><label>班次模板<input v-model="templateCode"></label><label>周期编号<input v-model="period"></label><label>开始<input type="datetime-local" v-model="startAt"></label><label>结束<input type="datetime-local" v-model="endAt"></label></div><label>变更原因<textarea v-model="changeReason"></textarea></label><button :disabled="busy||(center?!canManage:!canChange)" @click="create">提交排班/换班需求</button></section>
<p v-if="feedback" class="phase09-feedback">{{feedback}}</p>
<article v-for="a in rows" :key="a.record.id" class="phase09-card" :data-shift-id="a.record.id"><h2>{{a.record.businessNo}} · {{a.record.subject||'排班运行元数据'}}</h2><p>{{a.record.currentNodeCode}} / {{a.record.status}} · version {{a.record.versionNo}}</p><p>{{stamp(a.record.startAt)}} → {{stamp(a.record.endAt)}} · {{a.record.durationHours}} 小时</p><p v-if="a.record.qualificationCheckedAt">资格/冲突校验：{{stamp(a.record.qualificationCheckedAt)}} / {{stamp(a.record.conflictCheckedAt)}}</p><p v-if="a.record.approvedAt">变更批准：{{stamp(a.record.approvedAt)}}</p><p v-if="a.record.attendanceLinkedAt">联动：考勤 {{stamp(a.record.attendanceLinkedAt)}} · 餐饮 {{stamp(a.record.cateringLinkedAt)}} · 班车 {{stamp(a.record.shuttleLinkedAt)}}</p>
<div v-if="!center&&a.record.currentNodeCode==='S05'&&canChange"><button :disabled="busy" @click="act(a,'CONFIRM_SCHEDULE')">确认排班</button></div><div v-if="!center&&a.record.currentNodeCode==='S06'&&canChange"><label>替班员工 UUID（可选）<input v-model="replacement"></label><button :disabled="busy" @click="act(a,'SUBMIT_SHIFT_CHANGE')">提交换班/替班申请</button></div>
<div v-if="center"><label>处理说明<input v-model="reason"></label><button v-for="x in managerActions[a.record.currentNodeCode||'']||[]" :key="x.code" :disabled="busy||((x.code==='APPROVE_CHANGE'||x.code==='RETURN_CHANGE')?!canReview:!canManage)" @click="act(a,x.code)">{{x.label}}</button></div><button :disabled="busy" @click="load">刷新</button></article></main></template>
