<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { usePortalSessionStore } from '../../session'
import type { PortalDefinition } from '../portal-config'
type Process='P008'|'P009'|'P010';type Mode='employee'|'center'
interface RecordView{id:string;businessNo:string;currentNodeCode:string|null;status:string;versionNo:number;subject?:string|null;attendanceType?:string|null;startAt?:string|null;endAt?:string|null;durationHours?:number|null;quotaAccountId?:string|null;quotaAmount?:number|null;decision?:string|null;actualDurationHours?:number|null;supervisorDecision?:string|null;compensationPlan?:string|null;completionRate?:number|null;score1000?:number|null;practicalResult?:string|null;courseVersionId?:string|null;contentVersion?:string|null;periodOrCourseNo?:string|null;qualificationEffectiveDate?:string|null;qualificationExpireDate?:string|null;permissionLinkedAt?:string|null}
interface Aggregate{record:RecordView;evidence?:unknown[]}
const props=defineProps<{portal:PortalDefinition;process:Process;mode:Mode}>(),session=usePortalSessionStore(),rows=ref<Aggregate[]>([]),ledger=ref<unknown[]>([]),busy=ref(false),feedback=ref('')
const subject=ref(''),reason=ref(''),attendanceType=ref(''),startAt=ref(''),endAt=ref(''),quotaAccount=ref(''),quotaAmount=ref(''),handover=ref(''),knownImpact=ref(''),emergency=ref(false)
const actualStart=ref(''),actualEnd=ref(''),actualSummary=ref(''),resultSummary=ref(''),adjustment=ref(''),compPlan=ref('WAGE'),wage=ref('0'),timeOff=ref(''),payrollRef=ref('')
const progress=ref('100'),score=ref(''),practical=ref('通过'),effectiveDate=ref(''),expireDate=ref('')
const center=computed(()=>props.mode==='center'),orgId=computed(()=>session.session?.orgId??'')
function idem(s:string){return `${props.process}-${s}-${globalThis.crypto.randomUUID()}`}function iso(v:string){const d=new Date(v);if(Number.isNaN(d.getTime()))throw new Error('日期时间无效');return d.toISOString()}
async function run(fn:()=>Promise<void>){busy.value=true;feedback.value='';try{await fn()}catch(e){feedback.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
function base(){if(props.process==='P008')return'/api/v1/processes/P008/leaves';if(props.process==='P009')return'/api/v1/processes/P009/overtime-requests';return'/api/v1/processes/P010/assignments'}
async function load(){rows.value=await session.request<Aggregate[]>(base());if(props.process==='P008')ledger.value=await session.request<unknown[]>('/api/v1/processes/P008/quota-ledger')}
function create(){return run(async()=>{if(!orgId.value)throw new Error('缺少中心身份');if(props.process==='P008'){await session.request(base(),{method:'POST',idempotencyKey:idem('create'),body:{subject:subject.value.trim(),reason:reason.value.trim()||null,ownerCenterId:orgId.value,attendanceType:attendanceType.value.trim(),quotaAccountId:quotaAccount.value.trim(),quotaAmount:Number(quotaAmount.value),startAt:iso(startAt.value),endAt:iso(endAt.value),handoverAgentId:handover.value.trim()||null,knownImpact:knownImpact.value.trim()||null}})}else if(props.process==='P009'){await session.request(base(),{method:'POST',idempotencyKey:idem('create'),body:{subject:subject.value.trim(),reason:reason.value.trim()||null,ownerCenterId:orgId.value,attendanceType:attendanceType.value.trim(),startAt:iso(startAt.value),endAt:iso(endAt.value),emergencyFact:emergency.value}})}feedback.value='已提交并进入服务端状态机';await load()})}
function bodyFor(a:Aggregate,action:string){const common:{expectedVersion:number;reason:string|null;actualAt?:string;adjustmentAmount?:number;actualStartAt?:string;actualEndAt?:string;attendanceSummary?:string;resultSummary?:string;compensationPlan?:string;wageAmount?:number;quotaAccountId?:string;timeOffHours?:number;payrollReference?:string;note?:string;effectiveDate?:string;expireDate?:string}={expectedVersion:a.record.versionNo,reason:reason.value.trim()||null};if(props.process==='P008'){if(actualStart.value)common.actualAt=iso(actualStart.value);if(adjustment.value)common.adjustmentAmount=Number(adjustment.value)}if(props.process==='P009'){if(actualStart.value)common.actualStartAt=iso(actualStart.value);if(actualEnd.value)common.actualEndAt=iso(actualEnd.value);common.attendanceSummary=actualSummary.value.trim()||undefined;common.resultSummary=resultSummary.value.trim()||undefined;common.compensationPlan=compPlan.value;common.wageAmount=Number(wage.value||0);common.quotaAccountId=quotaAccount.value.trim()||undefined;common.timeOffHours=timeOff.value?Number(timeOff.value):undefined;common.payrollReference=payrollRef.value.trim()||undefined}if(props.process==='P010'){common.note=reason.value.trim()||undefined;common.effectiveDate=effectiveDate.value||undefined;common.expireDate=expireDate.value||undefined}return common}
function act(a:Aggregate,action:string){return run(async()=>{await session.request(`${base()}/${a.record.id}/actions/${action}`,{method:'POST',idempotencyKey:idem(action.toLowerCase()),body:bodyFor(a,action)});feedback.value=`${a.record.businessNo} 已执行 ${action}`;await load()})}
function p010Employee(a:Aggregate,kind:'progress'|'exam'|'practical'){return run(async()=>{let body:object;if(kind==='progress')body={completionRate:Number(progress.value),note:reason.value.trim()||null};else if(kind==='exam')body={score1000:Number(score.value),note:reason.value.trim()||null};else body={result:practical.value,note:reason.value.trim()||null};await session.request(`${base()}/${a.record.id}/${kind==='progress'?'learning-progress':kind}`,{method:'POST',idempotencyKey:idem(kind),body});await load()})}
const actions=computed<Record<string,{code:string;label:string}[]>>(()=>props.process==='P008'?{S02:[{code:'RESERVE_QUOTA',label:'预占额度'}],S03:[{code:'CONFIRM_HANDOVER',label:'确认交接'}],S04:[{code:'APPROVE_LEAVE',label:'批准'},{code:'REJECT_LEAVE',label:'驳回'}],S05:[{code:'COMMIT_QUOTA',label:'转扣减'},{code:'RELEASE_QUOTA',label:'释放预占'}],S06:[{code:'MARK_ATTENDANCE',label:'标记考勤'}],S07:[{code:'START_LEAVE',label:'确认实际休假'}],S08:[{code:'RETURN_TO_WORK',label:'销假/返岗'},{code:'CHANGE_LEAVE',label:'变更返岗'}],S09:[{code:'ADJUST_QUOTA',label:'差额调整'}],S10:[{code:'CLOSE_DAY',label:'日结归档'}]}:props.process==='P009'?{S02:[{code:'VALIDATE_NECESSITY',label:'必要性校验'}],S03:[{code:'APPROVE_OVERTIME',label:'批准加班'},{code:'REJECT_OVERTIME',label:'驳回'}],S04:[{code:'RECORD_ACTUAL_FACT',label:'登记实际劳动'}],S05:[{code:'ACCEPT_RESULT',label:'成果验收'}],S06:[{code:'HR_REVIEW',label:'人事复核'}],S07:[{code:'SET_COMPENSATION_PLAN',label:'确定工资/调休方案'}],S08:[{code:'ACK_PAYROLL_RECEIPT',label:'确认薪酬回执'}],S09:[{code:'ARCHIVE',label:'归档'}]}:{S01:[{code:'PUBLISH_CONTENT',label:'发布课程/制度版本'}],S02:[{code:'ASSIGN_BY_RISK',label:'按岗位风险指派'}],S06:[{code:'CERTIFY',label:'专业认证通过'},{code:'RETURN_FOR_TRAINING',label:'退回补训'}],S07:[{code:'ACTIVATE_QUALIFICATION',label:'资格生效'}],S08:[{code:'LINK_PERMISSIONS',label:'服务端联动岗位权限'}],S09:[{code:'COMPLETE_RETRAINING_CHECK',label:'完成复训/复证检查'}],S10:[{code:'ARCHIVE',label:'归档'}]})
onMounted(()=>void run(load))
</script>
<template><main class="phase09-page" :data-testid="`${process.toLowerCase()}-page`"><header><p class="phase09-kicker">PHASE-10 · {{process}}</p><h1>{{process==='P008'?'请假与考勤':process==='P009'?'加班与调休':'员工学习、考试与资格'}}</h1><p>页面仅提交业务动作；状态、权限、额度、成绩与资格事实均由服务端/PostgreSQL 决定。</p></header>
<section v-if="!center&&process!=='P010'" class="phase09-card"><h2>发起申请</h2><div class="phase09-grid"><label>主题<input v-model="subject"></label><label>类型<input v-model="attendanceType"></label><label>开始<input type="datetime-local" v-model="startAt"></label><label>结束<input type="datetime-local" v-model="endAt"></label><template v-if="process==='P008'"><label>额度账户<input v-model="quotaAccount"></label><label>额度数量<input v-model="quotaAmount" type="number" step="0.01"></label><label>交接代理人<input v-model="handover"></label><label>已知影响<input v-model="knownImpact"></label></template><label v-if="process==='P009'"><input v-model="emergency" type="checkbox"> 紧急事实登记</label></div><label>原因<textarea v-model="reason"></textarea></label><button :disabled="busy" @click="create">提交</button></section>
<section class="phase09-card"><label>处理/证据说明<input v-model="reason"></label><div v-if="process==='P008'" class="phase09-grid"><label>实际时点<input type="datetime-local" v-model="actualStart"></label><label>差额调整<input type="number" step="0.01" v-model="adjustment"></label></div><div v-if="process==='P009'" class="phase09-grid"><label>实际开始<input type="datetime-local" v-model="actualStart"></label><label>实际结束<input type="datetime-local" v-model="actualEnd"></label><label>考勤事实<input v-model="actualSummary"></label><label>成果验收<input v-model="resultSummary"></label><label>补偿方案<select v-model="compPlan"><option>WAGE</option><option>TIME_OFF</option><option>MIXED</option></select></label><label>工资金额<input type="number" v-model="wage"></label><label>调休账户<input v-model="quotaAccount"></label><label>调休小时<input type="number" v-model="timeOff"></label><label>薪酬回执号<input v-model="payrollRef"></label></div><div v-if="process==='P010'" class="phase09-grid"><label>学习进度 0-100<input type="number" min="0" max="100" v-model="progress"></label><label>考试分 0-1000<input type="number" min="0" max="1000" v-model="score"></label><label>实操结果<select v-model="practical"><option>通过</option><option>补训</option><option>不通过</option><option>不适用</option></select></label><label>资格生效日<input type="date" v-model="effectiveDate"></label><label>资格到期日<input type="date" v-model="expireDate"></label></div></section>
<p v-if="feedback" class="phase09-feedback">{{feedback}}</p><article v-for="a in rows" :key="a.record.id" class="phase09-card"><h2>{{a.record.businessNo}} · {{a.record.subject||'业务事实'}}</h2><p>{{a.record.currentNodeCode}} / {{a.record.status}} · version {{a.record.versionNo}}</p><p v-if="a.record.startAt">{{a.record.startAt}} → {{a.record.endAt}} · {{a.record.durationHours}}h</p><p v-if="process==='P010'">课程 {{a.record.courseVersionId}} · 进度 {{a.record.completionRate??'-'}} · 分数 {{a.record.score1000??'-'}} · 实操 {{a.record.practicalResult??'-'}}</p><template v-if="process==='P010'&&!center"><button v-if="a.record.currentNodeCode==='S03'" :disabled="busy" @click="p010Employee(a,'progress')">提交学习进度</button><button v-if="a.record.currentNodeCode==='S04'" :disabled="busy" @click="p010Employee(a,'exam')">提交考试结果</button><button v-if="a.record.currentNodeCode==='S05'" :disabled="busy" @click="p010Employee(a,'practical')">提交实操结果</button></template><button v-for="x in actions[a.record.currentNodeCode||'']||[]" v-if="center||(process!=='P010'&&['S03','S07','S08','S04'].includes(a.record.currentNodeCode||''))" :key="x.code" :disabled="busy" @click="act(a,x.code)">{{x.label}}</button></article>
<section v-if="process==='P008'" class="phase09-card"><h2>额度流水（只增不改）</h2><pre>{{JSON.stringify(ledger,null,2)}}</pre></section></main></template>
