package cn.shangjingu.platform.reward;

import static cn.shangjingu.platform.reward.RewardCaseService.*;

import cn.shangjingu.platform.core.process.ProcessRejectedException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcRewardCaseRepository implements RewardCaseService.Repository {
    private final JdbcTemplate jdbc;private final ObjectMapper mapper;public JdbcRewardCaseRepository(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
    @Override public Optional<UUID> latestPublishedWorkflowVersion(UUID t,String c){return jdbc.query("select v.id from workflow.wf_version v join workflow.wf_definition d on d.tenant_id=v.tenant_id and d.id=v.definition_id where v.tenant_id=? and d.process_code=? and d.enabled and not d.is_deleted and v.status='PUBLISHED' and not v.is_deleted and (v.effective_at is null or v.effective_at<=now()) order by v.version_no desc limit 1",(r,n)->r.getObject(1,UUID.class),t,c).stream().findFirst();}
    @Override public Optional<FormRef> latestPublishedForm(UUID t,String f,String p,String n){return jdbc.query("select id,version_no from workflow.wf_form_definition where tenant_id=? and form_code=? and process_code=? and node_code=? and enabled and not is_deleted order by version_no desc limit 1",(r,x)->new FormRef(r.getObject(1,UUID.class),r.getInt(2)),t,f,p,n).stream().findFirst();}
    @Override public Optional<Target> target(UUID t,UUID employee){return jdbc.query("""
        select e.id,ui.org_id,ui.user_id,ui.id identity_id from org.employee e join iam.user_identity ui on ui.tenant_id=e.tenant_id and ui.employee_id=e.id and ui.is_primary and not ui.is_deleted and ui.effective_start_at<=now() and (ui.effective_end_at is null or ui.effective_end_at>now()) where e.tenant_id=? and e.id=? and e.employment_status='ACTIVE' and not e.is_deleted order by ui.effective_start_at desc limit 1
        """,(r,n)->new Target(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class),r.getObject(4,UUID.class)),t,employee).stream().findFirst();}
    @Override public List<UUID> permissionCandidates(UUID t,String p,UUID center){return jdbc.query("""
        select distinct ui.employee_id from iam.user_role ur join iam.role r on r.tenant_id=ur.tenant_id and r.id=ur.role_id and r.enabled and not r.is_deleted join iam.role_permission rp on rp.tenant_id=r.tenant_id and rp.role_id=r.id and not rp.is_deleted join iam.permission pm on pm.tenant_id=rp.tenant_id and pm.id=rp.permission_id and not pm.is_deleted join iam.user_identity ui on ui.tenant_id=ur.tenant_id and ui.user_id=ur.user_id and not ui.is_deleted and (ur.identity_id is null or ur.identity_id=ui.id) join org.employee e on e.tenant_id=ui.tenant_id and e.id=ui.employee_id and e.employment_status='ACTIVE' and not e.is_deleted where ur.tenant_id=? and pm.permission_code=? and ui.org_id=? and not ur.is_deleted and ur.effective_start_at<=now() and (ur.effective_end_at is null or ur.effective_end_at>now()) order by ui.employee_id
        """,(r,n)->r.getObject(1,UUID.class),t,p,center);}
    @Override public void insert(RewardCase v,UUID actor){one(jdbc.update("""
        insert into reward.reward_case(id,tenant_id,business_no,status,version_no,created_by,updated_by,source_channel,business_date,subject,reason,priority,risk_level,owner_center_id,owner_employee_id,employee_event_type,fact_occurred_at,fact_summary,impact_level,source_fact_key)
        values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """,v.id(),v.tenantId(),v.businessNo(),v.status(),0,actor,actor,"PORTAL",v.businessDate(),v.subject(),v.reason(),"NORMAL","HIGH",v.ownerCenterId(),v.ownerEmployeeId(),v.employeeEventType(),ts(v.factOccurredAt()),v.factSummary(),v.impactLevel(),v.sourceFactKey()),"insert");}
    @Override public int bindWorkflow(UUID t,UUID id,int v,UUID wf,UUID actor){return jdbc.update("update reward.reward_case set workflow_instance_id=?,version_no=version_no+1,updated_by=? where tenant_id=? and id=? and version_no=? and not is_deleted",wf,actor,t,id,v);}
    @Override public int move(UUID t,UUID id,int v,String status,String result,Instant closed,UUID actor){return jdbc.update("update reward.reward_case set status=?,result_summary=coalesce(cast(? as text),result_summary),closed_at=coalesce(?,closed_at),version_no=version_no+1,updated_by=? where tenant_id=? and id=? and version_no=? and not is_deleted",status,result,ts(closed),actor,t,id,v);}
    @Override public void appendEvent(UUID t,UUID id,String type,JsonNode evidence,UUID actor){lock(t,id,"event");one(jdbc.update("""
        insert into reward.reward_case_event(id,tenant_id,reward_case_id,event_seq,event_type,evidence,actor_employee_id)
        select gen_random_uuid(),?,?,coalesce(max(event_seq),0)+1,?,cast(? as jsonb),? from reward.reward_case_event where tenant_id=? and reward_case_id=?
        """,t,id,type,json(evidence),actor,t,id),"event append");}
    @Override public Optional<UUID> eventActor(UUID t,UUID id,String type){return jdbc.query("select actor_employee_id from reward.reward_case_event where tenant_id=? and reward_case_id=? and event_type=? order by event_seq desc limit 1",(r,n)->r.getObject(1,UUID.class),t,id,type).stream().findFirst();}
    @Override public void setRecommendedLevel(UUID t,UUID id,String level,UUID actor){one(jdbc.update("update reward.reward_case set recommended_reward_level=?,updated_by=? where tenant_id=? and id=? and not is_deleted",level,actor,t,id),"recommendation projection");}
    @Override public void setApprovedLevel(UUID t,UUID id,String level,UUID actor){one(jdbc.update("update reward.reward_case set approved_reward_level=?,updated_by=? where tenant_id=? and id=? and not is_deleted",level,actor,t,id),"approval projection");}
    @Override public void verifySourceUnique(UUID t,UUID id,String sourceFactKey){lock(t,id,"duplicate");Long count=jdbc.queryForObject("select count(*) from reward.reward_case where tenant_id=? and source_fact_key=? and id<>? and not is_deleted",Long.class,t,sourceFactKey,id);if(count!=null&&count>0)throw rejected("source contribution already has an active reward");}
    @Override public void appendImpact(UUID t,UUID id,String type,Long points,BigDecimal amount,String reference,JsonNode evidence,UUID actor){one(jdbc.update("insert into reward.reward_impact_instruction(id,tenant_id,reward_case_id,impact_type,requested_points,approved_amount,authority_reference,evidence,instructed_by) values(gen_random_uuid(),?,?,?,?,?,?,cast(? as jsonb),?)",t,id,type,points,amount,reference,json(evidence),actor),"impact instruction append");if("HONOR_POINTS".equals(type))one(jdbc.update("update reward.reward_case set points_delta=?,updated_by=? where tenant_id=? and id=? and not is_deleted",points,actor,t,id),"points instruction projection");if("BONUS".equals(type))one(jdbc.update("update reward.reward_case set benefit_amount=?,updated_by=? where tenant_id=? and id=? and not is_deleted",amount,actor,t,id),"bonus instruction projection");if("DEVELOPMENT".equals(type))one(jdbc.update("update reward.reward_case set comp_grade_impact=?,updated_by=? where tenant_id=? and id=? and not is_deleted",reference,actor,t,id),"development instruction projection");}
    @Override public long impactCount(UUID t,UUID id){Long count=jdbc.queryForObject("select count(*) from reward.reward_impact_instruction where tenant_id=? and reward_case_id=?",Long.class,t,id);return count==null?0:count;}
    @Override public void appendReceipt(UUID t,UUID id,UUID instruction,String type,String reference,Instant occurredAt,JsonNode evidence,UUID actor){one(jdbc.update("insert into reward.reward_impact_receipt(id,tenant_id,reward_case_id,instruction_id,receipt_type,external_reference,external_occurred_at,evidence,received_by) values(gen_random_uuid(),?,?,?,?,?,?,cast(? as jsonb),?)",t,id,instruction,type,reference,ts(occurredAt),json(evidence),actor),"external receipt append");}
    @Override public boolean allInstructionsReceipted(UUID t,UUID id){Long count=jdbc.queryForObject("select count(*) from reward.reward_impact_instruction i left join reward.reward_impact_receipt r on r.tenant_id=i.tenant_id and r.instruction_id=i.id where i.tenant_id=? and i.reward_case_id=? and r.id is null",Long.class,t,id);return impactCount(t,id)>0&&count!=null&&count==0;}
    @Override public Optional<RewardCase> find(UUID t,UUID id){return jdbc.query(select("where c.tenant_id=? and c.id=? and not c.is_deleted"),(r,n)->map(r),t,id).stream().findFirst();}@Override public List<RewardCase> list(UUID t){return jdbc.query(select("where c.tenant_id=? and not c.is_deleted order by c.created_at desc,c.id desc"),(r,n)->map(r),t);}
    private String select(String suffix){return """
        select c.id,c.tenant_id,c.business_no,c.workflow_instance_id,w.instance_no workflow_instance_no,w.current_node_code,c.status,c.version_no,c.business_date,c.subject,c.reason,c.owner_center_id,c.owner_employee_id,c.source_fact_key,c.employee_event_type,c.fact_occurred_at,c.fact_summary,c.impact_level,c.recommended_reward_level,c.approved_reward_level,c.points_delta,c.benefit_amount,c.comp_grade_impact,c.updated_at from reward.reward_case c left join workflow.wf_instance w on w.tenant_id=c.tenant_id and w.id=c.workflow_instance_id and not w.is_deleted
        """+suffix;}
    private RewardCase map(ResultSet r)throws SQLException{UUID t=r.getObject("tenant_id",UUID.class),id=r.getObject("id",UUID.class);return new RewardCase(id,t,r.getString("business_no"),r.getObject("workflow_instance_id",UUID.class),r.getString("workflow_instance_no"),r.getString("current_node_code"),r.getString("status"),r.getInt("version_no"),date(r,"business_date"),r.getString("subject"),r.getString("reason"),r.getObject("owner_center_id",UUID.class),r.getObject("owner_employee_id",UUID.class),r.getString("source_fact_key"),r.getString("employee_event_type"),instant(r,"fact_occurred_at"),r.getString("fact_summary"),r.getString("impact_level"),r.getString("recommended_reward_level"),r.getString("approved_reward_level"),(Long)r.getObject("points_delta"),r.getBigDecimal("benefit_amount"),r.getString("comp_grade_impact"),events(t,id),impacts(t,id),receipts(t,id),instant(r,"updated_at"));}
    private List<Event> events(UUID t,UUID id){return jdbc.query("select id,event_seq,event_type,evidence,actor_employee_id,created_at from reward.reward_case_event where tenant_id=? and reward_case_id=? order by event_seq,id",(r,n)->new Event(r.getObject(1,UUID.class),r.getInt(2),r.getString(3),read(r.getString(4)),r.getObject(5,UUID.class),instant(r,"created_at")),t,id);}
    private List<ImpactInstruction> impacts(UUID t,UUID id){return jdbc.query("select id,impact_type,requested_points,approved_amount,authority_reference,evidence,instructed_by,instructed_at from reward.reward_impact_instruction where tenant_id=? and reward_case_id=? order by instructed_at,id",(r,n)->new ImpactInstruction(r.getObject(1,UUID.class),r.getString(2),(Long)r.getObject(3),r.getBigDecimal(4),r.getString(5),read(r.getString(6)),r.getObject(7,UUID.class),instant(r,"instructed_at")),t,id);}
    private List<ImpactReceipt> receipts(UUID t,UUID id){return jdbc.query("select id,instruction_id,receipt_type,external_reference,external_occurred_at,evidence,received_by,received_at from reward.reward_impact_receipt where tenant_id=? and reward_case_id=? order by received_at,id",(r,n)->new ImpactReceipt(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getString(3),r.getString(4),instant(r,"external_occurred_at"),read(r.getString(6)),r.getObject(7,UUID.class),instant(r,"received_at")),t,id);}
    private void lock(UUID t,UUID id,String domain){jdbc.query("select pg_advisory_xact_lock(hashtextextended(?,0))",r->{r.next();return null;},t+":"+id+":"+domain);}private String json(JsonNode n){try{return mapper.writeValueAsString(n);}catch(JsonProcessingException e){throw rejected("JSON serialization failed");}}private JsonNode read(String n){try{return n==null?null:mapper.readTree(n);}catch(JsonProcessingException e){throw rejected("persisted JSON invalid");}}private static void one(int n,String action){if(n!=1)throw rejected(action+" failed");}private static Timestamp ts(Instant v){return v==null?null:Timestamp.from(v);}private static LocalDate date(ResultSet r,String f)throws SQLException{var v=r.getDate(f);return v==null?null:v.toLocalDate();}private static Instant instant(ResultSet r,String f)throws SQLException{Object v=r.getObject(f);if(v==null)return null;if(v instanceof OffsetDateTime o)return o.toInstant();if(v instanceof Timestamp x)return x.toInstant();throw new SQLException("unsupported timestamp "+f);}private static ProcessRejectedException rejected(String m){return new ProcessRejectedException("P013 "+m);}
}
