package cn.shangjingu.platform.reward;

import static cn.shangjingu.platform.reward.PointLedgerService.*;

import cn.shangjingu.platform.core.process.ProcessRejectedException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcPointLedgerRepository implements PointLedgerService.Repository {
    private final JdbcTemplate jdbc;private final ObjectMapper mapper;public JdbcPointLedgerRepository(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
    @Override public Optional<UUID> latestPublishedWorkflowVersion(UUID t,String c){return jdbc.query("select v.id from workflow.wf_version v join workflow.wf_definition d on d.tenant_id=v.tenant_id and d.id=v.definition_id where v.tenant_id=? and d.process_code=? and d.enabled and not d.is_deleted and v.status='PUBLISHED' and not v.is_deleted and (v.effective_at is null or v.effective_at<=now()) order by v.version_no desc limit 1",(r,n)->r.getObject(1,UUID.class),t,c).stream().findFirst();}
    @Override public Optional<FormRef> latestPublishedForm(UUID t,String f,String p,String n){return jdbc.query("select id,version_no from workflow.wf_form_definition where tenant_id=? and form_code=? and process_code=? and node_code=? and enabled and not is_deleted order by version_no desc limit 1",(r,x)->new FormRef(r.getObject(1,UUID.class),r.getInt(2)),t,f,p,n).stream().findFirst();}
    @Override public Optional<Target> target(UUID t,UUID employee){return jdbc.query("select e.id,ui.org_id from org.employee e join iam.user_identity ui on ui.tenant_id=e.tenant_id and ui.employee_id=e.id and ui.is_primary and not ui.is_deleted and ui.effective_start_at<=now() and (ui.effective_end_at is null or ui.effective_end_at>now()) where e.tenant_id=? and e.id=? and e.employment_status='ACTIVE' and not e.is_deleted order by ui.effective_start_at desc limit 1",(r,n)->new Target(r.getObject(1,UUID.class),r.getObject(2,UUID.class)),t,employee).stream().findFirst();}
    @Override public List<UUID> permissionCandidates(UUID t,String p,UUID center){return jdbc.query("select distinct ui.employee_id from iam.user_role ur join iam.role r on r.tenant_id=ur.tenant_id and r.id=ur.role_id and r.enabled and not r.is_deleted join iam.role_permission rp on rp.tenant_id=r.tenant_id and rp.role_id=r.id and not rp.is_deleted join iam.permission pm on pm.tenant_id=rp.tenant_id and pm.id=rp.permission_id and not pm.is_deleted join iam.user_identity ui on ui.tenant_id=ur.tenant_id and ui.user_id=ur.user_id and not ui.is_deleted and (ur.identity_id is null or ur.identity_id=ui.id) join org.employee e on e.tenant_id=ui.tenant_id and e.id=ui.employee_id and e.employment_status='ACTIVE' and not e.is_deleted where ur.tenant_id=? and pm.permission_code=? and ui.org_id=? and not ur.is_deleted and ur.effective_start_at<=now() and (ur.effective_end_at is null or ur.effective_end_at>now()) order by ui.employee_id",(r,n)->r.getObject(1,UUID.class),t,p,center);}
    @Override public boolean employeeHasPermission(UUID t,UUID employee,String permission){return count("select count(*) from iam.user_role ur join iam.role r on r.tenant_id=ur.tenant_id and r.id=ur.role_id and r.enabled and not r.is_deleted join iam.role_permission rp on rp.tenant_id=r.tenant_id and rp.role_id=r.id and not rp.is_deleted join iam.permission p on p.tenant_id=rp.tenant_id and p.id=rp.permission_id and not p.is_deleted join iam.user_identity ui on ui.tenant_id=ur.tenant_id and ui.user_id=ur.user_id and not ui.is_deleted and (ur.identity_id is null or ur.identity_id=ui.id) where ur.tenant_id=? and ui.employee_id=? and p.permission_code=? and not ur.is_deleted and ur.effective_start_at<=now() and (ur.effective_end_at is null or ur.effective_end_at>now())",t,employee,permission)>0;}
    @Override public Optional<Rule> publishedRule(UUID t,String kind,String event,Instant at){return jdbc.query("select id,rule_code,version_no,point_kind,event_type,unit_points,min_points,max_points,manual_review_threshold from reward.point_rule_version where tenant_id=? and point_kind=? and event_type=? and status='PUBLISHED' and effective_from<=? and (effective_to is null or effective_to>?) order by version_no desc,id limit 1",(r,n)->new Rule(r.getObject(1,UUID.class),r.getString(2),r.getInt(3),r.getString(4),r.getString(5),r.getLong(6),r.getLong(7),r.getLong(8),r.getLong(9)),t,kind,event,ts(at),ts(at)).stream().findFirst();}
    @Override public void insertRule(UUID t,UUID id,RuleDraftCommand c,UUID actor){one(jdbc.update("insert into reward.point_rule_version(id,tenant_id,rule_code,version_no,point_kind,event_type,unit_points,min_points,max_points,manual_review_threshold,effective_from,effective_to,status,created_by) values(?,?,?,?,?,?,?,?,?,?,?,?,\'DRAFT\',?)",id,t,c.ruleCode().trim().toUpperCase(),c.versionNo(),c.pointKind().trim().toUpperCase(),c.eventType().trim().toUpperCase(),c.unitPoints(),c.minPoints(),c.maxPoints(),c.manualReviewThreshold(),ts(c.effectiveFrom()),ts(c.effectiveTo()),actor),"rule draft insert");for(RankRule rank:c.ranks())one(jdbc.update("insert into reward.point_rank_rule(id,tenant_id,rule_version_id,rank_code,min_balance,max_balance) values(gen_random_uuid(),?,?,?,?,?)",t,id,rank.rankCode().trim().toUpperCase(),rank.minBalance(),rank.maxBalance()),"rank rule insert");}
    @Override public void publishRule(UUID t,UUID id,UUID actor){lock(t,id,"rule-publish");RuleConfiguration current=rule(t,id).orElseThrow(()->rejected("point rule version not found"));if(!"DRAFT".equals(current.status()))throw rejected("only a draft rule can be published");Long overlaps=jdbc.queryForObject("select count(*) from reward.point_rule_version r where r.tenant_id=? and r.id<>? and r.status='PUBLISHED' and r.point_kind=? and r.event_type=? and r.effective_from<coalesce(?::timestamptz,'infinity'::timestamptz) and coalesce(r.effective_to,'infinity'::timestamptz)>?",Long.class,t,id,current.rule().pointKind(),current.rule().eventType(),ts(current.effectiveTo()),ts(current.effectiveFrom()));if(overlaps!=null&&overlaps>0)throw rejected("published rule effective interval overlaps existing version");one(jdbc.update("update reward.point_rule_version set status='PUBLISHED',published_by=?,published_at=now() where tenant_id=? and id=? and status='DRAFT'",actor,t,id),"rule publication");}
    @Override public Optional<RuleConfiguration> rule(UUID t,UUID id){return jdbc.query("select id,rule_code,version_no,point_kind,event_type,unit_points,min_points,max_points,manual_review_threshold,status,effective_from,effective_to from reward.point_rule_version where tenant_id=? and id=?",(r,n)->configuration(t,r),t,id).stream().findFirst();}
    @Override public List<RuleConfiguration> rules(UUID t){return jdbc.query("select id,rule_code,version_no,point_kind,event_type,unit_points,min_points,max_points,manual_review_threshold,status,effective_from,effective_to from reward.point_rule_version where tenant_id=? order by rule_code,version_no desc,id",(r,n)->configuration(t,r),t);}
    @Override public void insert(PointTransaction v,UUID actor){one(jdbc.update("""
        insert into reward.point_transaction(id,tenant_id,business_no,workflow_instance_id,status,version_no,created_by,updated_by,source_channel,business_date,subject,reason,priority,risk_level,owner_center_id,owner_employee_id,actual_amount,change_action,change_reason,cost_center_id,currency,employee_event_type,fact_occurred_at,fact_summary,impact_level,points_delta,source_fact_key,affected_employee_id,point_kind,rule_version_id,original_transaction_id,expires_at,business_object_type,business_object_no,business_object_name,quantity,calculated_points,capped_points)
        values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """,v.id(),v.tenantId(),v.businessNo(),v.workflowInstanceId(),"LEDGER_ENTRY",0,actor,actor,"PORTAL",v.businessDate(),v.subject(),v.reason(),"NORMAL",v.riskGrade(),v.ownerCenterId(),v.affectedEmployeeId(),0,v.changeAction(),v.reason(),v.ownerCenterId().toString().replace("-",""),"POINT",v.employeeEventType(),ts(v.factOccurredAt()),v.factSummary(),v.riskGrade(),v.cappedPoints(),v.sourceFactKey(),v.affectedEmployeeId(),v.pointKind(),v.ruleVersionId(),v.originalTransactionId(),ts(v.expiresAt()),v.businessObjectType(),v.businessObjectNo(),v.businessObjectName(),v.quantity(),v.calculatedPoints(),v.cappedPoints()),"transaction insert");}
    @Override public void appendEvent(UUID t,UUID id,int expected,String type,JsonNode evidence,UUID actor){lock(t,id,"event");Integer count=jdbc.queryForObject("select count(*) from reward.point_transaction_event where tenant_id=? and point_transaction_id=?",Integer.class,t,id);if(count==null||count!=expected)throw rejected("concurrent immutable event version conflict");one(jdbc.update("insert into reward.point_transaction_event(id,tenant_id,point_transaction_id,event_seq,event_type,evidence,actor_employee_id) values(gen_random_uuid(),?,?,?,?,cast(? as jsonb),?)",t,id,expected+1,type,json(evidence),actor),"event append");}
    @Override public void appendPosting(UUID t,UUID id,long points,UUID rule,String mode,String risk,JsonNode evidence,UUID actor){one(jdbc.update("insert into reward.point_posting_fact(id,tenant_id,point_transaction_id,posted_points,rule_version_id,posting_mode,risk_grade,evidence,posted_by) values(gen_random_uuid(),?,?,?,?,?,?,cast(? as jsonb),?)",t,id,points,rule,mode,risk,json(evidence),actor),"posting append");}
    @Override public void appendBalance(UUID t,UUID id,UUID employee,long balance,String rank,JsonNode evidence,UUID actor){one(jdbc.update("insert into reward.point_balance_fact(id,tenant_id,point_transaction_id,affected_employee_id,effective_balance,rank_code,evidence,calculated_by) values(gen_random_uuid(),?,?,?,?,?,cast(? as jsonb),?)",t,id,employee,balance,rank,json(evidence),actor),"balance append");}
    @Override public boolean isPosted(UUID t,UUID id){return count("select count(*) from reward.point_posting_fact where tenant_id=? and point_transaction_id=?",t,id)>0;}
    @Override public Optional<AdjustmentRequest> adjustmentRequest(UUID t,UUID id){return jdbc.query("select (evidence->>'adjustmentRequested')::boolean,(evidence->>'adjustmentPoints')::bigint,evidence->>'adjustmentReason' from reward.point_transaction_event where tenant_id=? and point_transaction_id=? and event_type='SUBMIT_ADJUSTMENT' order by event_seq desc limit 1",(r,n)->new AdjustmentRequest(r.getBoolean(1),(Long)r.getObject(2),r.getString(3)),t,id).stream().findFirst();}
    @Override public List<UUID> eventRecipients(UUID t,UUID id,String... types){LinkedHashSet<UUID> values=new LinkedHashSet<>();for(String type:types)jdbc.query("select actor_employee_id from reward.point_transaction_event where tenant_id=? and point_transaction_id=? and event_type=? order by event_seq desc limit 1",(r,n)->r.getObject(1,UUID.class),t,id,type).stream().findFirst().ifPresent(values::add);return List.copyOf(values);}
    @Override public long effectiveBalance(UUID t,UUID employee,Instant at){Long value=jdbc.queryForObject("select coalesce(sum(p.posted_points),0) from reward.point_posting_fact p join reward.point_transaction x on x.tenant_id=p.tenant_id and x.id=p.point_transaction_id where p.tenant_id=? and x.affected_employee_id=? and (x.expires_at is null or x.expires_at>?) and not x.is_deleted",Long.class,t,employee,ts(at));return value==null?0:value;}
    @Override public Optional<String> rank(UUID t,UUID rule,long balance){return jdbc.query("select rank_code from reward.point_rank_rule where tenant_id=? and rule_version_id=? and min_balance<=? and (max_balance is null or max_balance>=?) order by min_balance desc,id limit 1",(r,n)->r.getString(1),t,rule,balance,balance).stream().findFirst();}
    @Override public Optional<PointTransaction> find(UUID t,UUID id){return jdbc.query(select("where x.tenant_id=? and x.id=? and not x.is_deleted"),(r,n)->map(r),t,id).stream().findFirst();}@Override public List<PointTransaction> list(UUID t){return jdbc.query(select("where x.tenant_id=? and not x.is_deleted order by x.created_at desc,x.id desc"),(r,n)->map(r),t);}
    private String select(String suffix){return """
        select x.id,x.tenant_id,x.business_no,x.workflow_instance_id,w.instance_no,w.current_node_code,x.business_date,x.subject,x.reason,x.owner_center_id,x.affected_employee_id,x.source_fact_key,x.point_kind,x.rule_version_id,rv.rule_code,rv.version_no rule_version_no,x.quantity,x.calculated_points,x.capped_points,x.risk_level,x.business_object_type,x.business_object_no,x.business_object_name,x.employee_event_type,x.fact_occurred_at,x.fact_summary,x.expires_at,x.change_action,x.original_transaction_id,x.created_at,(select count(*) from reward.point_transaction_event e where e.tenant_id=x.tenant_id and e.point_transaction_id=x.id) event_version from reward.point_transaction x join reward.point_rule_version rv on rv.tenant_id=x.tenant_id and rv.id=x.rule_version_id left join workflow.wf_instance w on w.tenant_id=x.tenant_id and w.id=x.workflow_instance_id and not w.is_deleted
        """+suffix;}
    private PointTransaction map(ResultSet r)throws SQLException{UUID t=r.getObject("tenant_id",UUID.class),id=r.getObject("id",UUID.class);return new PointTransaction(id,t,r.getString("business_no"),r.getObject("workflow_instance_id",UUID.class),r.getString("instance_no"),r.getString("current_node_code"),r.getString("current_node_code"),r.getInt("event_version"),date(r,"business_date"),r.getString("subject"),r.getString("reason"),r.getObject("owner_center_id",UUID.class),r.getObject("affected_employee_id",UUID.class),r.getString("source_fact_key"),r.getString("point_kind"),r.getObject("rule_version_id",UUID.class),r.getString("rule_code"),r.getInt("rule_version_no"),r.getLong("quantity"),r.getLong("calculated_points"),r.getLong("capped_points"),r.getString("risk_level"),r.getString("business_object_type"),r.getString("business_object_no"),r.getString("business_object_name"),r.getString("employee_event_type"),instant(r,"fact_occurred_at"),r.getString("fact_summary"),instant(r,"expires_at"),r.getString("change_action"),r.getObject("original_transaction_id",UUID.class),events(t,id),posting(t,id),balance(t,id),instant(r,"created_at"));}
    private List<Event> events(UUID t,UUID id){return jdbc.query("select id,event_seq,event_type,evidence,actor_employee_id,created_at from reward.point_transaction_event where tenant_id=? and point_transaction_id=? order by event_seq,id",(r,n)->new Event(r.getObject(1,UUID.class),r.getInt(2),r.getString(3),read(r.getString(4)),r.getObject(5,UUID.class),instant(r,"created_at")),t,id);}
    private RuleConfiguration configuration(UUID t,ResultSet r)throws SQLException{UUID id=r.getObject("id",UUID.class);Rule rule=new Rule(id,r.getString("rule_code"),r.getInt("version_no"),r.getString("point_kind"),r.getString("event_type"),r.getLong("unit_points"),r.getLong("min_points"),r.getLong("max_points"),r.getLong("manual_review_threshold"));List<RankRule> ranks=jdbc.query("select rank_code,min_balance,max_balance from reward.point_rank_rule where tenant_id=? and rule_version_id=? order by min_balance,rank_code",(x,n)->new RankRule(x.getString(1),x.getLong(2),(Long)x.getObject(3)),t,id);return new RuleConfiguration(rule,r.getString("status"),instant(r,"effective_from"),instant(r,"effective_to"),ranks);}
    private Posting posting(UUID t,UUID id){return jdbc.query("select posted_points,posting_mode,risk_grade,posted_at from reward.point_posting_fact where tenant_id=? and point_transaction_id=?",(r,n)->new Posting(r.getLong(1),r.getString(2),r.getString(3),instant(r,"posted_at")),t,id).stream().findFirst().orElse(null);}private Balance balance(UUID t,UUID id){return jdbc.query("select effective_balance,rank_code,calculated_at from reward.point_balance_fact where tenant_id=? and point_transaction_id=?",(r,n)->new Balance(r.getLong(1),r.getString(2),instant(r,"calculated_at")),t,id).stream().findFirst().orElse(null);}
    private long count(String sql,Object... args){Long n=jdbc.queryForObject(sql,Long.class,args);return n==null?0:n;}private void lock(UUID t,UUID id,String d){jdbc.query("select pg_advisory_xact_lock(hashtextextended(?,0))",r->{r.next();return null;},t+":"+id+":"+d);}private String json(JsonNode n){try{return mapper.writeValueAsString(n);}catch(JsonProcessingException e){throw rejected("JSON serialization failed");}}private JsonNode read(String n){try{return n==null?null:mapper.readTree(n);}catch(JsonProcessingException e){throw rejected("persisted JSON invalid");}}private static void one(int n,String a){if(n!=1)throw rejected(a+" failed");}private static Timestamp ts(Instant v){return v==null?null:Timestamp.from(v);}private static LocalDate date(ResultSet r,String f)throws SQLException{var v=r.getDate(f);return v==null?null:v.toLocalDate();}private static Instant instant(ResultSet r,String f)throws SQLException{Object v=r.getObject(f);if(v==null)return null;if(v instanceof OffsetDateTime o)return o.toInstant();if(v instanceof Timestamp x)return x.toInstant();throw new SQLException("unsupported timestamp "+f);}private static ProcessRejectedException rejected(String m){return new ProcessRejectedException("P015 "+m);}
}
