package cn.shangjingu.platform.reward;

import cn.shangjingu.platform.core.database.DatabaseSecurityContext;
import cn.shangjingu.platform.core.database.TenantTransactionRunner;
import cn.shangjingu.platform.core.event.TransactionalOutboxService;
import cn.shangjingu.platform.core.process.BusinessNumberService;
import cn.shangjingu.platform.core.process.IdempotencyClaim;
import cn.shangjingu.platform.core.process.IdempotencyRegistry;
import cn.shangjingu.platform.core.process.ProcessRejectedException;
import cn.shangjingu.platform.workflow.WorkflowFormService;
import cn.shangjingu.platform.workflow.WorkflowRuntimeService;
import cn.shangjingu.platform.workflow.WorkflowTaskAssignmentService;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;

/** P015 keeps the canonical point ledger immutable; corrections are linked new rows. */
@Service
public final class PointLedgerService {
    public static final String PROCESS_CODE="P015",INITIAL_FORM_CODE="CTR-P015-F01";private static final Duration TTL=Duration.ofHours(24);
    private static final Map<String,Set<String>> ACTIONS=Map.ofEntries(Map.entry("S01",Set.of("REGISTER_EVENT")),Map.entry("S02",Set.of("VALIDATE_SOURCE")),Map.entry("S03",Set.of("CHECK_DUPLICATE")),Map.entry("S04",Set.of("MATCH_RULE")),Map.entry("S05",Set.of("CALCULATE_CAP")),Map.entry("S06",Set.of("CLASSIFY_RISK")),Map.entry("S07",Set.of("POST_LEDGER")),Map.entry("S08",Set.of("CONFIRM_NOTICE")),Map.entry("S09",Set.of("SUBMIT_ADJUSTMENT","REVIEW_ADJUSTMENT")),Map.entry("S10",Set.of("RECALCULATE_BALANCE")));
    private final TenantTransactionRunner transactions;private final IdempotencyRegistry idempotency;private final BusinessNumberService numbers;private final TransactionalOutboxService outbox;private final WorkflowRuntimeService workflow;private final WorkflowTaskAssignmentService tasks;private final WorkflowFormService forms;private final Repository repository;private final ObjectMapper mapper;
    public PointLedgerService(TenantTransactionRunner transactions,IdempotencyRegistry idempotency,BusinessNumberService numbers,TransactionalOutboxService outbox,WorkflowRuntimeService workflow,WorkflowTaskAssignmentService tasks,WorkflowFormService forms,Repository repository,ObjectMapper mapper){this.transactions=transactions;this.idempotency=idempotency;this.numbers=numbers;this.outbox=outbox;this.workflow=workflow;this.tasks=tasks;this.forms=forms;this.repository=repository;this.mapper=mapper;}

    public PointTransaction create(DatabaseSecurityContext actor,String key,String hash,CreateCommand c){requireActor(actor);validateCreate(c);return transactions.required(actor,()->{
        IdempotencyClaim claim=idempotency.claim(actor.tenantId(),actor.employeeId(),key,hash,"reward.point_transaction",UUID.randomUUID(),TTL);if(claim.existing())return required(actor,claim.resourceId());
        Target target=repository.target(actor.tenantId(),c.affectedEmployeeId()).orElseThrow(()->rejected("active affected employee is required"));Rule rule=repository.publishedRule(actor.tenantId(),normalize(c.pointKind()),normalize(c.employeeEventType()),c.factOccurredAt()).orElseThrow(()->rejected("an effective published point rule is required"));
        long calculated;try{calculated=Math.multiplyExact(rule.unitPoints(),c.quantity());}catch(ArithmeticException e){throw rejected("point calculation overflow");}long capped=Math.max(rule.minPoints(),Math.min(rule.maxPoints(),calculated));String risk=Math.abs(capped)>=rule.manualReviewThreshold()?"L3":"L1";
        List<UUID> managers=candidates(actor,"p015.points.manage",target.centerId()),reviewers=candidates(actor,"p015.points.review",target.centerId()),adjusters=candidates(actor,"p015.points.adjust",target.centerId());UUID wfVersion=repository.latestPublishedWorkflowVersion(actor.tenantId(),PROCESS_CODE).orElseThrow(()->rejected("published workflow is not configured"));FormRef form=repository.latestPublishedForm(actor.tenantId(),INITIAL_FORM_CODE,PROCESS_CODE,"S01").orElseThrow(()->rejected("published initial form is not configured"));
        UUID id=claim.resourceId();String businessNo=numbers.next(actor.tenantId(),actor.employeeId(),PROCESS_CODE);ObjectNode context=mapper.createObjectNode().put("affectedEmployeeId",target.employeeId().toString()).put("ownerCenterId",target.centerId().toString());context.set("ownerCandidateIds",uuids(List.of(target.employeeId())));context.set("managerCandidateIds",uuids(managers));context.set("reviewerCandidateIds",uuids(reviewers));context.set("adjusterCandidateIds",uuids(adjusters));
        WorkflowRuntimeService.Result started=workflow.start(new WorkflowRuntimeService.StartCommand(actor.tenantId(),actor.employeeId(),actor.identityId(),wfVersion,"reward.point_transaction",id,businessNo,c.subject().trim(),"L3".equals(risk)?"HIGH":"NORMAL",context,scoped(key,"start")));
        PointTransaction draft=new PointTransaction(id,actor.tenantId(),businessNo,started.instance().id(),started.instance().instanceNo(),"S01",label("S01"),0,c.businessDate(),c.subject().trim(),trim(c.reason()),target.centerId(),target.employeeId(),c.sourceFactKey().trim(),normalize(c.pointKind()),rule.id(),rule.ruleCode(),rule.versionNo(),c.quantity(),calculated,capped,risk,c.businessObjectType().trim(),c.businessObjectNo().trim(),c.businessObjectName().trim(),normalize(c.employeeEventType()),c.factOccurredAt(),c.factSummary().trim(),c.expiresAt(),"AWARD",null,List.of(),null,null,Instant.now());
        try{repository.insert(draft,actor.employeeId());repository.appendEvent(actor.tenantId(),id,0,"TRANSACTION_CREATED",evidence("created",c.evidence(),actor.employeeId()),actor.employeeId());}catch(DataIntegrityViolationException e){throw new ProcessRejectedException("P015 source, rule or employee fact conflicts with persisted ledger",e);}
        forms.submit(new WorkflowFormService.SubmitForm(actor.tenantId(),actor.employeeId(),actor.identityId(),started.instance().id(),null,form.id(),form.versionNo(),initial(started.instance(),draft),scoped(key,"form")));PointTransaction result=required(actor,id);emit(actor,result,"S01","CREATED","S01",List.of(actor.employeeId()));return result;
    });}

    public RuleConfiguration createRule(DatabaseSecurityContext actor,String key,String hash,RuleDraftCommand c){requireActor(actor);validateRule(c);return transactions.required(actor,()->{
        IdempotencyClaim claim=idempotency.claim(actor.tenantId(),actor.employeeId(),key,hash,"reward.point_rule_version",UUID.randomUUID(),TTL);if(claim.existing())return requiredRule(actor,claim.resourceId());
        try{repository.insertRule(actor.tenantId(),claim.resourceId(),c,actor.employeeId());}catch(DataIntegrityViolationException e){throw new ProcessRejectedException("P015 rule draft conflicts with persisted configuration",e);}RuleConfiguration result=requiredRule(actor,claim.resourceId());emitRule(actor,result,"DRAFT_CREATED");return result;
    });}
    public RuleConfiguration publishRule(DatabaseSecurityContext actor,UUID id,String key,String hash){requireActor(actor);Objects.requireNonNull(id,"P015 rule id is required");return transactions.required(actor,()->{
        IdempotencyClaim claim=idempotency.claim(actor.tenantId(),actor.employeeId(),key,hash,"reward.point_rule_version.publish",id,TTL);if(claim.existing())return requiredRule(actor,id);
        try{repository.publishRule(actor.tenantId(),id,actor.employeeId());}catch(DataIntegrityViolationException e){throw new ProcessRejectedException("P015 rule publication conflicts with effective configuration",e);}RuleConfiguration result=requiredRule(actor,id);emitRule(actor,result,"PUBLISHED");return result;
    });}
    public List<RuleConfiguration> rules(DatabaseSecurityContext actor){requireActor(actor);return transactions.required(actor,()->repository.rules(actor.tenantId()));}

    public PointTransaction act(DatabaseSecurityContext actor,UUID id,String actionCode,String key,String hash,ActionCommand c){requireActor(actor);Objects.requireNonNull(c,"P015 action command is required");String action=normalize(actionCode);return transactions.required(actor,()->{
        IdempotencyClaim claim=idempotency.claim(actor.tenantId(),actor.employeeId(),key,hash,"reward.point_transaction.action",id,TTL);if(claim.existing())return required(actor,id);PointTransaction current=required(actor,id);if(current.versionNo()!=c.expectedVersion())throw rejected("point transaction version conflict");WorkflowRuntimeService.Result runtime=workflow.get(actor.tenantId(),current.workflowInstanceId());String node=runtime.instance().currentNodeCode();if(!node.equals(current.currentNodeCode()))throw rejected("business projection is stale");if(!ACTIONS.getOrDefault(node,Set.of()).contains(action))throw rejected("action is not allowed at "+node);validateAction(actor,current,action,c);JsonNode immutable=requiredEvidence(c.evidence(),action);
        try{
            if("POST_LEDGER".equals(action))repository.appendPosting(actor.tenantId(),id,current.cappedPoints(),current.ruleVersionId(),"L3".equals(current.riskGrade())?"MANUAL_REVIEW":"AUTOMATIC",current.riskGrade(),immutable,actor.employeeId());
            if("SUBMIT_ADJUSTMENT".equals(action))repository.appendEvent(actor.tenantId(),id,current.versionNo(),action,adjustmentEvidence(c,immutable,actor.employeeId()),actor.employeeId());
            else if("REVIEW_ADJUSTMENT".equals(action)){AdjustmentRequest request=repository.adjustmentRequest(actor.tenantId(),id).orElseThrow(()->rejected("employee adjustment choice is required"));if(request.requested()&&Boolean.TRUE.equals(c.adjustmentApproved())){PointTransaction adjustment=adjustment(current,request,actor);repository.insert(adjustment,actor.employeeId());repository.appendPosting(actor.tenantId(),adjustment.id(),adjustment.cappedPoints(),adjustment.ruleVersionId(),"MANUAL_REVIEW","L3",immutable,actor.employeeId());}repository.appendEvent(actor.tenantId(),id,current.versionNo(),action,reviewEvidence(c,request,immutable,actor.employeeId()),actor.employeeId());}
            else if("RECALCULATE_BALANCE".equals(action)){long balance=repository.effectiveBalance(actor.tenantId(),current.affectedEmployeeId(),Instant.now());String rank=repository.rank(actor.tenantId(),current.ruleVersionId(),balance).orElseThrow(()->rejected("published rule has no matching rank for effective balance"));repository.appendBalance(actor.tenantId(),id,current.affectedEmployeeId(),balance,rank,immutable,actor.employeeId());repository.appendEvent(actor.tenantId(),id,current.versionNo(),action,evidence(action,immutable,actor.employeeId()),actor.employeeId());}
            else repository.appendEvent(actor.tenantId(),id,current.versionNo(),action,evidence(action,immutable,actor.employeeId()),actor.employeeId());
        }catch(DataIntegrityViolationException e){throw new ProcessRejectedException("P015 immutable ledger fact conflicts with persisted lifecycle",e);}
        if("SUBMIT_ADJUSTMENT".equals(action)){PointTransaction result=required(actor,id);emit(actor,result,node,action,node,repository.eventRecipients(actor.tenantId(),id,"REVIEW_ADJUSTMENT"));return result;}
        if(runtime.task()!=null)tasks.claim(new WorkflowTaskAssignmentService.ClaimCommand(actor.tenantId(),runtime.task().id(),actor.employeeId()));WorkflowRuntimeService.Result moved=workflow.act(new WorkflowRuntimeService.ActionCommand(actor.tenantId(),actor.employeeId(),actor.identityId(),current.workflowInstanceId(),runtime.task()==null?null:runtime.task().id(),node,action,trim(c.resultSummary()),scoped(key,"workflow")));PointTransaction result=required(actor,id);emit(actor,result,node,action,moved.instance().currentNodeCode(),recipients(moved));return result;
    });}

    public Optional<PointTransaction> find(DatabaseSecurityContext actor,UUID id){requireActor(actor);return transactions.required(actor,()->repository.find(actor.tenantId(),id).map(v->project(v,actor)));}public List<PointTransaction> list(DatabaseSecurityContext actor){requireActor(actor);return transactions.required(actor,()->repository.list(actor.tenantId()).stream().map(v->project(v,actor)).toList());}
    public String permissionForAction(String action){return switch(normalize(action)){case"CLASSIFY_RISK","POST_LEDGER"->"p015.points.review";case"CONFIRM_NOTICE"->"p015.points.read";case"SUBMIT_ADJUSTMENT","REVIEW_ADJUSTMENT"->"p015.points.adjust";default->"p015.points.manage";};}
    private PointTransaction project(PointTransaction v,DatabaseSecurityContext actor){WorkflowRuntimeService.Result r=workflow.get(actor.tenantId(),v.workflowInstanceId());return v.runtime(r.instance().currentNodeCode(),label(r.instance().currentNodeCode()));}
    private void validateAction(DatabaseSecurityContext actor,PointTransaction v,String action,ActionCommand c){boolean affected=actor.employeeId().equals(v.affectedEmployeeId());if(Set.of("CONFIRM_NOTICE","SUBMIT_ADJUSTMENT").contains(action)&&!affected)throw rejected("only affected employee may confirm notice or submit adjustment");if(!Set.of("CONFIRM_NOTICE","SUBMIT_ADJUSTMENT").contains(action)&&affected)throw rejected("affected employee cannot validate, review, post or recalculate own points");if("POST_LEDGER".equals(action)&&repository.isPosted(actor.tenantId(),v.id()))throw rejected("point transaction is already posted");if("SUBMIT_ADJUSTMENT".equals(action)){if(c.adjustmentRequested()==null)throw rejected("adjustment request or explicit waiver is required");if(Boolean.TRUE.equals(c.adjustmentRequested())&&(c.adjustmentPoints()==null||c.adjustmentPoints()==0||trim(c.adjustmentReason())==null))throw rejected("non-zero adjustment points and reason are required");if(repository.adjustmentRequest(actor.tenantId(),v.id()).isPresent())throw rejected("adjustment choice is append-only and already submitted");}if("REVIEW_ADJUSTMENT".equals(action)&&repository.adjustmentRequest(actor.tenantId(),v.id()).map(AdjustmentRequest::requested).orElse(false)&&c.adjustmentApproved()==null)throw rejected("requested adjustment requires an explicit approve or reject decision");}
    private PointTransaction adjustment(PointTransaction base,AdjustmentRequest request,DatabaseSecurityContext actor){long points=request.points();if(Math.abs(points)>Math.max(Math.abs(base.cappedPoints()),1_000_000L))throw rejected("adjustment exceeds safe linked-transaction bound");return new PointTransaction(UUID.randomUUID(),base.tenantId(),numbers.next(base.tenantId(),actor.employeeId(),PROCESS_CODE),base.workflowInstanceId(),base.workflowInstanceNo(),"S09",label("S09"),0,LocalDate.now(),"Adjustment for "+base.businessNo(),request.reason(),base.ownerCenterId(),base.affectedEmployeeId(),base.sourceFactKey()+":ADJ:"+UUID.randomUUID(),base.pointKind(),base.ruleVersionId(),base.ruleCode(),base.ruleVersionNo(),1,points,points,"L3",base.businessObjectType(),base.businessObjectNo(),base.businessObjectName(),base.employeeEventType(),Instant.now(),request.reason(),base.expiresAt(),points==-base.cappedPoints()?"REVERSAL":"ADJUSTMENT",base.id(),List.of(),null,null,Instant.now());}
    private List<WorkflowFormService.FieldValue> initial(WorkflowRuntimeService.Instance i,PointTransaction v){return List.of(text("process_instance_no",i.instanceNo()),text("affected_employee_id",v.affectedEmployeeId().toString()),text("source_fact_key",v.sourceFactKey()),text("point_kind",v.pointKind()),text("rule_version",v.ruleCode()+":"+v.ruleVersionNo()));}private static WorkflowFormService.FieldValue text(String c,String v){return new WorkflowFormService.FieldValue(c,"TEXT",v,null,null,null,null,null,"P2",false);}
    private List<UUID> candidates(DatabaseSecurityContext actor,String permission,UUID center){List<UUID> values=repository.permissionCandidates(actor.tenantId(),permission,center).stream().filter(id->repository.employeeHasPermission(actor.tenantId(),id,"p015.points.read")).toList();if(values.isEmpty())throw rejected("eligible business candidate with read permission is required for "+permission);return values;}private List<UUID> recipients(WorkflowRuntimeService.Result r){if(r.task()==null||r.task().candidateRule()==null)return List.of();JsonNode f=r.task().candidateRule().get("field"),v=f==null||r.instance().contextSnapshot()==null?null:r.instance().contextSnapshot().get(f.asText());List<UUID> ids=new ArrayList<>();if(v!=null&&v.isArray())v.forEach(n->{try{ids.add(UUID.fromString(n.asText()));}catch(IllegalArgumentException e){throw rejected("workflow candidate id is invalid");}});return List.copyOf(ids);}
    private ObjectNode adjustmentEvidence(ActionCommand c,JsonNode supplied,UUID actor){ObjectNode n=evidence("SUBMIT_ADJUSTMENT",supplied,actor);n.put("adjustmentRequested",Boolean.TRUE.equals(c.adjustmentRequested()));if(Boolean.TRUE.equals(c.adjustmentRequested())){n.put("adjustmentPoints",c.adjustmentPoints());n.put("adjustmentReason",c.adjustmentReason().trim());}return n;}private ObjectNode reviewEvidence(ActionCommand c,AdjustmentRequest request,JsonNode supplied,UUID actor){ObjectNode n=evidence("REVIEW_ADJUSTMENT",supplied,actor);n.put("adjustmentRequested",request.requested());n.put("adjustmentDecision",request.requested()?(Boolean.TRUE.equals(c.adjustmentApproved())?"APPROVED":"REJECTED"):"NOT_APPLICABLE");return n;}private ObjectNode evidence(String event,JsonNode supplied,UUID actor){ObjectNode n=mapper.createObjectNode().put("event",event).put("actorEmployeeId",actor.toString()).put("recordedAt",Instant.now().toString());n.set("sourceEvidence",requiredEvidence(supplied,event));return n;}
    private void emit(DatabaseSecurityContext actor,PointTransaction value,String node,String action,String target,List<UUID> ids){ObjectNode p=mapper.createObjectNode().put("pointTransactionId",value.id().toString()).put("businessNo",value.businessNo()).put("event","CREATED".equals(action)?"P015.points.created":"P015.stage."+node.substring(1)+".completed").put("actionCode",action).put("nodeCode",target);p.set("recipientEmployeeIds",uuids(ids));int version=Math.max(1,value.versionNo()+1);outbox.enqueue(new TransactionalOutboxService.Command(actor.tenantId(),actor.employeeId(),"P015_POINTS",value.id(),"P015_POINT_EVENT",version,json(p),"p015:"+value.id()+":v"+version+":"+node.toLowerCase(Locale.ROOT)+":"+action.toLowerCase(Locale.ROOT)));}
    private void emitRule(DatabaseSecurityContext actor,RuleConfiguration value,String action){ObjectNode p=mapper.createObjectNode().put("ruleVersionId",value.rule().id().toString()).put("ruleCode",value.rule().ruleCode()).put("versionNo",value.rule().versionNo()).put("status",value.status()).put("actionCode",action);outbox.enqueue(new TransactionalOutboxService.Command(actor.tenantId(),actor.employeeId(),"P015_POINT_RULE",value.rule().id(),"P015_POINT_RULE_EVENT",value.rule().versionNo(),json(p),"p015:rule:"+value.rule().id()+":"+action.toLowerCase(Locale.ROOT)));}
    private ArrayNode uuids(List<UUID> ids){ArrayNode a=mapper.createArrayNode();new LinkedHashSet<>(ids).forEach(x->a.add(x.toString()));return a;}private PointTransaction required(DatabaseSecurityContext actor,UUID id){return repository.find(actor.tenantId(),id).map(v->project(v,actor)).orElseThrow(()->rejected("point transaction not found"));}private String json(JsonNode n){try{return mapper.writeValueAsString(n);}catch(JsonProcessingException e){throw rejected("event payload cannot be serialized");}}
    private static void validateCreate(CreateCommand c){if(c==null||c.businessDate()==null||c.affectedEmployeeId()==null||c.factOccurredAt()==null||c.quantity()<=0)throw rejected("business date, affected employee, fact time and positive quantity are required");if(trim(c.subject())==null||c.subject().trim().length()<5||trim(c.reason())==null||c.reason().trim().length()<5)throw rejected("subject and reason are required");if(trim(c.sourceFactKey())==null||trim(c.pointKind())==null||trim(c.businessObjectType())==null||trim(c.businessObjectNo())==null||trim(c.businessObjectName())==null||trim(c.employeeEventType())==null||trim(c.factSummary())==null)throw rejected("source, point kind, business object and fact fields are required");requiredEvidence(c.evidence(),"business event");}
    private static void validateRule(RuleDraftCommand c){if(c==null||c.versionNo()<=0||c.effectiveFrom()==null||c.manualReviewThreshold()<=0||c.minPoints()>c.maxPoints()||c.unitPoints()<c.minPoints()||c.unitPoints()>c.maxPoints()||c.effectiveTo()!=null&&!c.effectiveTo().isAfter(c.effectiveFrom()))throw rejected("valid version, point bounds, risk threshold and effective interval are required");normalize(c.ruleCode());normalize(c.pointKind());normalize(c.eventType());if(c.ranks()==null||c.ranks().isEmpty())throw rejected("at least one rank range is required");for(int i=0;i<c.ranks().size();i++){RankRule a=c.ranks().get(i);normalize(a.rankCode());if(a.maxBalance()!=null&&a.maxBalance()<a.minBalance())throw rejected("rank range is invalid");for(int j=i+1;j<c.ranks().size();j++){RankRule b=c.ranks().get(j);long aMax=a.maxBalance()==null?Long.MAX_VALUE:a.maxBalance(),bMax=b.maxBalance()==null?Long.MAX_VALUE:b.maxBalance();if(a.minBalance()<=bMax&&b.minBalance()<=aMax)throw rejected("rank ranges overlap");}}}
    private static JsonNode requiredEvidence(JsonNode n,String p){if(n==null||!n.isObject()||n.isEmpty())throw rejected(p+" requires immutable evidence");return n;}private static void requireActor(DatabaseSecurityContext a){if(a==null||a.tenantId()==null||a.employeeId()==null||a.identityId()==null||a.orgId()==null)throw rejected("authenticated tenant employee identity is required");}private static String normalize(String v){String n=v==null?"":v.trim().toUpperCase(Locale.ROOT);if(!n.matches("[A-Z0-9_]{1,64}"))throw rejected("invalid code");return n;}private static String scoped(String k,String s){if(k==null||k.isBlank()||k.length()>160)throw rejected("valid idempotency key is required");return k+":"+s;}private static String trim(String v){return v==null||v.isBlank()?null:v.trim();}private static ProcessRejectedException rejected(String m){return new ProcessRejectedException("P015 "+m);}
    public static String label(String n){return switch(n){case"S01"->"Business event";case"S02"->"Person and source validation";case"S03"->"Exception and duplicate validation";case"S04"->"Rule version match";case"S05"->"Calculation and cap";case"S06"->"Risk classification";case"S07"->"Automatic posting or manual review";case"S08"->"Employee notification";case"S09"->"Appeal adjustment or reversal";case"S10"->"Balance and rank recalculation";case"END"->"Closed";default->throw rejected("unknown source node "+n);};}
    public record CreateCommand(LocalDate businessDate,String subject,String reason,UUID affectedEmployeeId,String sourceFactKey,String pointKind,long quantity,String businessObjectType,String businessObjectNo,String businessObjectName,String employeeEventType,Instant factOccurredAt,String factSummary,Instant expiresAt,JsonNode evidence){}public record ActionCommand(int expectedVersion,Boolean adjustmentRequested,Long adjustmentPoints,String adjustmentReason,Boolean adjustmentApproved,String resultSummary,JsonNode evidence){}
    public record Rule(UUID id,String ruleCode,int versionNo,String pointKind,String eventType,long unitPoints,long minPoints,long maxPoints,long manualReviewThreshold){}public record RankRule(String rankCode,long minBalance,Long maxBalance){}public record RuleDraftCommand(String ruleCode,int versionNo,String pointKind,String eventType,long unitPoints,long minPoints,long maxPoints,long manualReviewThreshold,Instant effectiveFrom,Instant effectiveTo,List<RankRule> ranks){}public record RuleConfiguration(Rule rule,String status,Instant effectiveFrom,Instant effectiveTo,List<RankRule> ranks){}public record AdjustmentRequest(boolean requested,Long points,String reason){}public record Target(UUID employeeId,UUID centerId){}public record FormRef(UUID id,int versionNo){}public record Event(UUID id,int eventSeq,String eventType,JsonNode evidence,UUID actorEmployeeId,Instant createdAt){}public record Posting(long postedPoints,String postingMode,String riskGrade,Instant postedAt){}public record Balance(long effectiveBalance,String rankCode,Instant calculatedAt){}
    public record PointTransaction(UUID id,UUID tenantId,String businessNo,UUID workflowInstanceId,String workflowInstanceNo,String currentNodeCode,String status,int versionNo,LocalDate businessDate,String subject,String reason,UUID ownerCenterId,UUID affectedEmployeeId,String sourceFactKey,String pointKind,UUID ruleVersionId,String ruleCode,int ruleVersionNo,long quantity,long calculatedPoints,long cappedPoints,String riskGrade,String businessObjectType,String businessObjectNo,String businessObjectName,String employeeEventType,Instant factOccurredAt,String factSummary,Instant expiresAt,String changeAction,UUID originalTransactionId,List<Event> events,Posting posting,Balance balance,Instant createdAt){PointTransaction runtime(String node,String state){return new PointTransaction(id,tenantId,businessNo,workflowInstanceId,workflowInstanceNo,node,state,versionNo,businessDate,subject,reason,ownerCenterId,affectedEmployeeId,sourceFactKey,pointKind,ruleVersionId,ruleCode,ruleVersionNo,quantity,calculatedPoints,cappedPoints,riskGrade,businessObjectType,businessObjectNo,businessObjectName,employeeEventType,factOccurredAt,factSummary,expiresAt,changeAction,originalTransactionId,events,posting,balance,createdAt);}public PointTransaction metadataOnly(){return new PointTransaction(id,tenantId,businessNo,workflowInstanceId,workflowInstanceNo,currentNodeCode,status,versionNo,businessDate,"Restricted point transaction",null,ownerCenterId,null,null,pointKind,ruleVersionId,ruleCode,ruleVersionNo,0,0,0,riskGrade,businessObjectType,null,null,null,null,null,expiresAt,changeAction,null,List.of(),null,balance==null?null:new Balance(balance.effectiveBalance(),balance.rankCode(),balance.calculatedAt()),createdAt);}}
    private RuleConfiguration requiredRule(DatabaseSecurityContext actor,UUID id){return repository.rule(actor.tenantId(),id).orElseThrow(()->rejected("point rule version not found"));}
    public interface Repository{Optional<UUID> latestPublishedWorkflowVersion(UUID t,String code);Optional<FormRef> latestPublishedForm(UUID t,String f,String p,String n);Optional<Target> target(UUID t,UUID employee);List<UUID> permissionCandidates(UUID t,String permission,UUID center);boolean employeeHasPermission(UUID t,UUID employee,String permission);Optional<Rule> publishedRule(UUID t,String kind,String event,Instant at);void insertRule(UUID t,UUID id,RuleDraftCommand command,UUID actor);void publishRule(UUID t,UUID id,UUID actor);Optional<RuleConfiguration> rule(UUID t,UUID id);List<RuleConfiguration> rules(UUID t);void insert(PointTransaction v,UUID actor);void appendEvent(UUID t,UUID id,int expectedVersion,String type,JsonNode evidence,UUID actor);void appendPosting(UUID t,UUID id,long points,UUID rule,String mode,String risk,JsonNode evidence,UUID actor);void appendBalance(UUID t,UUID id,UUID employee,long balance,String rank,JsonNode evidence,UUID actor);boolean isPosted(UUID t,UUID id);Optional<AdjustmentRequest> adjustmentRequest(UUID t,UUID id);List<UUID> eventRecipients(UUID t,UUID id,String... types);long effectiveBalance(UUID t,UUID employee,Instant at);Optional<String> rank(UUID t,UUID rule,long balance);Optional<PointTransaction> find(UUID t,UUID id);List<PointTransaction> list(UUID t);}
}
