-- 必须在postgres管理库中逐条执行；CREATE DATABASE不能处于事务块内。
CREATE ROLE sjg_owner NOLOGIN;
CREATE ROLE sjg_app LOGIN PASSWORD 'CHANGE_ME_STRONG_PASSWORD';
CREATE ROLE sjg_readonly LOGIN PASSWORD 'CHANGE_ME_STRONG_PASSWORD';
CREATE ROLE sjg_auditor LOGIN PASSWORD 'CHANGE_ME_STRONG_PASSWORD';
CREATE DATABASE sjg_oms OWNER sjg_owner ENCODING 'UTF8' TEMPLATE template0;
CREATE DATABASE sjg_audit OWNER sjg_owner ENCODING 'UTF8' TEMPLATE template0;
CREATE DATABASE sjg_dw OWNER sjg_owner ENCODING 'UTF8' TEMPLATE template0;
