-- 审计库仅允许INSERT/SELECT，不允许应用角色UPDATE/DELETE/TRUNCATE。
REVOKE UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA audit FROM sjg_app;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA audit TO sjg_app;
GRANT SELECT ON ALL TABLES IN SCHEMA audit TO sjg_auditor;
