package cn.shangjingu.platform.welfare;

import static cn.shangjingu.platform.welfare.P016CareService.*;

import cn.shangjingu.platform.core.process.ProcessRejectedException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcP016CareRepository implements P016CareService.Repository {
    private final JdbcTemplate jdbc;private final ObjectMapper mapper;public JdbcP016CareRepository(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
    @Override public Optional<UUID> latestPublishedWorkflowVersion(UUID t,String c){return jdbc.query("select v.id from workflow.wf_version v join workflow.wf_definition d on d.tenant_id=v.tenant_id and d.id=v.definition_id where v.tenant_id=? and d.process_code=? and d.enabled and not d.is_deleted and v.status='PUBLISHED' and not v.is_deleted and (v.effective_at is null or v.effective_at<=now()) order by v.version_no desc limit 1",(r,n)->r.getObject(1,UUID.class),t,c).stream().findFirst();}
    @Override public Optional<FormRef> latestPublishedForm(UUID t,String f,String p,String n){return jdbc.query("select id,version_no from workflow.wf_form_definition where tenant_id=? and form_code=? and process_code=? and node_code=? and enabled and not is_deleted order by version_no desc limit 1",(r,x)->new FormRef(r.getObject(1,UUID.class),r.getInt(2)),t,f,p,n).stream().findFirst();}
    @Override public Optional<Target> target(UUID t,UUID employee){return jdbc.query("""
        select e.id,ui.org_id,ui.user_id,ui.id identity_id from org.employee e join iam.user_identity ui on ui.tenant_id=e.tenant_id and ui.employee_id=e.id and ui.is_primary and not ui.is_deleted and ui.effective_start_at<=now() and (ui.effective_end_at is null or ui.effective_end_at>now()) where e.tenant_id=? and e.id=? and e.employment_status='ACTIVE' and not e.is_deleted order by ui.effective_start_at desc limit 1
        """,(r,n)->new Target(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class),r.getObject(4,UUID.class)),t,employee).stream().findFirst();}
    @Override public List<UUID> permissionCandidates(UUID t,String p,UUID center){return jdbc.query("""
        select distinct ui.employee_id from iam.user_role ur join iam.role r on r.tenant_id=ur.tenant_id and r.id=ur.role_id and r.enabled and not r.is_deleted join iam.role_permission rp on rp.tenant_id=r.tenant_id and rp.role_id=r.id and not rp.is_deleted join iam.permission pm on pm.tenant_id=rp.tenant_id and pm.id=rp.permission_id and not pm.is_deleted join iam.user_identity ui on ui.tenant_id=ur.tenant_id and ui.user_id=ur.user_id and not ui.is_deleted and (ur.identity_id is null or ur.identity_id=ui.id) join org.employee e on e.tenant_id=ui.tenant_id and e.id=ui.employee_id and e.employment_status='ACTIVE' and not e.is_deleted where ur.tenant_id=? and pm.permission_code=? and ui.org_id=? and not ur.is_deleted and ur.effective_start_at<=now() and (ur.effective_end_at is null or ur.effective_end_at>now()) order by ui.employee_id
        """,(r,n)->r.getObject(1,UUID.class),t,p,center);}
    @Override public boolean employeeHasPermission(UUID t,UUID employee,String permission){Long n=jdbc.queryForObject("""
        select count(*) from iam.user_identity ui join iam.user_role ur on ur.tenant_id=ui.tenant_id and ur.user_id=ui.user_id and (ur.identity_id is null or ur.identity_id=ui.id) and not ur.is_deleted join iam.role_permission rp on rp.tenant_id=ur.tenant_id and rp.role_id=ur.role_id and not rp.is_deleted join iam.permission p on p.tenant_id=rp.tenant_id and p.id=rp.permission_id and not p.is_deleted where ui.tenant_id=? and ui.employee_id=? and p.permission_code=? and not ui.is_deleted and ur.effective_start_at<=now() and (ur.effective_end_at is null or ur.effective_end_at>now())
        """,Long.class,t,employee,permission);return n!=null&&n>0;}
    @Override public void insert(CareCase v,UUID actor){one(jdbc.update("""
        insert into welfare.care_case(id,tenant_id,business_no,status,version_no,created_by,updated_by,source_channel,business_date,subject,reason,priority,risk_level,owner_center_id,owner_employee_id,benefit_amount,cost_center_id,currency,employee_event_type,fact_occurred_at,fact_summary,impact_level,source_fact_key,affected_employee_id,care_type,privacy_required,external_business_ref)
        values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """,v.id(),v.tenantId(),v.businessNo(),v.status(),0,actor,actor,"PORTAL",v.businessDate(),v.subject(),v.reason(),"NORMAL","HIGH",v.ownerCenterId(),v.affectedEmployeeId(),v.requestedAmount(),v.costCenterId(),v.currency(),"WELFARE_CARE",ts(v.factOccurredAt()),v.factSummary(),"L3",v.sourceFactKey(),v.affectedEmployeeId(),v.careType(),true,v.externalBusinessRef()),"insert");}
    @Override public int bindWorkflow(UUID t,UUID id,int v,UUID wf,UUID actor){return jdbc.update("update welfare.care_case set workflow_instance_id=?,version_no=version_no+1,updated_by=?,updated_at=now() where tenant_id=? and id=? and version_no=? and not is_deleted",wf,actor,t,id,v);}
    @Override public int move(UUID t,UUID id,int v,String status,String result,Instant closed,UUID actor){return jdbc.update("update welfare.care_case set status=?,result_summary=coalesce(cast(? as text),result_summary),closed_at=coalesce(?,closed_at),actual_start_at=coalesce(actual_start_at,now()),actual_end_at=coalesce(?,actual_end_at),version_no=version_no+1,updated_by=?,updated_at=now() where tenant_id=? and id=? and version_no=? and not is_deleted",status,result,ts(closed),ts(closed),actor,t,id,v);}
    @Override public void appendEvent(UUID t,UUID id,String type,JsonNode evidence,UUID actor){lock(t,id,"event");one(jdbc.update("""
        insert into welfare.care_case_event(id,tenant_id,care_case_id,event_seq,event_type,evidence,actor_employee_id) select gen_random_uuid(),?,?,coalesce(max(event_seq),0)+1,?,cast(? as jsonb),? from welfare.care_case_event where tenant_id=? and care_case_id=?
        """,t,id,type,json(evidence),actor,t,id),"event append");}
    @Override public Optional<UUID> eventActor(UUID t,UUID id,String type){return jdbc.query("select actor_employee_id from welfare.care_case_event where tenant_id=? and care_case_id=? and event_type=? order by event_seq desc limit 1",(r,n)->r.getObject(1,UUID.class),t,id,type).stream().findFirst();}
    @Override public void appendEligibility(UUID t,UUID id,String outcome,String ref,Instant at,JsonNode evidence,UUID actor){one(jdbc.update("insert into welfare.care_eligibility_fact(id,tenant_id,care_case_id,outcome,authority_reference,checked_at,evidence,checked_by) values(gen_random_uuid(),?,?,?,?,?,cast(? as jsonb),?)",t,id,outcome,ref,ts(at),json(evidence),actor),"eligibility append");}
    @Override public void appendConsent(UUID t,UUID id,String scope,String hash,Instant at,JsonNode evidence,UUID actor){one(jdbc.update("insert into welfare.care_privacy_consent(id,tenant_id,care_case_id,consent_scope,consent_hash,consented_at,evidence,consented_by) values(gen_random_uuid(),?,?,?,?,?,cast(? as jsonb),?)",t,id,scope,hash,ts(at),json(evidence),actor),"consent append");}
    @Override public void appendApproval(UUID t,UUID id,String outcome,String ref,BigDecimal amount,Instant at,JsonNode evidence,UUID actor){one(jdbc.update("insert into welfare.care_approval_fact(id,tenant_id,care_case_id,outcome,authority_reference,approved_amount,decided_at,evidence,decided_by) values(gen_random_uuid(),?,?,?,?,?,?,cast(? as jsonb),?)",t,id,outcome,ref,amount,ts(at),json(evidence),actor),"approval append");}
    @Override public void appendExecution(UUID t,UUID id,String kind,String ref,Instant at,BigDecimal amount,String currency,String invoiceCode,String invoiceNumber,LocalDate invoiceDate,BigDecimal invoiceAmount,String invoiceHash,JsonNode evidence,UUID actor){one(jdbc.update("insert into welfare.care_execution_receipt(id,tenant_id,care_case_id,execution_kind,external_reference,external_occurred_at,executed_amount,currency,invoice_code,invoice_number,invoice_date,invoice_amount,invoice_image_sha256,evidence,recorded_by) values(gen_random_uuid(),?,?,?,?,?,?,?,?,?,?,?,?,cast(? as jsonb),?)",t,id,kind,ref,ts(at),amount,currency,trim(invoiceCode),trim(invoiceNumber),invoiceDate,invoiceAmount,trim(invoiceHash),json(evidence),actor),"execution append");}
    @Override public void appendConfirmation(UUID t,UUID id,String outcome,Instant at,JsonNode evidence,UUID actor){one(jdbc.update("insert into welfare.care_employee_confirmation(id,tenant_id,care_case_id,outcome,confirmed_at,evidence,confirmed_by) values(gen_random_uuid(),?,?,?,?,cast(? as jsonb),?)",t,id,outcome,ts(at),json(evidence),actor),"confirmation append");}
    @Override public void appendReconciliation(UUID t,UUID id,String outcome,String ref,Instant at,JsonNode evidence,UUID actor){one(jdbc.update("insert into welfare.care_reconciliation_fact(id,tenant_id,care_case_id,outcome,external_reference,reconciled_at,evidence,reconciled_by) values(gen_random_uuid(),?,?,?,?,?,cast(? as jsonb),?)",t,id,outcome,ref,ts(at),json(evidence),actor),"reconciliation append");}
    @Override public Optional<String> confirmationOutcome(UUID t,UUID id){return jdbc.query("select outcome from welfare.care_employee_confirmation where tenant_id=? and care_case_id=?",(r,n)->r.getString(1),t,id).stream().findFirst();}
    @Override public boolean completeForArchive(UUID t,UUID id){Long n=jdbc.queryForObject("""
        select count(*) from welfare.care_case c join welfare.care_eligibility_fact e on e.tenant_id=c.tenant_id and e.care_case_id=c.id and e.outcome='ELIGIBLE' join welfare.care_privacy_consent p on p.tenant_id=c.tenant_id and p.care_case_id=c.id join welfare.care_approval_fact a on a.tenant_id=c.tenant_id and a.care_case_id=c.id and a.outcome='APPROVED' join welfare.care_execution_receipt x on x.tenant_id=c.tenant_id and x.care_case_id=c.id join welfare.care_employee_confirmation f on f.tenant_id=c.tenant_id and f.care_case_id=c.id join welfare.care_reconciliation_fact r on r.tenant_id=c.tenant_id and r.care_case_id=c.id where c.tenant_id=? and c.id=? and not c.is_deleted
        """,Long.class,t,id);return n!=null&&n==1;}
    @Override public Optional<CareCase> find(UUID t,UUID id){return jdbc.query(select("where c.tenant_id=? and c.id=? and not c.is_deleted"),(r,n)->map(r),t,id).stream().findFirst();}@Override public List<CareCase> list(UUID t){return jdbc.query(select("where c.tenant_id=? and not c.is_deleted order by c.created_at desc,c.id desc"),(r,n)->map(r),t);}
    private String select(String suffix){return """
        select c.id,c.tenant_id,c.business_no,c.workflow_instance_id,w.instance_no workflow_instance_no,w.current_node_code,c.status,c.version_no,c.business_date,c.subject,c.reason,c.owner_center_id,c.affected_employee_id,c.source_fact_key,c.care_type,c.benefit_amount,c.currency,c.cost_center_id,c.external_business_ref,c.fact_occurred_at,c.fact_summary,c.updated_at from welfare.care_case c left join workflow.wf_instance w on w.tenant_id=c.tenant_id and w.id=c.workflow_instance_id and not w.is_deleted
        """+suffix;}
    private CareCase map(ResultSet r)throws SQLException{UUID t=r.getObject("tenant_id",UUID.class),id=r.getObject("id",UUID.class);return new CareCase(id,t,r.getString("business_no"),r.getObject("workflow_instance_id",UUID.class),r.getString("workflow_instance_no"),r.getString("current_node_code"),r.getString("status"),r.getInt("version_no"),date(r,"business_date"),r.getString("subject"),r.getString("reason"),r.getObject("owner_center_id",UUID.class),r.getObject("affected_employee_id",UUID.class),r.getString("source_fact_key"),r.getString("care_type"),r.getBigDecimal("benefit_amount"),r.getString("currency"),r.getString("cost_center_id"),r.getString("external_business_ref"),instant(r,"fact_occurred_at"),r.getString("fact_summary"),events(t,id),eligibility(t,id).orElse(null),consent(t,id).orElse(null),approval(t,id).orElse(null),execution(t,id).orElse(null),confirmation(t,id).orElse(null),reconciliation(t,id).orElse(null),instant(r,"updated_at"));}
    private List<Event> events(UUID t,UUID id){return jdbc.query("select id,event_seq,event_type,evidence,actor_employee_id,created_at from welfare.care_case_event where tenant_id=? and care_case_id=? order by event_seq,id",(r,n)->new Event(r.getObject(1,UUID.class),r.getInt(2),r.getString(3),read(r.getString(4)),r.getObject(5,UUID.class),instant(r,"created_at")),t,id);}
    private Optional<EligibilityFact> eligibility(UUID t,UUID id){return jdbc.query("select outcome,authority_reference,checked_at,checked_by from welfare.care_eligibility_fact where tenant_id=? and care_case_id=?",(r,n)->new EligibilityFact(r.getString(1),r.getString(2),instant(r,"checked_at"),r.getObject(4,UUID.class)),t,id).stream().findFirst();}
    private Optional<ConsentFact> consent(UUID t,UUID id){return jdbc.query("select consent_scope,consent_hash,consented_at,consented_by from welfare.care_privacy_consent where tenant_id=? and care_case_id=?",(r,n)->new ConsentFact(r.getString(1),r.getString(2),instant(r,"consented_at"),r.getObject(4,UUID.class)),t,id).stream().findFirst();}
    private Optional<ApprovalFact> approval(UUID t,UUID id){return jdbc.query("select outcome,authority_reference,approved_amount,decided_at,decided_by from welfare.care_approval_fact where tenant_id=? and care_case_id=?",(r,n)->new ApprovalFact(r.getString(1),r.getString(2),r.getBigDecimal(3),instant(r,"decided_at"),r.getObject(5,UUID.class)),t,id).stream().findFirst();}
    private Optional<ExecutionReceipt> execution(UUID t,UUID id){return jdbc.query("select execution_kind,external_reference,external_occurred_at,executed_amount,currency,invoice_code,invoice_number,invoice_date,invoice_amount,invoice_image_sha256,recorded_by from welfare.care_execution_receipt where tenant_id=? and care_case_id=?",(r,n)->new ExecutionReceipt(r.getString(1),r.getString(2),instant(r,"external_occurred_at"),r.getBigDecimal(4),r.getString(5),r.getString(6),r.getString(7),date(r,"invoice_date"),r.getBigDecimal(9),r.getString(10),r.getObject(11,UUID.class)),t,id).stream().findFirst();}
    private Optional<ConfirmationFact> confirmation(UUID t,UUID id){return jdbc.query("select outcome,confirmed_at,confirmed_by from welfare.care_employee_confirmation where tenant_id=? and care_case_id=?",(r,n)->new ConfirmationFact(r.getString(1),instant(r,"confirmed_at"),r.getObject(3,UUID.class)),t,id).stream().findFirst();}
    private Optional<ReconciliationFact> reconciliation(UUID t,UUID id){return jdbc.query("select outcome,external_reference,reconciled_at,reconciled_by from welfare.care_reconciliation_fact where tenant_id=? and care_case_id=?",(r,n)->new ReconciliationFact(r.getString(1),r.getString(2),instant(r,"reconciled_at"),r.getObject(4,UUID.class)),t,id).stream().findFirst();}
    private void lock(UUID t,UUID id,String domain){jdbc.query("select pg_advisory_xact_lock(hashtextextended(?,0))",r->{r.next();return null;},t+":"+id+":"+domain);}private String json(JsonNode n){try{return mapper.writeValueAsString(n);}catch(JsonProcessingException e){throw rejected("JSON serialization failed");}}private JsonNode read(String n){try{return n==null?null:mapper.readTree(n);}catch(JsonProcessingException e){throw rejected("persisted JSON invalid");}}private static void one(int n,String action){if(n!=1)throw rejected(action+" failed");}private static String trim(String v){return v==null||v.isBlank()?null:v.trim();}private static Timestamp ts(Instant v){return v==null?null:Timestamp.from(v);}private static LocalDate date(ResultSet r,String f)throws SQLException{var v=r.getDate(f);return v==null?null:v.toLocalDate();}private static Instant instant(ResultSet r,String f)throws SQLException{Object v=r.getObject(f);if(v==null)return null;if(v instanceof OffsetDateTime o)return o.toInstant();if(v instanceof Timestamp x)return x.toInstant();throw new SQLException("unsupported timestamp "+f);}private static ProcessRejectedException rejected(String m){return new ProcessRejectedException("P016 "+m);}
}
