package cn.shangjingu.platform.welfare;

import cn.shangjingu.platform.core.database.DatabaseSecurityContext;
import cn.shangjingu.platform.core.database.TenantTransactionRunner;
import cn.shangjingu.platform.core.event.TransactionalOutboxService;
import cn.shangjingu.platform.core.process.BusinessNumberService;
import cn.shangjingu.platform.core.process.IdempotencyClaim;
import cn.shangjingu.platform.core.process.IdempotencyRegistry;
import cn.shangjingu.platform.core.process.ProcessRejectedException;
import cn.shangjingu.platform.workflow.WorkflowFormService;
import cn.shangjingu.platform.workflow.WorkflowRuntimeService;
import cn.shangjingu.platform.workflow.WorkflowTaskAssignmentService;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;

/** P016 records human-authorized welfare decisions and external execution receipts without initiating payment. */
@Service
public final class P016CareService {
    public static final String PROCESS_CODE="P016",INITIAL_FORM_CODE="CTR-P016-F01";private static final Duration TTL=Duration.ofHours(24);
    private static final Map<String,Set<String>> ACTIONS=Map.of(
        "S01",Set.of("SUBMIT_APPLICATION"),"S02",Set.of("CONFIRM_ELIGIBILITY","REJECT_ELIGIBILITY"),
        "S03",Set.of("AUTHORIZE_PRIVACY"),"S04",Set.of("APPROVE_CARE","REJECT_CARE"),
        "S05",Set.of("RECORD_EXECUTION"),"S06",Set.of("CONFIRM_RECEIPT"),
        "S07",Set.of("RECONCILE"),"S08",Set.of("ARCHIVE"));
    private final TenantTransactionRunner transactions;private final IdempotencyRegistry idempotency;private final BusinessNumberService numbers;private final TransactionalOutboxService outbox;private final WorkflowRuntimeService workflow;private final WorkflowTaskAssignmentService tasks;private final WorkflowFormService forms;private final Repository repository;private final ObjectMapper mapper;
    public P016CareService(TenantTransactionRunner transactions,IdempotencyRegistry idempotency,BusinessNumberService numbers,TransactionalOutboxService outbox,WorkflowRuntimeService workflow,WorkflowTaskAssignmentService tasks,WorkflowFormService forms,Repository repository,ObjectMapper mapper){this.transactions=transactions;this.idempotency=idempotency;this.numbers=numbers;this.outbox=outbox;this.workflow=workflow;this.tasks=tasks;this.forms=forms;this.repository=repository;this.mapper=mapper;}

    public CareCase create(DatabaseSecurityContext actor,String key,String hash,CreateCommand c){requireActor(actor);validateCreate(c);return transactions.required(actor,()->{
        IdempotencyClaim claim=idempotency.claim(actor.tenantId(),actor.employeeId(),key,hash,"welfare.care_case.p016",UUID.randomUUID(),TTL);if(claim.existing())return required(actor.tenantId(),claim.resourceId());
        Target target=repository.target(actor.tenantId(),c.affectedEmployeeId()).orElseThrow(()->rejected("active affected employee is required"));List<UUID> managers=candidates(actor,"p016.welfare.manage",target.centerId()),approvers=candidates(actor,"p016.welfare.approve",target.centerId()),executors=candidates(actor,"p016.welfare.execute",target.centerId()),reconcilers=candidates(actor,"p016.welfare.reconcile",target.centerId());
        UUID wfVersion=repository.latestPublishedWorkflowVersion(actor.tenantId(),PROCESS_CODE).orElseThrow(()->rejected("published workflow is not configured"));FormRef form=repository.latestPublishedForm(actor.tenantId(),INITIAL_FORM_CODE,PROCESS_CODE,"S01").orElseThrow(()->rejected("published initial form is not configured"));UUID id=claim.resourceId();String businessNo=numbers.next(actor.tenantId(),actor.employeeId(),PROCESS_CODE);
        CareCase draft=new CareCase(id,actor.tenantId(),businessNo,null,null,"S01",label("S01"),0,c.businessDate(),c.subject().trim(),trim(c.reason()),target.centerId(),target.employeeId(),c.sourceFactKey().trim(),normalize(c.careType()),c.benefitAmount(),normalizeCurrency(c.currency()),c.costCenterId().trim(),c.externalBusinessRef()==null?null:c.externalBusinessRef().trim(),c.factOccurredAt(),c.factSummary().trim(),List.of(),null,null,null,null,null,null,Instant.now());
        try{repository.insert(draft,actor.employeeId());}catch(DataIntegrityViolationException e){throw new ProcessRejectedException("P016 source, employee or amount conflicts with persisted case",e);}
        ObjectNode context=mapper.createObjectNode().put("affectedEmployeeId",target.employeeId().toString()).put("ownerCenterId",target.centerId().toString());context.set("affectedCandidateIds",uuids(List.of(target.employeeId())));context.set("managerCandidateIds",uuids(managers));context.set("approverCandidateIds",uuids(approvers));context.set("executorCandidateIds",uuids(executors));context.set("reconcilerCandidateIds",uuids(reconcilers));
        WorkflowRuntimeService.Result started=workflow.start(new WorkflowRuntimeService.StartCommand(actor.tenantId(),actor.employeeId(),actor.identityId(),wfVersion,"welfare.care_case",id,businessNo,draft.subject(),"HIGH",context,scoped(key,"start")));
        forms.submit(new WorkflowFormService.SubmitForm(actor.tenantId(),actor.employeeId(),actor.identityId(),started.instance().id(),null,form.id(),form.versionNo(),initial(started.instance(),draft),scoped(key,"form")));if(repository.bindWorkflow(actor.tenantId(),id,0,started.instance().id(),actor.employeeId())!=1)throw rejected("concurrent workflow binding conflict");repository.appendEvent(actor.tenantId(),id,"CASE_CREATED",evidence("created",c.evidence(),actor.employeeId()),actor.employeeId());CareCase result=required(actor.tenantId(),id);emit(actor,result,"S01","CREATED","S01",List.of(actor.employeeId()));return result;
    });}

    public CareCase act(DatabaseSecurityContext actor,UUID id,String actionCode,String key,String hash,ActionCommand c){requireActor(actor);Objects.requireNonNull(c,"P016 action command is required");String action=normalize(actionCode);return transactions.required(actor,()->{
        IdempotencyClaim claim=idempotency.claim(actor.tenantId(),actor.employeeId(),key,hash,"welfare.care_case.p016.action",id,TTL);if(claim.existing())return required(actor.tenantId(),id);CareCase current=required(actor.tenantId(),id);if(current.versionNo()!=c.expectedVersion())throw rejected("care case version conflict");WorkflowRuntimeService.Result runtime=workflow.get(actor.tenantId(),current.workflowInstanceId());String node=runtime.instance().currentNodeCode();if(!node.equals(current.currentNodeCode()))throw rejected("business projection is stale");if(!ACTIONS.getOrDefault(node,Set.of()).contains(action))throw rejected("action is not allowed at "+node);validateAction(actor,current,action,c);JsonNode immutable=requiredEvidence(c.evidence(),action);
        try{
            if(Set.of("CONFIRM_ELIGIBILITY","REJECT_ELIGIBILITY").contains(action))repository.appendEligibility(actor.tenantId(),id,"CONFIRM_ELIGIBILITY".equals(action)?"ELIGIBLE":"INELIGIBLE",c.authorityReference().trim(),c.occurredAt(),immutable,actor.employeeId());
            if("AUTHORIZE_PRIVACY".equals(action))repository.appendConsent(actor.tenantId(),id,c.consentScope().trim(),c.consentHash().trim(),c.occurredAt(),immutable,actor.employeeId());
            if(Set.of("APPROVE_CARE","REJECT_CARE").contains(action))repository.appendApproval(actor.tenantId(),id,"APPROVE_CARE".equals(action)?"APPROVED":"REJECTED",c.authorityReference().trim(),c.approvedAmount(),c.occurredAt(),immutable,actor.employeeId());
            if("RECORD_EXECUTION".equals(action))repository.appendExecution(actor.tenantId(),id,normalize(c.executionKind()),c.externalReference().trim(),c.occurredAt(),c.executedAmount(),normalizeCurrency(c.currency()),c.invoiceCode(),c.invoiceNumber(),c.invoiceDate(),c.invoiceAmount(),c.invoiceImageSha256(),immutable,actor.employeeId());
            if("CONFIRM_RECEIPT".equals(action))repository.appendConfirmation(actor.tenantId(),id,normalize(c.confirmationOutcome()),c.occurredAt(),immutable,actor.employeeId());
            if("RECONCILE".equals(action))repository.appendReconciliation(actor.tenantId(),id,normalize(c.reconciliationOutcome()),c.externalReference().trim(),c.occurredAt(),immutable,actor.employeeId());
            repository.appendEvent(actor.tenantId(),id,action,evidence(action,immutable,actor.employeeId()),actor.employeeId());
        }catch(DataIntegrityViolationException e){throw new ProcessRejectedException("P016 immutable lifecycle fact conflicts with persisted case",e);}
        if(runtime.task()!=null)tasks.claim(new WorkflowTaskAssignmentService.ClaimCommand(actor.tenantId(),runtime.task().id(),actor.employeeId()));WorkflowRuntimeService.Result moved=workflow.act(new WorkflowRuntimeService.ActionCommand(actor.tenantId(),actor.employeeId(),actor.identityId(),current.workflowInstanceId(),runtime.task()==null?null:runtime.task().id(),node,action,trim(c.resultSummary()),scoped(key,"workflow")));Instant closed="END".equals(moved.instance().currentNodeCode())?moved.instance().finishedAt():null;if(repository.move(actor.tenantId(),id,current.versionNo(),label(moved.instance().currentNodeCode()),trim(c.resultSummary()),closed,actor.employeeId())!=1)throw rejected("concurrent care transition conflict");CareCase result=required(actor.tenantId(),id);emit(actor,result,node,action,moved.instance().currentNodeCode(),recipients(moved));return result;
    });}

    public Optional<CareCase> find(DatabaseSecurityContext actor,UUID id){requireActor(actor);return transactions.required(actor,()->repository.find(actor.tenantId(),id));}public List<CareCase> list(DatabaseSecurityContext actor){requireActor(actor);return transactions.required(actor,()->repository.list(actor.tenantId()));}
    public String permissionForAction(String action){return switch(normalize(action)){case"AUTHORIZE_PRIVACY","CONFIRM_RECEIPT"->"p016.welfare.read";case"APPROVE_CARE","REJECT_CARE"->"p016.welfare.approve";case"RECORD_EXECUTION"->"p016.welfare.execute";case"RECONCILE"->"p016.welfare.reconcile";default->"p016.welfare.manage";};}
    private void validateAction(DatabaseSecurityContext actor,CareCase v,String action,ActionCommand c){boolean affected=actor.employeeId().equals(v.affectedEmployeeId());if(Set.of("AUTHORIZE_PRIVACY","CONFIRM_RECEIPT").contains(action)&&!affected)throw rejected("only affected employee may authorize privacy or confirm receipt");if(!Set.of("SUBMIT_APPLICATION","AUTHORIZE_PRIVACY","CONFIRM_RECEIPT").contains(action)&&affected)throw rejected("affected employee cannot validate, approve, execute, reconcile or archive own case");
        if(Set.of("CONFIRM_ELIGIBILITY","REJECT_ELIGIBILITY","APPROVE_CARE","REJECT_CARE").contains(action)&&(trim(c.authorityReference())==null||c.occurredAt()==null))throw rejected("external authority reference and occurrence time are required");
        if(Set.of("APPROVE_CARE","REJECT_CARE").contains(action)){different(actor,v.id(),"CONFIRM_ELIGIBILITY","approval actor must be independent from eligibility actor");if("APPROVE_CARE".equals(action)&&(c.approvedAmount()==null||c.approvedAmount().signum()<0||(v.requestedAmount()!=null&&c.approvedAmount().compareTo(v.requestedAmount())>0)))throw rejected("approved amount must be non-negative and not exceed requested amount");if("REJECT_CARE".equals(action)&&c.approvedAmount()!=null)throw rejected("rejected case cannot carry approved amount");}
        if("AUTHORIZE_PRIVACY".equals(action)&&(trim(c.consentScope())==null||trim(c.consentHash())==null||!c.consentHash().matches("[0-9a-fA-F]{64}")||c.occurredAt()==null))throw rejected("privacy consent scope, SHA-256 and occurrence time are required");
        if("RECORD_EXECUTION".equals(action)){different(actor,v.id(),"APPROVE_CARE","executor must be independent from approver");String kind=normalize(c.executionKind());if(!Set.of("PAYMENT_RECEIPT","GOODS_DELIVERY","SERVICE_COMPLETION").contains(kind)||trim(c.externalReference())==null||c.occurredAt()==null)throw rejected("external execution kind, reference and occurrence time are required");if("PAYMENT_RECEIPT".equals(kind)&&(c.executedAmount()==null||c.executedAmount().signum()<0||trim(c.currency())==null))throw rejected("external payment receipt requires non-negative amount and currency");validateInvoice(c);}
        if("CONFIRM_RECEIPT".equals(action)&&(!Set.of("CONFIRMED","DISPUTED").contains(normalize(c.confirmationOutcome()))||c.occurredAt()==null))throw rejected("employee confirmation outcome and occurrence time are required");
        if("RECONCILE".equals(action)){different(actor,v.id(),"RECORD_EXECUTION","reconciler must be independent from executor");String outcome=normalize(c.reconciliationOutcome());if(!Set.of("MATCHED","EXCEPTION_RESOLVED").contains(outcome)||trim(c.externalReference())==null||c.occurredAt()==null)throw rejected("reconciliation outcome, external reference and occurrence time are required");if(repository.confirmationOutcome(actor.tenantId(),v.id()).filter("DISPUTED"::equals).isPresent()&&!"EXCEPTION_RESOLVED".equals(outcome))throw rejected("disputed employee confirmation requires resolved reconciliation evidence");}
        if("ARCHIVE".equals(action)&&!repository.completeForArchive(actor.tenantId(),v.id()))throw rejected("archive requires eligibility, consent, approval, execution, employee confirmation and reconciliation facts");
    }
    private static void validateInvoice(ActionCommand c){boolean any=c.invoiceCode()!=null||c.invoiceNumber()!=null||c.invoiceDate()!=null||c.invoiceAmount()!=null||c.invoiceImageSha256()!=null;if(!any)return;if(trim(c.invoiceCode())==null||trim(c.invoiceNumber())==null||c.invoiceDate()==null||c.invoiceAmount()==null||c.invoiceAmount().signum()<0||trim(c.invoiceImageSha256())==null||!c.invoiceImageSha256().matches("[0-9a-fA-F]{64}"))throw rejected("invoice evidence must be complete and carry SHA-256");}
    private void different(DatabaseSecurityContext actor,UUID id,String event,String message){if(repository.eventActor(actor.tenantId(),id,event).filter(actor.employeeId()::equals).isPresent())throw rejected(message);}
    private List<UUID> candidates(DatabaseSecurityContext actor,String permission,UUID center){List<UUID> values=repository.permissionCandidates(actor.tenantId(),permission,center).stream().filter(id->repository.employeeHasPermission(actor.tenantId(),id,"p016.welfare.read")).toList();if(values.isEmpty())throw rejected("eligible business candidate with read permission is required for "+permission);return values;}
    private List<UUID> recipients(WorkflowRuntimeService.Result r){if(r.task()==null||r.task().candidateRule()==null)return List.of();JsonNode f=r.task().candidateRule().get("field"),v=f==null||r.instance().contextSnapshot()==null?null:r.instance().contextSnapshot().get(f.asText());List<UUID> ids=new ArrayList<>();if(v!=null&&v.isArray())v.forEach(n->{try{ids.add(UUID.fromString(n.asText()));}catch(IllegalArgumentException e){throw rejected("workflow candidate id is invalid");}});return List.copyOf(ids);}
    private List<WorkflowFormService.FieldValue> initial(WorkflowRuntimeService.Instance i,CareCase v){return List.of(text("process_instance_no",i.instanceNo()),text("affected_employee_id",v.affectedEmployeeId().toString()),text("source_fact_key",v.sourceFactKey()),text("care_type",v.careType()),text("fact_summary",v.factSummary()));}private static WorkflowFormService.FieldValue text(String c,String v){return new WorkflowFormService.FieldValue(c,"TEXT",v,null,null,null,null,null,"P3",false);}
    private ObjectNode evidence(String event,JsonNode supplied,UUID actor){ObjectNode n=mapper.createObjectNode().put("event",event).put("actorEmployeeId",actor.toString()).put("recordedAt",Instant.now().toString());n.set("sourceEvidence",requiredEvidence(supplied,event));return n;}
    private void emit(DatabaseSecurityContext actor,CareCase value,String node,String action,String target,List<UUID> ids){ObjectNode p=mapper.createObjectNode().put("careCaseId",value.id().toString()).put("businessNo",value.businessNo()).put("event","CREATED".equals(action)?"P016.care.created":"P016.stage."+node.substring(1)+".completed").put("actionCode",action).put("nodeCode",target);p.set("recipientEmployeeIds",uuids(ids));int version=Math.max(1,value.versionNo()+1);outbox.enqueue(new TransactionalOutboxService.Command(actor.tenantId(),actor.employeeId(),"P016_CARE",value.id(),"P016_CARE_EVENT",version,json(p),"p016:"+value.id()+":v"+version+":"+node.toLowerCase(Locale.ROOT)+":"+action.toLowerCase(Locale.ROOT)));}
    private ArrayNode uuids(List<UUID> ids){ArrayNode a=mapper.createArrayNode();new LinkedHashSet<>(ids).forEach(x->a.add(x.toString()));return a;}private CareCase required(UUID t,UUID id){return repository.find(t,id).orElseThrow(()->rejected("care case not found"));}private String json(JsonNode n){try{return mapper.writeValueAsString(n);}catch(JsonProcessingException e){throw rejected("event payload cannot be serialized");}}
    private static void validateCreate(CreateCommand c){if(c==null||c.businessDate()==null||c.affectedEmployeeId()==null||c.factOccurredAt()==null)throw rejected("business date, affected employee and fact time are required");if(trim(c.subject())==null||c.subject().trim().length()<5||trim(c.factSummary())==null||c.factSummary().trim().length()<10)throw rejected("subject and fact summary are incomplete");if(trim(c.sourceFactKey())==null||trim(c.careType())==null||trim(c.currency())==null||trim(c.costCenterId())==null)throw rejected("source, care type, currency and cost center are required");if(!Set.of("MARRIAGE_BIRTH","HARDSHIP","HEALTH","BEREAVEMENT","OTHER").contains(normalize(c.careType())))throw rejected("care type is not source-backed");if(c.benefitAmount()!=null&&c.benefitAmount().signum()<0)throw rejected("requested benefit amount must be non-negative");requiredEvidence(c.evidence(),"care application");}
    private static JsonNode requiredEvidence(JsonNode n,String purpose){if(n==null||!n.isObject()||n.isEmpty())throw rejected(purpose+" requires immutable evidence");return n;}private static void requireActor(DatabaseSecurityContext a){if(a==null||a.tenantId()==null||a.employeeId()==null||a.identityId()==null||a.orgId()==null)throw rejected("authenticated tenant employee identity is required");}private static String normalize(String v){String n=v==null?"":v.trim().toUpperCase(Locale.ROOT);if(!n.matches("[A-Z0-9_]{1,32}"))throw rejected("invalid code");return n;}private static String normalizeCurrency(String v){String n=v==null?null:v.trim().toUpperCase(Locale.ROOT);if(n==null||!n.matches("[A-Z]{3}"))throw rejected("currency must be a three-letter code");return n;}private static String scoped(String k,String suffix){if(k==null||k.isBlank()||k.length()>160)throw rejected("valid idempotency key is required");return k+":"+suffix;}private static String trim(String v){return v==null||v.isBlank()?null:v.trim();}private static ProcessRejectedException rejected(String m){return new ProcessRejectedException("P016 "+m);}
    public static String label(String n){return switch(n){case"S01"->"Trigger or application";case"S02"->"Eligibility validation";case"S03"->"Materials and privacy consent";case"S04"->"Approval";case"S05"->"External execution receipt";case"S06"->"Employee confirmation";case"S07"->"Reconciliation";case"S08"->"Archive";case"END"->"Closed";default->throw rejected("unknown source node "+n);};}

    public record CreateCommand(LocalDate businessDate,String subject,String reason,UUID affectedEmployeeId,String sourceFactKey,String careType,BigDecimal benefitAmount,String currency,String costCenterId,String externalBusinessRef,Instant factOccurredAt,String factSummary,JsonNode evidence){}
    public record ActionCommand(int expectedVersion,String authorityReference,Instant occurredAt,String consentScope,String consentHash,BigDecimal approvedAmount,String executionKind,String externalReference,BigDecimal executedAmount,String currency,String invoiceCode,String invoiceNumber,LocalDate invoiceDate,BigDecimal invoiceAmount,String invoiceImageSha256,String confirmationOutcome,String reconciliationOutcome,String resultSummary,JsonNode evidence){}
    public record Event(UUID id,int eventSeq,String eventType,JsonNode evidence,UUID actorEmployeeId,Instant createdAt){}public record EligibilityFact(String outcome,String authorityReference,Instant checkedAt,UUID checkedBy){}public record ConsentFact(String consentScope,String consentHash,Instant consentedAt,UUID consentedBy){}public record ApprovalFact(String outcome,String authorityReference,BigDecimal approvedAmount,Instant decidedAt,UUID decidedBy){}public record ExecutionReceipt(String executionKind,String externalReference,Instant occurredAt,BigDecimal executedAmount,String currency,String invoiceCode,String invoiceNumber,LocalDate invoiceDate,BigDecimal invoiceAmount,String invoiceImageSha256,UUID recordedBy){}public record ConfirmationFact(String outcome,Instant confirmedAt,UUID confirmedBy){}public record ReconciliationFact(String outcome,String externalReference,Instant reconciledAt,UUID reconciledBy){}public record Target(UUID employeeId,UUID centerId,UUID userId,UUID identityId){}public record FormRef(UUID id,int versionNo){}
    public record CareCase(UUID id,UUID tenantId,String businessNo,UUID workflowInstanceId,String workflowInstanceNo,String currentNodeCode,String status,int versionNo,LocalDate businessDate,String subject,String reason,UUID ownerCenterId,UUID affectedEmployeeId,String sourceFactKey,String careType,BigDecimal requestedAmount,String currency,String costCenterId,String externalBusinessRef,Instant factOccurredAt,String factSummary,List<Event> events,EligibilityFact eligibility,ConsentFact consent,ApprovalFact approval,ExecutionReceipt execution,ConfirmationFact confirmation,ReconciliationFact reconciliation,Instant updatedAt){public CareCase metadataOnly(){return new CareCase(id,tenantId,businessNo,workflowInstanceId,workflowInstanceNo,currentNodeCode,status,versionNo,businessDate,"Restricted welfare case",null,ownerCenterId,null,null,careType,null,null,null,null,null,null,List.of(),null,null,null,null,null,null,updatedAt);}}
    public interface Repository{Optional<UUID> latestPublishedWorkflowVersion(UUID t,String c);Optional<FormRef> latestPublishedForm(UUID t,String f,String p,String n);Optional<Target> target(UUID t,UUID employee);List<UUID> permissionCandidates(UUID t,String p,UUID center);boolean employeeHasPermission(UUID t,UUID employee,String permission);void insert(CareCase v,UUID actor);int bindWorkflow(UUID t,UUID id,int version,UUID wf,UUID actor);int move(UUID t,UUID id,int version,String status,String result,Instant closed,UUID actor);void appendEvent(UUID t,UUID id,String type,JsonNode evidence,UUID actor);Optional<UUID> eventActor(UUID t,UUID id,String type);void appendEligibility(UUID t,UUID id,String outcome,String reference,Instant at,JsonNode evidence,UUID actor);void appendConsent(UUID t,UUID id,String scope,String hash,Instant at,JsonNode evidence,UUID actor);void appendApproval(UUID t,UUID id,String outcome,String reference,BigDecimal amount,Instant at,JsonNode evidence,UUID actor);void appendExecution(UUID t,UUID id,String kind,String reference,Instant at,BigDecimal amount,String currency,String invoiceCode,String invoiceNumber,LocalDate invoiceDate,BigDecimal invoiceAmount,String invoiceHash,JsonNode evidence,UUID actor);void appendConfirmation(UUID t,UUID id,String outcome,Instant at,JsonNode evidence,UUID actor);void appendReconciliation(UUID t,UUID id,String outcome,String reference,Instant at,JsonNode evidence,UUID actor);Optional<String> confirmationOutcome(UUID t,UUID id);boolean completeForArchive(UUID t,UUID id);Optional<CareCase> find(UUID t,UUID id);List<CareCase> list(UUID t);}
}
