<script setup lang="ts">
import { computed, ref } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import type { RuntimePortalCode } from '../platform/portal-config'
import { usePortalSessionStore } from '../session'
import NavigationIcon from './NavigationIcon.vue'
import { projectNavigationGroups, resolveActiveGroup, splitProjectedMobileNavigation, type NavigationRouteAccessRule } from './navigation-projection'
import { PORTAL_IA_NAVIGATION } from './navigation-source'
const props=withDefaults(defineProps<{runtimeCode:RuntimePortalCode;mobile?:boolean;identityLabel?:string|null}>(),{mobile:false,identityLabel:null})
const route=useRoute(),router=useRouter(),session=usePortalSessionStore(),expanded=ref<Set<string>>(new Set())
const paths=computed(()=>new Set(router.getRoutes().map(r=>r.path)))
const rules=computed<ReadonlyMap<string,NavigationRouteAccessRule>>(()=>{const m=new Map<string,NavigationRouteAccessRule>();for(const r of router.getRoutes()){const all=typeof r.meta.permission==='string'?[r.meta.permission]:[];const any=Array.isArray(r.meta.permissionsAny)?r.meta.permissionsAny.filter((x):x is string=>typeof x==='string'):[];if(all.length||any.length)m.set(r.path,{all,any})}return m})
const groups=computed(()=>projectNavigationGroups(PORTAL_IA_NAVIGATION,{runtimeCode:props.runtimeCode,permissions:new Set(session.session?.permissions??[]),implementedRoutePaths:paths.value,routeAccessRules:rules.value,mobile:props.mobile,identityLabel:props.identityLabel??null}))
const mobile=computed(()=>splitProjectedMobileNavigation(groups.value));const active=computed(()=>resolveActiveGroup(groups.value,route.path,route.query.module))
function open(key:string){const n=new Set(expanded.value);n.has(key)?n.delete(key):n.add(key);expanded.value=n}function target(g:(typeof groups.value)[number]){return(g.items.find(i=>i.state==='implemented')??g.items[0])?.routePath??'/'}
</script>
<template><nav class="nav" :class="{mobile:props.mobile}">
<template v-if="!props.mobile"><div v-for="g in groups" :key="g.key" class="group"><RouterLink v-if="g.items.length===1" class="top" :class="{active:active?.key===g.key}" :to="g.items[0]!.routePath"><NavigationIcon :icon="g.iconKey"/><span>{{ g.label }}</span><small v-if="g.items[0]!.state!=='implemented'">{{ g.items[0]!.state==='developing'?'开发中':'无权限' }}</small></RouterLink><template v-else><button class="top" :class="{active:active?.key===g.key}" @click="open(g.key)"><NavigationIcon :icon="g.iconKey"/><span>{{ g.label }}</span><small v-if="g.centerScoped&&g.contextLabel">{{ g.contextLabel }}</small><b>{{ expanded.has(g.key)?'−':'+' }}</b></button><div v-show="expanded.has(g.key)||active?.key===g.key" class="sub"><RouterLink v-for="i in g.items" :key="i.key" :to="i.routePath"><span>{{ i.label }}</span><small v-if="i.state!=='implemented'">{{ i.state==='developing'?'开发中':'无权限' }}</small></RouterLink></div></template></div></template>
<template v-else><RouterLink v-for="g in mobile.primary" :key="g.key" :to="target(g)"><NavigationIcon :icon="g.iconKey"/><span>{{ g.label }}</span></RouterLink><details v-if="mobile.overflow.length"><summary>更多</summary><div class="more"><RouterLink v-for="g in mobile.overflow" :key="g.key" :to="target(g)">{{ g.label }}</RouterLink></div></details></template>
</nav></template>
<style scoped>.nav{display:grid;gap:4px}.group{min-width:0}.top{width:100%;min-height:44px;display:flex;align-items:center;gap:10px;padding:8px 10px;border:0;border-radius:12px;background:transparent;color:#475569;text-decoration:none;font:inherit;text-align:left;cursor:pointer}.top:hover,.top.active{background:#fff7ed;color:#c2410c}.top svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.8}.top span{flex:1}.top small{font-size:10px;color:#94a3b8}.top b{font-weight:500}.sub{display:grid;gap:2px;padding:2px 0 6px 38px}.sub a{display:flex;justify-content:space-between;gap:8px;padding:7px 9px;border-radius:9px;color:#64748b;text-decoration:none;font-size:13px}.sub a:hover,.sub a.router-link-active{background:#fff7ed;color:#ea580c}.sub small{font-size:10px}.mobile{display:flex;justify-content:space-around;align-items:center}.mobile>a,.mobile summary{display:flex;flex-direction:column;align-items:center;gap:2px;color:#64748b;text-decoration:none;font-size:10px}.mobile svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.8}.mobile details{position:relative}.mobile summary{list-style:none;cursor:pointer}.more{position:absolute;right:0;bottom:42px;min-width:180px;padding:8px;background:#fff;border:1px solid #e2e8f0;border-radius:12px;box-shadow:0 12px 30px rgba(15,23,42,.12)}.more a{display:block;padding:8px;color:#475569;text-decoration:none}</style>
