package cn.shangjingu.platform.workflow;

import cn.shangjingu.platform.core.database.DatabaseSecurityContext;
import cn.shangjingu.platform.core.database.TenantTransactionRunner;
import cn.shangjingu.platform.core.event.TransactionalOutboxService;
import cn.shangjingu.platform.core.process.IdempotencyClaim;
import cn.shangjingu.platform.core.process.IdempotencyRegistry;
import cn.shangjingu.platform.core.process.ProcessRejectedException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import org.springframework.stereotype.Service;

@Service
public final class LearningService {
    public static final String PROCESS_CODE="P010", MANAGE="p010.learning.manage", CERTIFY="p010.learning.certify";
    private static final Duration IDEMPOTENCY_TTL=Duration.ofHours(24);
    private final TenantTransactionRunner tx; private final IdempotencyRegistry idempotency; private final TransactionalOutboxService outbox;
    private final WorkflowRuntimeService workflow; private final WorkflowTaskAssignmentService tasks; private final WorkflowFormService forms;
    private final Repository repo; private final ObjectMapper mapper;
    public LearningService(TenantTransactionRunner tx,IdempotencyRegistry idempotency,TransactionalOutboxService outbox,WorkflowRuntimeService workflow,WorkflowTaskAssignmentService tasks,WorkflowFormService forms,Repository repo,ObjectMapper mapper){this.tx=tx;this.idempotency=idempotency;this.outbox=outbox;this.workflow=workflow;this.tasks=tasks;this.forms=forms;this.repo=repo;this.mapper=mapper;}

    public Optional<Aggregate> find(DatabaseSecurityContext a,UUID id){actor(a);return tx.required(a,()->repo.find(a.tenantId(),id).map(this::aggregate));}
    public List<Aggregate> list(DatabaseSecurityContext a){actor(a);return tx.required(a,()->repo.list(a.tenantId()).stream().map(this::aggregate).toList());}

    public Aggregate progress(DatabaseSecurityContext a,UUID id,String key,String hash,ProgressCommand c){
        actor(a);Objects.requireNonNull(c);if(c.completionRate()==null||c.completionRate().compareTo(BigDecimal.ZERO)<0||c.completionRate().compareTo(BigDecimal.valueOf(100))>0)throw reject("completionRate must be 0-100");
        return tx.required(a,()->{LearningRecord r=required(a.tenantId(),id);self(a,r);node(r,"S03");if(claim(a,key,hash,"progress",id))return aggregate(r);repo.appendEvidence(a.tenantId(),id,"LEARNING_PROGRESS",a.employeeId(),null,c.completionRate(),null,c.note(),null);repo.updateProgress(a.tenantId(),id,c.completionRate(),a.employeeId());if(c.completionRate().compareTo(BigDecimal.valueOf(100))==0){repo.markLearningCompleted(a.tenantId(),id,a.employeeId());advance(a,required(a.tenantId(),id),"S03","COMPLETE_LEARNING",scope(key,"workflow"),c.note());}emit(a,id,"LEARNING_PROGRESS");return aggregate(required(a.tenantId(),id));});
    }
    public Aggregate exam(DatabaseSecurityContext a,UUID id,String key,String hash,ExamCommand c){
        actor(a);Objects.requireNonNull(c);if(c.score1000()<0||c.score1000()>1000)throw reject("score1000 must be 0-1000");
        return tx.required(a,()->{LearningRecord r=required(a.tenantId(),id);self(a,r);node(r,"S04");if(claim(a,key,hash,"exam",id))return aggregate(r);repo.appendEvidence(a.tenantId(),id,"EXAM_ATTEMPT",a.employeeId(),c.score1000(),null,null,c.note(),null);repo.updateExam(a.tenantId(),id,c.score1000(),a.employeeId());advance(a,required(a.tenantId(),id),"S04","RECORD_EXAM",scope(key,"workflow"),c.note());emit(a,id,"EXAM_RECORDED");return aggregate(required(a.tenantId(),id));});
    }
    public Aggregate practical(DatabaseSecurityContext a,UUID id,String key,String hash,PracticalCommand c){
        actor(a);Objects.requireNonNull(c);String result=practical(c.result());
        return tx.required(a,()->{LearningRecord r=required(a.tenantId(),id);self(a,r);node(r,"S05");if(claim(a,key,hash,"practical",id))return aggregate(r);repo.appendEvidence(a.tenantId(),id,"PRACTICAL_ASSESSMENT",a.employeeId(),null,null,result,c.note(),null);repo.updatePractical(a.tenantId(),id,result,a.employeeId());advance(a,required(a.tenantId(),id),"S05","RECORD_PRACTICAL",scope(key,"workflow"),c.note());emit(a,id,"PRACTICAL_RECORDED");return aggregate(required(a.tenantId(),id));});
    }
    public Aggregate action(DatabaseSecurityContext a,UUID id,String action,String key,String hash,ActionCommand c){
        actor(a);Objects.requireNonNull(c);String x=safe(action);
        return tx.required(a,()->{LearningRecord r=required(a.tenantId(),id);if(r.versionNo()!=c.expectedVersion())throw reject("version conflict");if(claim(a,key,hash,"action."+x.toLowerCase(Locale.ROOT),id))return aggregate(r);
            switch(r.currentNodeCode()){
                case "S01"->{must(x,"PUBLISH_CONTENT");start(a,r,key,c.note());repo.markContentPublished(a.tenantId(),id,a.employeeId());}
                case "S02"->{must(x,"ASSIGN_BY_RISK");repo.markRiskAssigned(a.tenantId(),id,a.employeeId());advance(a,r,"S02",x,scope(key,"workflow"),c.note());}
                case "S06"->{if(!x.equals("CERTIFY")&&!x.equals("RETURN_FOR_TRAINING"))throw reject("certification action invalid");repo.appendEvidence(a.tenantId(),id,"PROFESSIONAL_CERTIFICATION",a.employeeId(),null,null,x,c.note(),null);if(x.equals("CERTIFY"))repo.markCertified(a.tenantId(),id,a.employeeId());advance(a,r,"S06",x,scope(key,"workflow"),c.note());}
                case "S07"->{must(x,"ACTIVATE_QUALIFICATION");if(c.effectiveDate()==null)throw reject("effectiveDate is required");if(c.expireDate()!=null&&c.expireDate().isBefore(c.effectiveDate()))throw reject("expireDate before effectiveDate");repo.activateQualification(a.tenantId(),id,c.effectiveDate(),c.expireDate(),a.employeeId());repo.appendEvidence(a.tenantId(),id,"QUALIFICATION_ACTIVATION",a.employeeId(),null,null,null,c.note(),jsonDates(c.effectiveDate(),c.expireDate()));advance(a,required(a.tenantId(),id),"S07",x,scope(key,"workflow"),c.note());}
                case "S08"->{must(x,"LINK_PERMISSIONS");List<UUID> roles=repo.linkPermissions(a.tenantId(),id,a.employeeId());if(roles.isEmpty())throw reject("qualification permission binding is missing; fail closed");repo.appendEvidence(a.tenantId(),id,"PERMISSION_LINK",a.employeeId(),null,null,null,c.note(),jsonRoles(roles));repo.markPermissionLinked(a.tenantId(),id,a.employeeId());advance(a,required(a.tenantId(),id),"S08",x,scope(key,"workflow"),c.note());}
                case "S09"->{must(x,"COMPLETE_RETRAINING_CHECK");repo.markRetrainingChecked(a.tenantId(),id,a.employeeId());repo.appendEvidence(a.tenantId(),id,"RETRAINING_CHECK",a.employeeId(),null,null,null,c.note(),null);advance(a,required(a.tenantId(),id),"S09",x,scope(key,"workflow"),c.note());}
                case "S10"->{must(x,"ARCHIVE");repo.markArchived(a.tenantId(),id,a.employeeId());advance(a,required(a.tenantId(),id),"S10",x,scope(key,"workflow"),c.note());}
                default->throw reject("action not allowed from current node");
            }
            emit(a,id,x);return aggregate(required(a.tenantId(),id));});
    }

    private void start(DatabaseSecurityContext a,LearningRecord r,String key,String note){if(r.workflowInstanceId()!=null)throw reject("workflow already started");if(r.ownerCenterId()==null||r.ownerEmployeeId()==null)throw reject("assignment owner center/employee missing");UUID version=repo.workflowVersion(a.tenantId()).orElseThrow(()->reject("workflow not published"));FormRef f=repo.form(a.tenantId()).orElseThrow(()->reject("form not published"));List<UUID> managers=repo.permissionCandidates(a.tenantId(),MANAGE,r.ownerCenterId());List<UUID> certifiers=repo.permissionCandidates(a.tenantId(),CERTIFY,r.ownerCenterId());if(managers.isEmpty()||certifiers.isEmpty())throw reject("manager/certifier candidates missing");ObjectNode ctx=mapper.createObjectNode();ctx.put("ownerCenterId",r.ownerCenterId().toString());ctx.set("targetEmployeeIds",uuidArray(List.of(r.ownerEmployeeId())));ctx.set("managerCandidateIds",uuidArray(managers));ctx.set("certifierCandidateIds",uuidArray(certifiers));var s=workflow.start(new WorkflowRuntimeService.StartCommand(a.tenantId(),a.employeeId(),a.identityId(),version,"learning.learning_assignment",r.id(),r.businessNo(),r.subject(),"NORMAL",ctx,scope(key,"start")));forms.submit(new WorkflowFormService.SubmitForm(a.tenantId(),a.employeeId(),a.identityId(),s.instance().id(),null,f.id(),f.versionNo(),List.of(text("course_version_id",r.courseVersionId()),text("content_version",r.contentVersion()),text("period_or_course_no",r.periodOrCourseNo()),text("owner_employee_id",r.ownerEmployeeId().toString())),scope(key,"form")));var moved=workflow.act(new WorkflowRuntimeService.ActionCommand(a.tenantId(),a.employeeId(),a.identityId(),s.instance().id(),null,"S01","PUBLISH_CONTENT",note,scope(key,"publish")));if(repo.bindWorkflow(a.tenantId(),r.id(),r.versionNo(),moved.instance().id(),"S02",label("S02"),a.employeeId())!=1)throw reject("concurrent publish conflict");}
    private void advance(DatabaseSecurityContext a,LearningRecord r,String source,String action,String key,String note){var runtime=workflow.get(a.tenantId(),r.workflowInstanceId());if(!source.equals(runtime.instance().currentNodeCode())||!source.equals(r.currentNodeCode()))throw reject("stale workflow projection");if(runtime.task()==null)throw reject("workflow task missing");tasks.claim(new WorkflowTaskAssignmentService.ClaimCommand(a.tenantId(),runtime.task().id(),a.employeeId()));var moved=workflow.act(new WorkflowRuntimeService.ActionCommand(a.tenantId(),a.employeeId(),a.identityId(),r.workflowInstanceId(),runtime.task().id(),source,action,note,key));Instant closed="END".equals(moved.instance().currentNodeCode())?moved.instance().finishedAt():null;if(repo.moveNode(a.tenantId(),r.id(),r.versionNo(),moved.instance().currentNodeCode(),label(moved.instance().currentNodeCode()),closed,a.employeeId())!=1)throw reject("concurrent transition conflict");}
    private Aggregate aggregate(LearningRecord r){return new Aggregate(r,repo.evidence(r.tenantId(),r.id()));} private LearningRecord required(UUID t,UUID id){return repo.find(t,id).orElseThrow(()->reject("assignment not found"));}
    private boolean claim(DatabaseSecurityContext a,String key,String hash,String type,UUID id){return idempotency.claim(a.tenantId(),a.employeeId(),key,hash,"learning.learning_assignment."+type,id,IDEMPOTENCY_TTL).existing();}
    private void emit(DatabaseSecurityContext a,UUID id,String event){LearningRecord r=required(a.tenantId(),id);ObjectNode p=mapper.createObjectNode();p.put("assignmentId",id.toString());p.put("businessNo",r.businessNo());p.put("event",event);p.put("nodeCode",r.currentNodeCode());outbox.enqueue(new TransactionalOutboxService.Command(a.tenantId(),a.employeeId(),"P010_LEARNING",id,"P010_LEARNING_EVENT",1,json(p),"p010:"+id+":"+r.versionNo()));}
    private static void actor(DatabaseSecurityContext a){if(a==null||a.tenantId()==null||a.employeeId()==null||a.identityId()==null||a.userId()==null||a.orgId()==null||a.positionId()==null)throw reject("authenticated employee context required");} private static void self(DatabaseSecurityContext a,LearningRecord r){if(!a.employeeId().equals(r.ownerEmployeeId()))throw reject("employee action is self-only");} private static void node(LearningRecord r,String n){if(!n.equals(r.currentNodeCode()))throw reject("operation not allowed from current node");}
    private static String practical(String v){if(v==null||!List.of("通过","补训","不通过","不适用").contains(v.trim()))throw reject("practical result invalid");return v.trim();}private static String safe(String v){if(v==null)return"INVALID";String x=v.trim().toUpperCase(Locale.ROOT);return x.matches("[A-Z0-9_]{1,40}")?x:"INVALID";}private static void must(String a,String e){if(!e.equals(a))throw reject("action not allowed from current node");}private static ProcessRejectedException reject(String m){return new ProcessRejectedException("P010 "+m);}private static String scope(String k,String s){if(k==null||k.isBlank())throw reject("idempotency key required");String x=k+":"+s;if(x.length()>128)throw reject("idempotency key too long");return x;}
    private static WorkflowFormService.FieldValue text(String c,String v){return new WorkflowFormService.FieldValue(c,"TEXT",v,null,null,null,null,null,"P1",false);}private ArrayNode uuidArray(List<UUID> ids){ArrayNode a=mapper.createArrayNode();ids.stream().filter(Objects::nonNull).distinct().forEach(x->a.add(x.toString()));return a;}private String json(JsonNode n){try{return mapper.writeValueAsString(n);}catch(JsonProcessingException e){throw reject("JSON serialization failed");}}private JsonNode jsonDates(LocalDate a,LocalDate b){ObjectNode n=mapper.createObjectNode();n.put("effectiveDate",a.toString());if(b!=null)n.put("expireDate",b.toString());return n;}private JsonNode jsonRoles(List<UUID> roles){ObjectNode n=mapper.createObjectNode();ArrayNode a=n.putArray("roleIds");roles.forEach(x->a.add(x.toString()));return n;}
    public static String label(String n){return switch(n){case"S01"->"课程/制度版本发布";case"S02"->"按岗位风险指派";case"S03"->"员工学习";case"S04"->"1000分制考试";case"S05"->"线下实操";case"S06"->"主管/专业人员认证";case"S07"->"资格生效";case"S08"->"岗位权限联动";case"S09"->"到期复训/复证";case"S10"->"归档";case"END"->"已关闭";default->throw reject("unknown node "+n);};}

    public interface Repository {Optional<UUID> workflowVersion(UUID t);Optional<FormRef> form(UUID t);List<UUID> permissionCandidates(UUID t,String p,UUID org);Optional<LearningRecord> find(UUID t,UUID id);List<LearningRecord> list(UUID t);List<Evidence> evidence(UUID t,UUID id);int bindWorkflow(UUID t,UUID id,int v,UUID wf,String node,String status,UUID actor);int moveNode(UUID t,UUID id,int v,String node,String status,Instant closed,UUID actor);void appendEvidence(UUID t,UUID id,String type,UUID actor,Long score,BigDecimal progress,String practical,String text,JsonNode json);int updateProgress(UUID t,UUID id,BigDecimal p,UUID actor);int markLearningCompleted(UUID t,UUID id,UUID actor);int updateExam(UUID t,UUID id,long score,UUID actor);int updatePractical(UUID t,UUID id,String result,UUID actor);int markContentPublished(UUID t,UUID id,UUID actor);int markRiskAssigned(UUID t,UUID id,UUID actor);int markCertified(UUID t,UUID id,UUID actor);int activateQualification(UUID t,UUID id,LocalDate effective,LocalDate expire,UUID actor);List<UUID> linkPermissions(UUID t,UUID id,UUID actor);int markPermissionLinked(UUID t,UUID id,UUID actor);int markRetrainingChecked(UUID t,UUID id,UUID actor);int markArchived(UUID t,UUID id,UUID actor);}
    public record FormRef(UUID id,int versionNo){} public record ProgressCommand(BigDecimal completionRate,String note){} public record ExamCommand(long score1000,String note){} public record PracticalCommand(String result,String note){} public record ActionCommand(int expectedVersion,String note,LocalDate effectiveDate,LocalDate expireDate){}
    public record LearningRecord(UUID id,UUID tenantId,String businessNo,UUID workflowInstanceId,String workflowInstanceNo,String currentNodeCode,String status,int versionNo,String subject,UUID ownerCenterId,UUID ownerEmployeeId,String contentVersion,String courseVersionId,String periodOrCourseNo,BigDecimal completionRate,Long score1000,String practicalResult,LocalDate qualificationEffectiveDate,LocalDate qualificationExpireDate,Instant certifiedAt,UUID certifiedBy,Instant permissionLinkedAt,Instant archivedAt,Instant updatedAt){}
    public record Evidence(UUID id,String evidenceType,UUID actorEmployeeId,Long score1000,BigDecimal completionRate,String practicalResult,String evidenceText,JsonNode evidenceJson,Instant createdAt){} public record Aggregate(LearningRecord record,List<Evidence> evidence){public Aggregate metadataOnly(){LearningRecord r=record;return new Aggregate(new LearningRecord(r.id(),r.tenantId(),r.businessNo(),r.workflowInstanceId(),r.workflowInstanceNo(),r.currentNodeCode(),r.status(),r.versionNo(),null,r.ownerCenterId(),null,r.contentVersion(),r.courseVersionId(),r.periodOrCourseNo(),null,null,null,null,r.qualificationExpireDate(),null,null,r.permissionLinkedAt(),r.archivedAt(),r.updatedAt()),List.of());}}
}
