from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[2]


def read(path: str) -> str:
    target = ROOT / path
    if not target.is_file():
        raise SystemExit(f"missing required P016 reuse-review file: {path}")
    return target.read_text(encoding="utf-8")


workflow = json.loads(read("docs/implementation/phases/PHASE-11/PHASE11_WORKFLOW_CONTRACT.json"))
http = json.loads(read("docs/implementation/phases/PHASE-11/PHASE11_HTTP_PERMISSION_CONTRACT.json"))
pages = json.loads(read("docs/implementation/phases/PHASE-11/PHASE11_PAGE_BINDINGS.json"))
db_contract = read("docs/implementation/phases/PHASE-11/DATABASE_CONTRACT.md")
decisions = read("docs/implementation/contracts/phase-11/C0_DECISION_LOG.md")
progress = read("docs/implementation/MASTER_PROGRESS.md")
review = read("docs/implementation/phases/PHASE-11/P016_REUSE_REVIEW.md")

expected_nodes = ["S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "END"]
expected_actions = [
    "REGISTER_CARE_CASE",
    "VERIFY_ELIGIBILITY",
    "AUTHORIZE_PRIVACY",
    "APPROVE_CARE",
    "EXECUTE_BENEFIT",
    "CONFIRM_RECEIPT",
    "RECONCILE",
    "ARCHIVE",
]
p016 = workflow.get("processes", {}).get("P016")
if not p016:
    raise SystemExit("P016 workflow contract is missing")
if p016.get("nodes") != expected_nodes:
    raise SystemExit(f"P016 node order drifted: {p016.get('nodes')}")
actual_actions = [item.get("action") for item in p016.get("transitions", [])]
if actual_actions != expected_actions:
    raise SystemExit(f"P016 action order drifted: {actual_actions}")
if p016.get("form_codes", {}).get("initial") != "EMP-P016-F01":
    raise SystemExit("P016 initial form must remain EMP-P016-F01")

p016_http = http.get("processes", {}).get("P016", {})
if p016_http.get("base") != "/api/v1/processes/P016/care-cases":
    raise SystemExit("P016 API base drifted")
expected_permissions = [
    "p016.care.create",
    "p016.care.read",
    "p016.care.review",
    "p016.care.execute",
    "p016.care.confirm",
    "p016.care.reconcile",
    "p016.care.monitor",
]
if p016_http.get("permissions") != expected_permissions:
    raise SystemExit(f"P016 permission contract drifted: {p016_http.get('permissions')}")

bindings = {
    item.get("portal"): item
    for item in pages.get("bindings", [])
    if item.get("process_code") == "P016"
}
expected_routes = {
    "employee": ("/employee/03/06/05", "SELF"),
    "center": ("/center/06/03/09", "CENTER"),
    "tech": ("/tech/01/11/04", "METADATA_ONLY"),
}
for portal, (route, scope) in expected_routes.items():
    item = bindings.get(portal)
    if not item or item.get("route_path") != route or item.get("data_scope") != scope:
        raise SystemExit(f"P016 {portal} page binding drifted: {item}")

for token in (
    "P016 | `welfare.care_case` | V127",
    "复用旧主表",
    "资格、隐私授权、执行、员工确认和对账事实独立留痕",
):
    if token not in db_contract:
        raise SystemExit(f"P016 database contract drifted: {token}")
for token in (
    "C0-08",
    "复用 `welfare.care_case`",
    "不建立第二真相源",
    "财务/服务能力不可用时 fail-closed",
):
    if token not in decisions:
        raise SystemExit(f"P016 C0 decision missing: {token}")

v44 = read("technical-platform/database/flyway/oms/V44__welfare_tables.sql")
for token in (
    "GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY",
    "source_sha256: cb8339c93a0fb006b687f082845f78b481d2526bc85a691b43e10d36faa28c04",
    "CREATE TABLE IF NOT EXISTS welfare.care_case",
    "流程动作、动态字段和附件分别落公共子表",
    "workflow_instance_id uuid",
    "version_no integer DEFAULT 0 NOT NULL",
):
    if token not in v44:
        raise SystemExit(f"V44 welfare canonical table drifted: {token}")

care_service = read(
    "technical-platform/backend/modules/welfare/src/main/java/cn/shangjingu/platform/welfare/CareCaseService.java"
)
for token in (
    'PROCESS_CODE = "P016"',
    "TenantTransactionRunner",
    "IdempotencyRegistry",
    "BusinessNumberService",
    "benefit amount must be non-negative",
    "welfare finance capability is unavailable or ambiguous",
    "validateInvoiceEvidence",
):
    if token not in care_service:
        raise SystemExit(f"PHASE-05 CareCase kernel capability missing: {token}")

repo = read(
    "technical-platform/backend/modules/welfare/src/main/java/cn/shangjingu/platform/welfare/JdbcCareCaseRepository.java"
)
for token in (
    "insert into welfare.care_case",
    "where tenant_id=? and id=?",
    "version_no=version_no+1",
    "and version_no=?",
):
    if token not in repo:
        raise SystemExit(f"PHASE-05 welfare repository reuse invariant missing: {token}")

legacy_controller = read(
    "technical-platform/backend/apps/api/src/main/java/cn/shangjingu/platform/api/phase05/WelfareCareCaseController.java"
)
for token in (
    '/api/v1/phase05/welfare/care-cases',
    "phase05.p016.read",
    "phase05.p016.write",
):
    if token not in legacy_controller:
        raise SystemExit(f"legacy PHASE-05 compatibility surface drifted: {token}")

for token in (
    "welfare.care_case` 稳定业务事实主表",
    "客户端 target status",
    "P017+ | LOCKED",
):
    if token not in review:
        raise SystemExit(f"P016 reuse review is incomplete: {token}")

process = read(
    "technical-platform/backend/modules/workflow/src/main/java/cn/shangjingu/platform/workflow/phase11/Phase11Process.java"
)
construction_authorized = "P016_CONSTRUCTION_AUTHORIZED" in progress or "P016 = CHECKPOINT_PASS / CLOSED" in progress
if not construction_authorized:
    if re.search(r"\bP016\s*\(", process):
        raise SystemExit("P016 executable process introduced before reuse-review authorization")
    premature_paths = [
        "technical-platform/database/flyway-overlays/oms/V127__phase11_p016_welfare.sql",
        "technical-platform/backend/apps/api/src/main/java/cn/shangjingu/platform/api/phase11/P016CareCaseController.java",
        "technical-platform/web/src/router/p016-route-specs.ts",
    ]
    for path in premature_paths:
        if (ROOT / path).exists():
            raise SystemExit(f"P016 production construction started before reuse-review gate: {path}")
    if "requestedStatus" not in legacy_controller or "requestedStatus" not in care_service:
        raise SystemExit("reuse review expected the legacy target-status gap to remain visible before construction")

if re.search(r"\bP0(17|18|19|20)\s*\(", process):
    raise SystemExit("P017+ executable process introduced while PHASE-12 remains locked")

v127 = ROOT / "technical-platform/database/flyway-overlays/oms/V127__phase11_p016_welfare.sql"
if v127.exists():
    migration = v127.read_text(encoding="utf-8")
    if re.search(r"create\s+table\s+(if\s+not\s+exists\s+)?welfare\.care_case\b", migration, re.I):
        raise SystemExit("V127 must not recreate the canonical welfare.care_case table")
    if re.search(r"create\s+table\s+[^;]*(care_case_v2|phase11_care_case|p016_case|care_case_shadow)", migration, re.I):
        raise SystemExit("P016 shadow primary table is forbidden")

print("PHASE11_P016_REUSE_REVIEW_OK")
