package cn.shangjingu.platform.database;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.UUID;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;

class Phase11P012DatabaseIT {
    private static final UUID TENANT=id("00000000-0000-0000-0000-000000001012"),OTHER=id("00000000-0000-0000-0000-000000009012"),CENTER=id("11000000-0000-0000-0000-000000001012"),OTHER_CENTER=id("11000000-0000-0000-0000-000000009012"),OLD_POSITION=id("12000000-0000-0000-0000-000000001012"),NEW_POSITION=id("12000000-0000-0000-0000-000000001013"),OTHER_POSITION=id("12000000-0000-0000-0000-000000009012"),OWNER=id("10000000-0000-0000-0000-000000001012"),ACTOR=id("10000000-0000-0000-0000-000000001013"),OTHER_EMPLOYEE=id("10000000-0000-0000-0000-000000009012"),OLD_APPOINTMENT=id("13000000-0000-0000-0000-000000001012"),OTHER_APPOINTMENT=id("13000000-0000-0000-0000-000000009012"),REQUEST=id("20000000-0000-0000-0000-000000001012"),EVENT=id("21000000-0000-0000-0000-000000001012"),EXECUTION=id("22000000-0000-0000-0000-000000001012");
    private static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:16.14-alpine3.24").withDatabaseName("postgres").withUsername("postgres").withPassword("phase11-p012-bootstrap");private static String omsUrl;
    @BeforeAll static void migrate()throws Exception{POSTGRES.start();Path root=root();Flyway.configure().dataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/cluster")).cleanDisabled(true).load().migrate();try(Connection c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword());Statement s=c.createStatement()){s.execute("create database sjg_oms");}omsUrl="jdbc:postgresql://"+POSTGRES.getHost()+":"+POSTGRES.getMappedPort(5432)+"/sjg_oms";Flyway f=Flyway.configure().dataSource(omsUrl,POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/oms"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/oms")).placeholders(Map.of("sjg_tenant_id",TENANT.toString(),"sjg_tenant_code","PHASE11_P012","sjg_tenant_name","P012 database test")).cleanDisabled(true).load();assertTrue(f.migrate().success);f.validate();assertEquals(0,f.migrate().migrationsExecuted);seed();}
    @AfterAll static void stop(){POSTGRES.stop();}
    @Test void migrationPublishesExactWorkflowFormPermissionsAndRuntimeGrants()throws Exception{try(Connection c=connection();Statement s=c.createStatement()){assertEquals(1,scalar(s,"select count(*) from flyway_schema_history where version='121' and success"));assertEquals(6,scalar(s,"select count(*) from iam.permission where tenant_id='"+TENANT+"' and permission_code like 'p012.promotion.%' and not is_deleted"));assertEquals(11,scalar(s,workflowCount("wf_node")));assertEquals(12,scalar(s,workflowCount("wf_transition")));assertEquals(1,scalar(s,"select count(*) from workflow.wf_form_definition where tenant_id='"+TENANT+"' and form_code='EMP-P012-F01' and validation_schema->'guards' ? 'approval-not-effective' and not is_deleted"));assertEquals(2,scalar(s,"select count(distinct table_name) from information_schema.role_table_grants where grantee='sjg_api_runtime' and table_schema='hr' and table_name in ('promotion_request_event','promotion_appointment_execution') and privilege_type='INSERT'"));assertEquals(0,scalar(s,"select count(*) from information_schema.role_table_grants where grantee in ('sjg_api_runtime','sjg_worker_runtime') and table_schema='hr' and table_name in ('promotion_request_event','promotion_appointment_execution') and privilege_type in ('UPDATE','DELETE','TRUNCATE')"));}}
    @Test void assessmentProjectionIsBoundedAndFactsAreAppendOnly(){assertSqlState("23514","update hr.promotion_request set score_1000=1001 where id='"+REQUEST+"'");assertSqlState("55000","update hr.promotion_request_event set event_type='TAMPER' where id='"+EVENT+"'");assertSqlState("55000","delete from hr.promotion_appointment_execution where id='"+EXECUTION+"'");}
    @Test void crossTenantActorAndAppointmentReferencesAreRejected(){assertSqlState("23514","insert into hr.promotion_request_event(tenant_id,request_id,event_seq,event_type,evidence,actor_employee_id) values ('"+TENANT+"','"+REQUEST+"',2,'TAMPER','{}','"+OTHER_EMPLOYEE+"')");assertSqlState("23514","insert into hr.promotion_appointment_execution(tenant_id,request_id,execution_type,target_position_id,previous_appointment_id,new_appointment_id,effective_date,external_reference,evidence,executed_by) values ('"+TENANT+"','"+REQUEST+"','EFFECTIVE','"+NEW_POSITION+"','"+OTHER_APPOINTMENT+"','"+OLD_APPOINTMENT+"',current_date,'P012-XTENANT','{}','"+ACTOR+"')");}
    private static void seed()throws Exception{try(Connection c=connection();Statement s=c.createStatement()){s.execute("insert into core.tenant(id,tenant_code,tenant_name,status) values ('"+OTHER+"','P012_OTHER','P012 Other','ACTIVE')");s.execute("insert into org.organization(id,tenant_id,org_code,org_name,org_type,path,status) values ('"+CENTER+"','"+TENANT+"','P012_CENTER','P012 Center','CENTER','p012_center'::ltree,'ACTIVE'),('"+OTHER_CENTER+"','"+OTHER+"','P012_OTHER','P012 Other','CENTER','p012_other'::ltree,'ACTIVE')");s.execute("insert into org.position(id,tenant_id,position_code,position_name,org_id,status) values ('"+OLD_POSITION+"','"+TENANT+"','P012_OLD','P012 Old','"+CENTER+"','ACTIVE'),('"+NEW_POSITION+"','"+TENANT+"','P012_NEW','P012 New','"+CENTER+"','ACTIVE'),('"+OTHER_POSITION+"','"+OTHER+"','P012_OTHER','P012 Other','"+OTHER_CENTER+"','ACTIVE')");s.execute("insert into org.employee(id,tenant_id,employee_no,person_name,employment_status,hire_date,primary_org_id,primary_position_id) values ('"+OWNER+"','"+TENANT+"','P012-E01','P012 Owner','ACTIVE',current_date-90,'"+CENTER+"','"+OLD_POSITION+"'),('"+ACTOR+"','"+TENANT+"','P012-E02','P012 Actor','ACTIVE',current_date-90,'"+CENTER+"','"+OLD_POSITION+"'),('"+OTHER_EMPLOYEE+"','"+OTHER+"','P012-X01','P012 Other','ACTIVE',current_date-90,'"+OTHER_CENTER+"','"+OTHER_POSITION+"')");s.execute("insert into org.employee_position(id,tenant_id,employee_id,position_id,org_id,is_primary,effective_start_date,status) values ('"+OLD_APPOINTMENT+"','"+TENANT+"','"+OWNER+"','"+OLD_POSITION+"','"+CENTER+"',true,current_date-90,'ACTIVE'),('"+OTHER_APPOINTMENT+"','"+OTHER+"','"+OTHER_EMPLOYEE+"','"+OTHER_POSITION+"','"+OTHER_CENTER+"',true,current_date-90,'ACTIVE')");s.execute("insert into hr.promotion_request(id,tenant_id,business_no,status,created_by,updated_by,source_channel,business_date,subject,priority,risk_level,owner_center_id,owner_employee_id,employment_type,period_or_course_no,person_name,person_no,planned_effective_date,target_job_id,score_1000) values ('"+REQUEST+"','"+TENANT+"','P012-DB-1','Approval','"+ACTOR+"','"+ACTOR+"','PORTAL',current_date,'P012 promotion request','NORMAL','CRITICAL','"+CENTER+"','"+OWNER+"','FULL_TIME','2026-H2','P012 Owner','P012-E01',current_date+30,'P012_NEW',900)");s.execute("insert into hr.promotion_request_event(id,tenant_id,request_id,event_seq,event_type,evidence,actor_employee_id) values ('"+EVENT+"','"+TENANT+"','"+REQUEST+"',1,'APPROVE','{}','"+ACTOR+"')");s.execute("insert into hr.promotion_appointment_execution(id,tenant_id,request_id,execution_type,target_position_id,effective_date,salary_confirmation_reference,external_reference,evidence,executed_by) values ('"+EXECUTION+"','"+TENANT+"','"+REQUEST+"','CONFIRMED','"+NEW_POSITION+"',current_date+30,'SALARY-AUTH-001','APPOINTMENT-001','{}','"+ACTOR+"')");}}
    private static void assertSqlState(String expected,String sql){SQLException e=assertThrows(SQLException.class,()->{try(Connection c=connection();Statement s=c.createStatement()){s.execute(sql);}});assertEquals(expected,e.getSQLState());}private static String workflowCount(String table){return "select count(*) from workflow."+table+" x join workflow.wf_version v on v.id=x.version_id and v.tenant_id=x.tenant_id join workflow.wf_definition d on d.id=v.definition_id and d.tenant_id=v.tenant_id where d.process_code='P012' and v.status='PUBLISHED' and x.tenant_id='"+TENANT+"' and not x.is_deleted";}private static long scalar(Statement s,String sql)throws SQLException{try(var r=s.executeQuery(sql)){r.next();return r.getLong(1);}}private static Connection connection()throws SQLException{return DriverManager.getConnection(omsUrl,POSTGRES.getUsername(),POSTGRES.getPassword());}private static UUID id(String value){return UUID.fromString(value);}private static Path root(){Path p=Path.of("").toAbsolutePath();while(p!=null){if(Files.exists(p.resolve("AGENT.md")))return p;p=p.getParent();}throw new IllegalStateException("repository root not found");}
}
