package cn.shangjingu.platform.database;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.UUID;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;

class Phase10P007DatabaseIT {
    private static final UUID TENANT=UUID.fromString("00000000-0000-0000-0000-000000001007"),ACTOR=UUID.fromString("10000000-0000-0000-0000-000000001007"),ORG=UUID.fromString("11000000-0000-0000-0000-000000001007"),POSITION=UUID.fromString("12000000-0000-0000-0000-000000001007"),REQUEST=UUID.fromString("20000000-0000-0000-0000-000000001007");
    private static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:16.14-alpine3.24").withDatabaseName("postgres").withUsername("postgres").withPassword("phase10-p007-bootstrap");private static String omsUrl;
    @BeforeAll static void migrate()throws Exception{POSTGRES.start();Path root=root();Flyway.configure().dataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/cluster")).cleanDisabled(true).load().migrate();try(Connection c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword());Statement s=c.createStatement()){s.execute("create database sjg_oms");}omsUrl="jdbc:postgresql://"+POSTGRES.getHost()+":"+POSTGRES.getMappedPort(5432)+"/sjg_oms";Flyway f=Flyway.configure().dataSource(omsUrl,POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/oms"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/oms")).placeholders(Map.of("sjg_tenant_id",TENANT.toString(),"sjg_tenant_code","PHASE10_P007","sjg_tenant_name","P007 database test")).cleanDisabled(true).load();assertTrue(f.migrate().success);f.validate();assertEquals(0,f.migrate().migrationsExecuted);try(Connection c=connection();Statement s=c.createStatement()){s.execute("insert into org.organization(id,tenant_id,org_code,org_name,org_type,path,status) values ('"+ORG+"','"+TENANT+"','P007_CENTER','P007 Center','CENTER','p007_center'::ltree,'ACTIVE')");s.execute("insert into org.position(id,tenant_id,position_code,position_name,org_id,status) values ('"+POSITION+"','"+TENANT+"','P007_POS','P007 Position','"+ORG+"','ACTIVE')");s.execute("insert into org.employee(id,tenant_id,employee_no,person_name,employment_status,hire_date,primary_org_id,primary_position_id) values ('"+ACTOR+"','"+TENANT+"','P007-E001','P007 Actor','ACTIVE',current_date-30,'"+ORG+"','"+POSITION+"')");}}
    @AfterAll static void stop(){POSTGRES.stop();}
    @Test void migrationPublishesExactWorkflowFormPermissionsAndSequence()throws Exception{try(Connection c=connection();Statement s=c.createStatement()){assertEquals(1,scalar(s,"select count(*) from core.sequence_rule where tenant_id='"+TENANT+"' and rule_code='P007' and not is_deleted"));assertEquals(5,scalar(s,"select count(*) from iam.permission where tenant_id='"+TENANT+"' and permission_code like 'p007.schedule.%' and not is_deleted"));assertEquals(10,scalar(s,workflowCount("wf_node")));assertEquals(15,scalar(s,workflowCount("wf_transition")));assertEquals(1,scalar(s,"select count(*) from workflow.wf_form_definition where tenant_id='"+TENANT+"' and form_code='CTR-P007-F01' and field_schema#>>'{properties,duration_hours,maximum}'='12' and not is_deleted"));}}
    @Test void canonicalAggregateUsesOptimisticVersionAndImmutableSnapshots()throws Exception{try(Connection c=connection();Statement s=c.createStatement()){s.execute("""
            insert into attendance.shift_change_request(id,tenant_id,business_no,status,version_no,created_by,updated_by,source_channel,business_date,subject,reason,priority,owner_center_id,owner_employee_id,planned_start_at,planned_finish_at,attendance_type,change_action,change_reason,content_version,duration_hours,end_at,period_or_course_no,start_at)
            values ('%s','%s','P007-DB-1','业务量与活动需求输入',0,'%s','%s','TEST',current_date,'真实排班计划','这是数据库集成测试排班原因','NORMAL','%s','%s',now()+interval '1 day',now()+interval '9 hours 1 day','排班','制定','业务量需求','V1',8,now()+interval '9 hours 1 day','PERIOD-1',now()+interval '1 day')
            """.formatted(REQUEST,TENANT,ACTOR,ACTOR,ORG,ACTOR));assertEquals(1,s.executeUpdate("update attendance.shift_change_request set status='班次模板匹配',version_no=version_no+1 where tenant_id='"+TENANT+"' and id='"+REQUEST+"' and version_no=0"));assertEquals(0,s.executeUpdate("update attendance.shift_change_request set status='非法并发覆盖' where tenant_id='"+TENANT+"' and id='"+REQUEST+"' and version_no=0"));s.execute("insert into attendance.shift_change_request_item(id,tenant_id,created_by,updated_by,master_id,field_code,item_seq,item_name,item_value_json) values (gen_random_uuid(),'"+TENANT+"','"+ACTOR+"','"+ACTOR+"','"+REQUEST+"','after_snapshot',1,'变更后快照','{\"startAt\":\"2030-01-01T08:00:00Z\"}'::jsonb)");}
        SQLException update=assertThrows(SQLException.class,()->{try(Connection c=connection();Statement s=c.createStatement()){s.executeUpdate("update attendance.shift_change_request_item set item_name='tampered' where tenant_id='"+TENANT+"' and master_id='"+REQUEST+"' and field_code='after_snapshot'");}});assertEquals("55000",update.getSQLState());SQLException delete=assertThrows(SQLException.class,()->{try(Connection c=connection();Statement s=c.createStatement()){s.executeUpdate("delete from attendance.shift_change_request_item where tenant_id='"+TENANT+"' and master_id='"+REQUEST+"' and field_code='after_snapshot'");}});assertEquals("55000",delete.getSQLState());}
    private static String workflowCount(String table){return "select count(*) from workflow."+table+" x join workflow.wf_version v on v.id=x.version_id and v.tenant_id=x.tenant_id join workflow.wf_definition d on d.id=v.definition_id and d.tenant_id=v.tenant_id where d.process_code='P007' and v.status='PUBLISHED' and x.tenant_id='"+TENANT+"' and not x.is_deleted";}private static long scalar(Statement s,String sql)throws SQLException{try(var r=s.executeQuery(sql)){r.next();return r.getLong(1);}}private static Connection connection()throws SQLException{return DriverManager.getConnection(omsUrl,POSTGRES.getUsername(),POSTGRES.getPassword());}private static Path root(){Path p=Path.of("").toAbsolutePath();while(p!=null){if(Files.exists(p.resolve("mvnw")))return p;p=p.getParent();}throw new IllegalStateException("repository root not found");}
}
