package cn.shangjingu.platform.database;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.UUID;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;

class Phase11P011DatabaseIT {
    private static final UUID TENANT=UUID.fromString("00000000-0000-0000-0000-000000001011"),EMPLOYEE=UUID.fromString("10000000-0000-0000-0000-000000001011"),REVIEWER=UUID.fromString("10000000-0000-0000-0000-000000001012"),CENTER=UUID.fromString("11000000-0000-0000-0000-000000001011"),POSITION=UUID.fromString("12000000-0000-0000-0000-000000001011"),CYCLE=UUID.fromString("20000000-0000-0000-0000-000000001011"),CYCLE2=UUID.fromString("20000000-0000-0000-0000-000000001012"),SCORE=UUID.fromString("21000000-0000-0000-0000-000000001011"),EVENT=UUID.fromString("22000000-0000-0000-0000-000000001011"),EFFECT=UUID.fromString("23000000-0000-0000-0000-000000001011");
    private static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:16.14-alpine3.24").withDatabaseName("postgres").withUsername("postgres").withPassword("phase11-p011-bootstrap");private static String omsUrl;
    @BeforeAll static void migrate()throws Exception{POSTGRES.start();Path root=root();Flyway.configure().dataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/cluster")).cleanDisabled(true).load().migrate();try(Connection c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword());Statement s=c.createStatement()){s.execute("create database sjg_oms");}omsUrl="jdbc:postgresql://"+POSTGRES.getHost()+":"+POSTGRES.getMappedPort(5432)+"/sjg_oms";Flyway f=Flyway.configure().dataSource(omsUrl,POSTGRES.getUsername(),POSTGRES.getPassword()).locations("filesystem:"+root.resolve("technical-platform/database/flyway/oms"),"filesystem:"+root.resolve("technical-platform/database/flyway-overlays/oms")).placeholders(Map.of("sjg_tenant_id",TENANT.toString(),"sjg_tenant_code","PHASE11_P011","sjg_tenant_name","P011 database test")).cleanDisabled(true).load();assertTrue(f.migrate().success);f.validate();assertEquals(0,f.migrate().migrationsExecuted);seed();}
    @AfterAll static void stop(){POSTGRES.stop();}
    @Test void migrationPublishesSourceWorkflowFormPermissionsAndRuntimeGrants()throws Exception{try(Connection c=connection();Statement s=c.createStatement()){assertEquals(1,scalar(s,"select count(*) from core.sequence_rule where tenant_id='"+TENANT+"' and rule_code='P011' and not is_deleted"));assertEquals(7,scalar(s,"select count(*) from iam.permission where tenant_id='"+TENANT+"' and permission_code like 'p011.performance.%' and not is_deleted"));assertEquals(12,scalar(s,workflowCount("wf_node")));assertEquals(13,scalar(s,workflowCount("wf_transition")));assertEquals(1,scalar(s,"select count(*) from workflow.wf_form_definition where tenant_id='"+TENANT+"' and form_code='CTR-P011-F01' and validation_schema->'guards' ? 'score-type-independent' and not is_deleted"));assertEquals(3,scalar(s,"select count(distinct table_name) from information_schema.role_table_grants where grantee='sjg_api_runtime' and table_schema='performance' and table_name in ('performance_score_fact','performance_cycle_event','performance_effect_execution') and privilege_type='INSERT'"));assertEquals(0,scalar(s,"select count(*) from information_schema.role_table_grants where grantee in ('sjg_api_runtime','sjg_worker_runtime') and table_schema='performance' and table_name in ('performance_score_fact','performance_cycle_event','performance_effect_execution') and privilege_type in ('UPDATE','DELETE','TRUNCATE')"));}}
    @Test void scoreTypesRemainIndependentAndBounded()throws Exception{try(Connection c=connection();Statement s=c.createStatement()){s.execute("insert into performance.performance_score_fact(tenant_id,cycle_id,score_seq,score_type,score_1000,evidence,actor_employee_id) values ('"+TENANT+"','"+CYCLE+"',2,'SUPERVISOR',820,'{}','"+REVIEWER+"'),('"+TENANT+"','"+CYCLE+"',3,'SYSTEM_CALCULATED',810,'{}','"+REVIEWER+"'),('"+TENANT+"','"+CYCLE+"',4,'CALIBRATED',815,'{}','"+REVIEWER+"')");assertEquals(4,scalar(s,"select count(distinct score_type) from performance.performance_score_fact where tenant_id='"+TENANT+"' and cycle_id='"+CYCLE+"'"));assertSqlState("23505","insert into performance.performance_score_fact(tenant_id,cycle_id,score_seq,score_type,score_1000,evidence,actor_employee_id) values ('"+TENANT+"','"+CYCLE+"',5,'EMPLOYEE_SELF',700,'{}','"+EMPLOYEE+"')");assertSqlState("23514","insert into performance.performance_score_fact(tenant_id,cycle_id,score_seq,score_type,score_1000,evidence,actor_employee_id) values ('"+TENANT+"','"+CYCLE2+"',1,'SUPERVISOR',1001,'{}','"+REVIEWER+"')");}}
    @Test void scoreEventAndEffectFactsAreAppendOnly(){assertSqlState("55000","update performance.performance_score_fact set score_1000=1 where id='"+SCORE+"'");assertSqlState("55000","delete from performance.performance_cycle_event where id='"+EVENT+"'");assertSqlState("55000","update performance.performance_effect_execution set external_reference='TAMPER' where id='"+EFFECT+"'");}
    @Test void crossTenantFactsAreRejected(){String other="00000000-0000-0000-0000-000000009999";assertSqlState("23514","insert into performance.performance_cycle_event(tenant_id,cycle_id,event_seq,event_type,evidence,actor_employee_id) values ('"+other+"','"+CYCLE+"',2,'TAMPER','{}','"+EMPLOYEE+"')");assertSqlState("23514","insert into performance.performance_effect_execution(tenant_id,cycle_id,execution_type,external_reference,evidence,executed_by) values ('"+other+"','"+CYCLE+"','EXTERNAL_HR_REFERENCE','REF-X','{}','"+REVIEWER+"')");}
    private static void seed()throws Exception{try(Connection c=connection();Statement s=c.createStatement()){s.execute("insert into org.organization(id,tenant_id,org_code,org_name,org_type,path,status) values ('"+CENTER+"','"+TENANT+"','P011_CENTER','P011 Center','CENTER','p011_center'::ltree,'ACTIVE')");s.execute("insert into org.position(id,tenant_id,position_code,position_name,org_id,status) values ('"+POSITION+"','"+TENANT+"','P011_POS','P011 Position','"+CENTER+"','ACTIVE')");s.execute("insert into org.employee(id,tenant_id,employee_no,person_name,employment_status,hire_date,primary_org_id,primary_position_id) values ('"+EMPLOYEE+"','"+TENANT+"','P011-E001','P011 Employee','ACTIVE',current_date-30,'"+CENTER+"','"+POSITION+"'),('"+REVIEWER+"','"+TENANT+"','P011-E002','P011 Reviewer','ACTIVE',current_date-30,'"+CENTER+"','"+POSITION+"')");s.execute("insert into performance.performance_cycle(id,tenant_id,business_no,status,created_by,owner_center_id,owner_employee_id,content_version,employee_event_type,fact_occurred_at,period_or_course_no) values ('"+CYCLE+"','"+TENANT+"','P011-DB-1','Calibration','"+REVIEWER+"','"+CENTER+"','"+EMPLOYEE+"','v1','PERFORMANCE_CYCLE',now(),'2026-H2'),('"+CYCLE2+"','"+TENANT+"','P011-DB-2','Evaluation','"+REVIEWER+"','"+CENTER+"','"+EMPLOYEE+"','v1','PERFORMANCE_CYCLE',now(),'2026-H2')");s.execute("insert into performance.performance_score_fact(id,tenant_id,cycle_id,score_seq,score_type,score_1000,evidence,actor_employee_id) values ('"+SCORE+"','"+TENANT+"','"+CYCLE+"',1,'EMPLOYEE_SELF',800,'{\"source\":\"employee\"}','"+EMPLOYEE+"')");s.execute("insert into performance.performance_cycle_event(id,tenant_id,cycle_id,event_seq,event_type,evidence,actor_employee_id) values ('"+EVENT+"','"+TENANT+"','"+CYCLE+"',1,'TARGET_CONFIRMED','{}','"+EMPLOYEE+"')");s.execute("insert into performance.performance_effect_execution(id,tenant_id,cycle_id,execution_type,external_reference,evidence,executed_by) values ('"+EFFECT+"','"+TENANT+"','"+CYCLE+"','DEVELOPMENT_PLAN','DEV-REF-001','{}','"+REVIEWER+"')");}}
    private static void assertSqlState(String expected,String sql){SQLException e=assertThrows(SQLException.class,()->{try(Connection c=connection();Statement s=c.createStatement()){s.execute(sql);}});assertEquals(expected,e.getSQLState());}private static String workflowCount(String table){return "select count(*) from workflow."+table+" x join workflow.wf_version v on v.id=x.version_id and v.tenant_id=x.tenant_id join workflow.wf_definition d on d.id=v.definition_id and d.tenant_id=v.tenant_id where d.process_code='P011' and v.status='PUBLISHED' and x.tenant_id='"+TENANT+"' and not x.is_deleted";}private static long scalar(Statement s,String sql)throws SQLException{try(var r=s.executeQuery(sql)){r.next();return r.getLong(1);}}private static Connection connection()throws SQLException{return DriverManager.getConnection(omsUrl,POSTGRES.getUsername(),POSTGRES.getPassword());}private static Path root(){Path p=Path.of("").toAbsolutePath();while(p!=null){if(Files.exists(p.resolve("mvnw")))return p;p=p.getParent();}throw new IllegalStateException("repository root not found");}
}
