erDiagram
  WORKFLOW_WF_INSTANCE ||--o| ADMINISTRATION_LARGE_EVENT : drives
  ADMINISTRATION_LARGE_EVENT ||--o{ ADMINISTRATION_LARGE_EVENT_ITEM : contains
  ADMINISTRATION_LARGE_EVENT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| ADMINISTRATION_OFFICIAL_DOCUMENT : drives
  ADMINISTRATION_OFFICIAL_DOCUMENT ||--o{ ADMINISTRATION_OFFICIAL_DOCUMENT_ITEM : contains
  ADMINISTRATION_OFFICIAL_DOCUMENT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
