erDiagram
  WORKFLOW_WF_INSTANCE ||--o| CLEANING_CLEANING_TASK : drives
  CLEANING_CLEANING_TASK ||--o{ CLEANING_CLEANING_TASK_ITEM : contains
  CLEANING_CLEANING_TASK ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| CLEANING_EVENT_SUPPORT : drives
  CLEANING_EVENT_SUPPORT ||--o{ CLEANING_EVENT_SUPPORT_ITEM : contains
  CLEANING_EVENT_SUPPORT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| CLEANING_POLLUTION_INCIDENT : drives
  CLEANING_POLLUTION_INCIDENT ||--o{ CLEANING_POLLUTION_INCIDENT_ITEM : contains
  CLEANING_POLLUTION_INCIDENT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
