erDiagram
  WORKFLOW_WF_INSTANCE ||--o| COLLABORATION_EXECUTIVE_DIRECTIVE : drives
  COLLABORATION_EXECUTIVE_DIRECTIVE ||--o{ COLLABORATION_EXECUTIVE_DIRECTIVE_ITEM : contains
  COLLABORATION_EXECUTIVE_DIRECTIVE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| COLLABORATION_MAJOR_MATTER : drives
  COLLABORATION_MAJOR_MATTER ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| COLLABORATION_MEETING : drives
  COLLABORATION_MEETING ||--o{ COLLABORATION_MEETING_ITEM : contains
  COLLABORATION_MEETING ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| COLLABORATION_NOTICE : drives
  COLLABORATION_NOTICE ||--o{ COLLABORATION_NOTICE_ITEM : contains
  COLLABORATION_NOTICE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
