erDiagram
  WORKFLOW_WF_INSTANCE ||--o| CONTENT_CHANGE_REQUEST : drives
  CONTENT_CHANGE_REQUEST ||--o{ CONTENT_CHANGE_REQUEST_ITEM : contains
  CONTENT_CHANGE_REQUEST ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| CONTENT_MATERIAL_REQUEST : drives
  CONTENT_MATERIAL_REQUEST ||--o{ CONTENT_MATERIAL_REQUEST_ITEM : contains
  CONTENT_MATERIAL_REQUEST ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| CONTENT_SHOOTING_TASK : drives
  CONTENT_SHOOTING_TASK ||--o{ CONTENT_SHOOTING_TASK_ITEM : contains
  CONTENT_SHOOTING_TASK ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
