erDiagram
  WORKFLOW_WF_INSTANCE ||--o| CRM_CHANNEL_PARTNER : drives
  CRM_CHANNEL_PARTNER ||--o{ CRM_CHANNEL_PARTNER_ITEM : contains
  CRM_CHANNEL_PARTNER ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| CRM_OPPORTUNITY : drives
  CRM_OPPORTUNITY ||--o{ CRM_OPPORTUNITY_ITEM : contains
  CRM_OPPORTUNITY ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
