erDiagram
  WORKFLOW_WF_INSTANCE ||--o| DEVOPS_DEFECT : drives
  DEVOPS_DEFECT ||--o{ DEVOPS_DEFECT_ITEM : contains
  DEVOPS_DEFECT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| DEVOPS_RELEASE : drives
  DEVOPS_RELEASE ||--o{ DEVOPS_RELEASE_ITEM : contains
  DEVOPS_RELEASE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| DEVOPS_REQUIREMENT : drives
  DEVOPS_REQUIREMENT ||--o{ DEVOPS_REQUIREMENT_ITEM : contains
  DEVOPS_REQUIREMENT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
