erDiagram
  WORKFLOW_WF_INSTANCE ||--o| DRONE_FLIGHT_CANCELLATION : drives
  DRONE_FLIGHT_CANCELLATION ||--o{ DRONE_FLIGHT_CANCELLATION_ITEM : contains
  DRONE_FLIGHT_CANCELLATION ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| DRONE_FLIGHT_INCIDENT : drives
  DRONE_FLIGHT_INCIDENT ||--o{ DRONE_FLIGHT_INCIDENT_ITEM : contains
  DRONE_FLIGHT_INCIDENT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| DRONE_FLIGHT_TASK : drives
  DRONE_FLIGHT_TASK ||--o{ DRONE_FLIGHT_TASK_ITEM : contains
  DRONE_FLIGHT_TASK ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
