erDiagram
  WORKFLOW_WF_INSTANCE ||--o| ECOMMERCE_OTA_ORDER : drives
  ECOMMERCE_OTA_ORDER ||--o{ ECOMMERCE_OTA_ORDER_ITEM : contains
  ECOMMERCE_OTA_ORDER ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| ECOMMERCE_PRODUCT_LISTING : drives
  ECOMMERCE_PRODUCT_LISTING ||--o{ ECOMMERCE_PRODUCT_LISTING_ITEM : contains
  ECOMMERCE_PRODUCT_LISTING ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| ECOMMERCE_REFUND_ORDER : drives
  ECOMMERCE_REFUND_ORDER ||--o{ ECOMMERCE_REFUND_ORDER_ITEM : contains
  ECOMMERCE_REFUND_ORDER ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| ECOMMERCE_REVIEW_COMPLAINT : drives
  ECOMMERCE_REVIEW_COMPLAINT ||--o{ ECOMMERCE_REVIEW_COMPLAINT_ITEM : contains
  ECOMMERCE_REVIEW_COMPLAINT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
