erDiagram
  WORKFLOW_WF_INSTANCE ||--o| HR_EMPLOYEE_OFFBOARDING : drives
  HR_EMPLOYEE_OFFBOARDING ||--o{ HR_EMPLOYEE_OFFBOARDING_ITEM : contains
  HR_EMPLOYEE_OFFBOARDING ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| HR_EMPLOYEE_ONBOARDING : drives
  HR_EMPLOYEE_ONBOARDING ||--o{ HR_EMPLOYEE_ONBOARDING_ITEM : contains
  HR_EMPLOYEE_ONBOARDING ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| HR_EMPLOYEE_PROFILE_CHANGE : drives
  HR_EMPLOYEE_PROFILE_CHANGE ||--o{ HR_EMPLOYEE_PROFILE_CHANGE_ITEM : contains
  HR_EMPLOYEE_PROFILE_CHANGE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| HR_EMPLOYEE_TRANSFER : drives
  HR_EMPLOYEE_TRANSFER ||--o{ HR_EMPLOYEE_TRANSFER_ITEM : contains
  HR_EMPLOYEE_TRANSFER ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| HR_PROMOTION_REQUEST : drives
  HR_PROMOTION_REQUEST ||--o{ HR_PROMOTION_REQUEST_ITEM : contains
  HR_PROMOTION_REQUEST ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
