erDiagram
  WORKFLOW_WF_INSTANCE ||--o| IAM_ACCOUNT_EXECUTION : drives
  IAM_ACCOUNT_EXECUTION ||--o{ IAM_ACCOUNT_EXECUTION_ITEM : contains
  IAM_ACCOUNT_EXECUTION ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| IAM_LOGIN_SESSION : drives
  IAM_LOGIN_SESSION ||--o{ IAM_LOGIN_SESSION_ITEM : contains
  IAM_LOGIN_SESSION ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| IAM_PERMISSION_REQUEST : drives
  IAM_PERMISSION_REQUEST ||--o{ IAM_PERMISSION_REQUEST_ITEM : contains
  IAM_PERMISSION_REQUEST ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
