erDiagram
  WORKFLOW_WF_INSTANCE ||--o| ITOPS_EVENT_SUPPORT : drives
  ITOPS_EVENT_SUPPORT ||--o{ ITOPS_EVENT_SUPPORT_ITEM : contains
  ITOPS_EVENT_SUPPORT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| ITOPS_NETWORK_CHANGE : drives
  ITOPS_NETWORK_CHANGE ||--o{ ITOPS_NETWORK_CHANGE_ITEM : contains
  ITOPS_NETWORK_CHANGE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| ITOPS_NETWORK_INCIDENT : drives
  ITOPS_NETWORK_INCIDENT ||--o{ ITOPS_NETWORK_INCIDENT_ITEM : contains
  ITOPS_NETWORK_INCIDENT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| ITOPS_RECOVERY_DRILL : drives
  ITOPS_RECOVERY_DRILL ||--o{ ITOPS_RECOVERY_DRILL_ITEM : contains
  ITOPS_RECOVERY_DRILL ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| ITOPS_SERVICE_REQUEST : drives
  ITOPS_SERVICE_REQUEST ||--o{ ITOPS_SERVICE_REQUEST_ITEM : contains
  ITOPS_SERVICE_REQUEST ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
