erDiagram
  WORKFLOW_WF_INSTANCE ||--o| MEDIA_AD_CAMPAIGN : drives
  MEDIA_AD_CAMPAIGN ||--o{ MEDIA_AD_CAMPAIGN_ITEM : contains
  MEDIA_AD_CAMPAIGN ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| MEDIA_LIVE_SESSION : drives
  MEDIA_LIVE_SESSION ||--o{ MEDIA_LIVE_SESSION_ITEM : contains
  MEDIA_LIVE_SESSION ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| MEDIA_PUBLIC_OPINION_CASE : drives
  MEDIA_PUBLIC_OPINION_CASE ||--o{ MEDIA_PUBLIC_OPINION_CASE_ITEM : contains
  MEDIA_PUBLIC_OPINION_CASE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| MEDIA_SHORT_VIDEO_RELEASE : drives
  MEDIA_SHORT_VIDEO_RELEASE ||--o{ MEDIA_SHORT_VIDEO_RELEASE_ITEM : contains
  MEDIA_SHORT_VIDEO_RELEASE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
