erDiagram
  WORKFLOW_WF_INSTANCE ||--o| MERCHANT_MERCHANT_ADMISSION : drives
  MERCHANT_MERCHANT_ADMISSION ||--o{ MERCHANT_MERCHANT_ADMISSION_ITEM : contains
  MERCHANT_MERCHANT_ADMISSION ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| MERCHANT_MERCHANT_EXIT : drives
  MERCHANT_MERCHANT_EXIT ||--o{ MERCHANT_MERCHANT_EXIT_ITEM : contains
  MERCHANT_MERCHANT_EXIT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| MERCHANT_MERCHANT_INSPECTION : drives
  MERCHANT_MERCHANT_INSPECTION ||--o{ MERCHANT_MERCHANT_INSPECTION_ITEM : contains
  MERCHANT_MERCHANT_INSPECTION ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
