erDiagram
  WORKFLOW_WF_INSTANCE ||--o| PLANNING_CHANGE_REQUEST : drives
  PLANNING_CHANGE_REQUEST ||--o{ PLANNING_CHANGE_REQUEST_ITEM : contains
  PLANNING_CHANGE_REQUEST ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| PLANNING_EVENT_HANDOVER : drives
  PLANNING_EVENT_HANDOVER ||--o{ PLANNING_EVENT_HANDOVER_ITEM : contains
  PLANNING_EVENT_HANDOVER ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| PLANNING_PROJECT : drives
  PLANNING_PROJECT ||--o{ PLANNING_PROJECT_ITEM : contains
  PLANNING_PROJECT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
