erDiagram
  WORKFLOW_WF_INSTANCE ||--o| PROCUREMENT_EMERGENCY_PURCHASE : drives
  PROCUREMENT_EMERGENCY_PURCHASE ||--o{ PROCUREMENT_EMERGENCY_PURCHASE_ITEM : contains
  PROCUREMENT_EMERGENCY_PURCHASE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| PROCUREMENT_PURCHASE_REQUEST : drives
  PROCUREMENT_PURCHASE_REQUEST ||--o{ PROCUREMENT_PURCHASE_REQUEST_ITEM : contains
  PROCUREMENT_PURCHASE_REQUEST ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| PROCUREMENT_PURCHASE_RETURN : drives
  PROCUREMENT_PURCHASE_RETURN ||--o{ PROCUREMENT_PURCHASE_RETURN_ITEM : contains
  PROCUREMENT_PURCHASE_RETURN ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
