erDiagram
  WORKFLOW_WF_INSTANCE ||--o| REWARD_DISCIPLINE_CASE : drives
  REWARD_DISCIPLINE_CASE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| REWARD_POINT_TRANSACTION : drives
  REWARD_POINT_TRANSACTION ||--o{ REWARD_POINT_TRANSACTION_ITEM : contains
  REWARD_POINT_TRANSACTION ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| REWARD_REWARD_CASE : drives
  REWARD_REWARD_CASE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
