erDiagram
  WORKFLOW_WF_INSTANCE ||--o| SECURITY_CROWD_ALERT : drives
  SECURITY_CROWD_ALERT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| SECURITY_EVENT_SECURITY_PLAN : drives
  SECURITY_EVENT_SECURITY_PLAN ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| SECURITY_PATROL_TASK : drives
  SECURITY_PATROL_TASK ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| SECURITY_SECURITY_INCIDENT : drives
  SECURITY_SECURITY_INCIDENT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
