erDiagram
  WORKFLOW_WF_INSTANCE ||--o| TICKETING_OFFLINE_CHECK_EVENT : drives
  TICKETING_OFFLINE_CHECK_EVENT ||--o{ TICKETING_OFFLINE_CHECK_EVENT_ITEM : contains
  TICKETING_OFFLINE_CHECK_EVENT ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| TICKETING_TICKET_ORDER : drives
  TICKETING_TICKET_ORDER ||--o{ TICKETING_TICKET_ORDER_ITEM : contains
  TICKETING_TICKET_ORDER ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
  WORKFLOW_WF_INSTANCE ||--o| TICKETING_TICKET_REFUND_CHANGE : drives
  TICKETING_TICKET_REFUND_CHANGE ||--o{ TICKETING_TICKET_REFUND_CHANGE_ITEM : contains
  TICKETING_TICKET_REFUND_CHANGE ||--o{ DOCUMENT_ATTACHMENT_LINK : attaches
